// Code generated by BobGen sqlite v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var GameServerOperationEvents = Table[
	gameServerOperationEventColumns,
	gameServerOperationEventIndexes,
	gameServerOperationEventForeignKeys,
	gameServerOperationEventUniques,
	gameServerOperationEventChecks,
]{
	Schema: "",
	Name:   "game_server_operation_event",
	Columns: gameServerOperationEventColumns{
		ID: column{
			Name:      "id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		GameServerID: column{
			Name:      "game_server_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Operation: column{
			Name:      "operation",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Phase: column{
			Name:      "phase",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Outcome: column{
			Name:      "outcome",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		StartedAt: column{
			Name:      "started_at",
			DBType:    "DATETIME",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CompletedAt: column{
			Name:      "completed_at",
			DBType:    "DATETIME",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		DurationMS: column{
			Name:      "duration_ms",
			DBType:    "INTEGER",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		BytesProcessed: column{
			Name:      "bytes_processed",
			DBType:    "INTEGER",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Source: column{
			Name:      "source",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: gameServerOperationEventIndexes{
		GameServerOperationEventRetentionIdx: index{
			Type: "c",
			Name: "game_server_operation_event_retention_idx",
			Columns: []indexColumn{
				{
					Name:         "coalesce(completed_at, started_at)",
					Desc:         null.FromCond(false, true),
					IsExpression: true,
				},
			},
			Unique:  false,
			Comment: "",
			Partial: false,
		},
		GameServerOperationEventServerTimeIdx: index{
			Type: "c",
			Name: "game_server_operation_event_server_time_idx",
			Columns: []indexColumn{
				{
					Name:         "game_server_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "started_at",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
			Partial: false,
		},
		SqliteAutoindexGameServerOperationEvent1: index{
			Type: "pk",
			Name: "sqlite_autoindex_game_server_operation_event_1",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_game_server_operation_event",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: gameServerOperationEventForeignKeys{
		FKGameServerOperationEvent0: foreignKey{
			constraint: constraint{
				Name:    "fk_game_server_operation_event_0",
				Columns: []string{"game_server_id"},
				Comment: "",
			},
			ForeignTable:   "game_server",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type gameServerOperationEventColumns struct {
	ID             column
	GameServerID   column
	Operation      column
	Phase          column
	Outcome        column
	StartedAt      column
	CompletedAt    column
	DurationMS     column
	BytesProcessed column
	Source         column
}

func (c gameServerOperationEventColumns) AsSlice() []column {
	return []column{
		c.ID, c.GameServerID, c.Operation, c.Phase, c.Outcome, c.StartedAt, c.CompletedAt, c.DurationMS, c.BytesProcessed, c.Source,
	}
}

type gameServerOperationEventIndexes struct {
	GameServerOperationEventRetentionIdx     index
	GameServerOperationEventServerTimeIdx    index
	SqliteAutoindexGameServerOperationEvent1 index
}

func (i gameServerOperationEventIndexes) AsSlice() []index {
	return []index{
		i.GameServerOperationEventRetentionIdx, i.GameServerOperationEventServerTimeIdx, i.SqliteAutoindexGameServerOperationEvent1,
	}
}

type gameServerOperationEventForeignKeys struct {
	FKGameServerOperationEvent0 foreignKey
}

func (f gameServerOperationEventForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKGameServerOperationEvent0,
	}
}

type gameServerOperationEventUniques struct{}

func (u gameServerOperationEventUniques) AsSlice() []constraint {
	return []constraint{}
}

type gameServerOperationEventChecks struct{}

func (c gameServerOperationEventChecks) AsSlice() []check {
	return []check{}
}
