// Code generated by BobGen sqlite v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var GameServerLifecycleEvents = Table[
	gameServerLifecycleEventColumns,
	gameServerLifecycleEventIndexes,
	gameServerLifecycleEventForeignKeys,
	gameServerLifecycleEventUniques,
	gameServerLifecycleEventChecks,
]{
	Schema: "",
	Name:   "game_server_lifecycle_event",
	Columns: gameServerLifecycleEventColumns{
		ID: column{
			Name:      "id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		GameServerID: column{
			Name:      "game_server_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		NodeID: column{
			Name:      "node_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ExecutionID: column{
			Name:      "execution_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		TransitionSequence: column{
			Name:      "transition_sequence",
			DBType:    "INTEGER",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		PreviousStatus: column{
			Name:      "previous_status",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Status: column{
			Name:      "status",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		IntentionalStop: column{
			Name:      "intentional_stop",
			DBType:    "BOOLEAN",
			Default:   "false",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ExitCode: column{
			Name:      "exit_code",
			DBType:    "INTEGER",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		ObservedAt: column{
			Name:      "observed_at",
			DBType:    "DATETIME",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: gameServerLifecycleEventIndexes{
		GameServerLifecycleEventObservedAtIdx: index{
			Type: "c",
			Name: "game_server_lifecycle_event_observed_at_idx",
			Columns: []indexColumn{
				{
					Name:         "observed_at",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
			Partial: false,
		},
		GameServerLifecycleEventServerTimeIdx: index{
			Type: "c",
			Name: "game_server_lifecycle_event_server_time_idx",
			Columns: []indexColumn{
				{
					Name:         "game_server_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "observed_at",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
			Partial: false,
		},
		SqliteAutoindexGameServerLifecycleEvent2: index{
			Type: "u",
			Name: "sqlite_autoindex_game_server_lifecycle_event_2",
			Columns: []indexColumn{
				{
					Name:         "node_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "game_server_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "execution_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "transition_sequence",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
		SqliteAutoindexGameServerLifecycleEvent1: index{
			Type: "pk",
			Name: "sqlite_autoindex_game_server_lifecycle_event_1",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_game_server_lifecycle_event",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: gameServerLifecycleEventForeignKeys{
		FKGameServerLifecycleEvent0: foreignKey{
			constraint: constraint{
				Name:    "fk_game_server_lifecycle_event_0",
				Columns: []string{"game_server_id"},
				Comment: "",
			},
			ForeignTable:   "game_server",
			ForeignColumns: []string{"id"},
		},
	},
	Uniques: gameServerLifecycleEventUniques{
		SqliteAutoindexGameServerLifecycleEvent2: constraint{
			Name:    "sqlite_autoindex_game_server_lifecycle_event_2",
			Columns: []string{"node_id", "game_server_id", "execution_id", "transition_sequence"},
			Comment: "",
		},
	},

	Comment: "",
}

type gameServerLifecycleEventColumns struct {
	ID                 column
	GameServerID       column
	NodeID             column
	ExecutionID        column
	TransitionSequence column
	PreviousStatus     column
	Status             column
	IntentionalStop    column
	ExitCode           column
	ObservedAt         column
}

func (c gameServerLifecycleEventColumns) AsSlice() []column {
	return []column{
		c.ID, c.GameServerID, c.NodeID, c.ExecutionID, c.TransitionSequence, c.PreviousStatus, c.Status, c.IntentionalStop, c.ExitCode, c.ObservedAt,
	}
}

type gameServerLifecycleEventIndexes struct {
	GameServerLifecycleEventObservedAtIdx    index
	GameServerLifecycleEventServerTimeIdx    index
	SqliteAutoindexGameServerLifecycleEvent2 index
	SqliteAutoindexGameServerLifecycleEvent1 index
}

func (i gameServerLifecycleEventIndexes) AsSlice() []index {
	return []index{
		i.GameServerLifecycleEventObservedAtIdx, i.GameServerLifecycleEventServerTimeIdx, i.SqliteAutoindexGameServerLifecycleEvent2, i.SqliteAutoindexGameServerLifecycleEvent1,
	}
}

type gameServerLifecycleEventForeignKeys struct {
	FKGameServerLifecycleEvent0 foreignKey
}

func (f gameServerLifecycleEventForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKGameServerLifecycleEvent0,
	}
}

type gameServerLifecycleEventUniques struct {
	SqliteAutoindexGameServerLifecycleEvent2 constraint
}

func (u gameServerLifecycleEventUniques) AsSlice() []constraint {
	return []constraint{
		u.SqliteAutoindexGameServerLifecycleEvent2,
	}
}

type gameServerLifecycleEventChecks struct{}

func (c gameServerLifecycleEventChecks) AsSlice() []check {
	return []check{}
}
