// Code generated by BobGen sqlite v0.48.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var GameServerStatusPageIdentifiers = Table[
	gameServerStatusPageIdentifierColumns,
	gameServerStatusPageIdentifierIndexes,
	gameServerStatusPageIdentifierForeignKeys,
	gameServerStatusPageIdentifierUniques,
	gameServerStatusPageIdentifierChecks,
]{
	Schema: "",
	Name:   "game_server_status_page_identifier",
	Columns: gameServerStatusPageIdentifierColumns{
		Identifier: column{
			Name:      "identifier",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "DATETIME",
			Default:   "current_timestamp",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: gameServerStatusPageIdentifierIndexes{
		SqliteAutoindexGameServerStatusPageIdentifier1: index{
			Type: "pk",
			Name: "sqlite_autoindex_game_server_status_page_identifier_1",
			Columns: []indexColumn{
				{
					Name:         "identifier",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_game_server_status_page_identifier",
		Columns: []string{"identifier"},
		Comment: "",
	},

	Comment: "",
}

type gameServerStatusPageIdentifierColumns struct {
	Identifier column
	CreatedAt  column
}

func (c gameServerStatusPageIdentifierColumns) AsSlice() []column {
	return []column{
		c.Identifier, c.CreatedAt,
	}
}

type gameServerStatusPageIdentifierIndexes struct {
	SqliteAutoindexGameServerStatusPageIdentifier1 index
}

func (i gameServerStatusPageIdentifierIndexes) AsSlice() []index {
	return []index{
		i.SqliteAutoindexGameServerStatusPageIdentifier1,
	}
}

type gameServerStatusPageIdentifierForeignKeys struct{}

func (f gameServerStatusPageIdentifierForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type gameServerStatusPageIdentifierUniques struct{}

func (u gameServerStatusPageIdentifierUniques) AsSlice() []constraint {
	return []constraint{}
}

type gameServerStatusPageIdentifierChecks struct{}

func (c gameServerStatusPageIdentifierChecks) AsSlice() []check {
	return []check{}
}
