// Code generated by BobGen sqlite v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Ips = Table[
	ipColumns,
	ipIndexes,
	ipForeignKeys,
	ipUniques,
	ipChecks,
]{
	Schema: "",
	Name:   "ip",
	Columns: ipColumns{
		Address: column{
			Name:      "address",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Usable: column{
			Name:      "usable",
			DBType:    "BOOLEAN",
			Default:   "true",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		External: column{
			Name:      "external",
			DBType:    "BOOLEAN",
			Default:   "false",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		AutomaticallyAdded: column{
			Name:      "automatically_added",
			DBType:    "BOOLEAN",
			Default:   "false",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		NodeID: column{
			Name:      "node_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: ipIndexes{
		IdxIPNodeID: index{
			Type: "c",
			Name: "idx_ip_node_id",
			Columns: []indexColumn{
				{
					Name:         "node_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
			Partial: false,
		},
		SqliteAutoindexIP1: index{
			Type: "pk",
			Name: "sqlite_autoindex_ip_1",
			Columns: []indexColumn{
				{
					Name:         "address",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "node_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_ip",
		Columns: []string{"address", "node_id"},
		Comment: "",
	},
	ForeignKeys: ipForeignKeys{
		FKIP0: foreignKey{
			constraint: constraint{
				Name:    "fk_ip_0",
				Columns: []string{"node_id"},
				Comment: "",
			},
			ForeignTable:   "node",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type ipColumns struct {
	Address            column
	Usable             column
	External           column
	AutomaticallyAdded column
	NodeID             column
}

func (c ipColumns) AsSlice() []column {
	return []column{
		c.Address, c.Usable, c.External, c.AutomaticallyAdded, c.NodeID,
	}
}

type ipIndexes struct {
	IdxIPNodeID        index
	SqliteAutoindexIP1 index
}

func (i ipIndexes) AsSlice() []index {
	return []index{
		i.IdxIPNodeID, i.SqliteAutoindexIP1,
	}
}

type ipForeignKeys struct {
	FKIP0 foreignKey
}

func (f ipForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKIP0,
	}
}

type ipUniques struct{}

func (u ipUniques) AsSlice() []constraint {
	return []constraint{}
}

type ipChecks struct{}

func (c ipChecks) AsSlice() []check {
	return []check{}
}
