// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var ScheduledTasks = Table[
	scheduledTaskColumns,
	scheduledTaskIndexes,
	scheduledTaskForeignKeys,
	scheduledTaskUniques,
	scheduledTaskChecks,
]{
	Schema: "",
	Name:   "scheduled_task",
	Columns: scheduledTaskColumns{
		ID: column{
			Name:      "id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		GameServerID: column{
			Name:      "game_server_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedBy: column{
			Name:      "created_by",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		TaskType: column{
			Name:      "task_type",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CronExpression: column{
			Name:      "cron_expression",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Timezone: column{
			Name:      "timezone",
			DBType:    "TEXT",
			Default:   "'UTC'",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ConsoleCommand: column{
			Name:      "console_command",
			DBType:    "TEXT",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Enabled: column{
			Name:      "enabled",
			DBType:    "INTEGER",
			Default:   "1",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		LastRunAt: column{
			Name:      "last_run_at",
			DBType:    "DATETIME",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		NextRunAt: column{
			Name:      "next_run_at",
			DBType:    "DATETIME",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "DATETIME",
			Default:   "current_timestamp",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "DATETIME",
			Default:   "current_timestamp",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: scheduledTaskIndexes{
		IdxScheduledTaskServerName: index{
			Type: "c",
			Name: "idx_scheduled_task_server_name",
			Columns: []indexColumn{
				{
					Name:         "game_server_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "name",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
		IdxScheduledTaskEnabled: index{
			Type: "c",
			Name: "idx_scheduled_task_enabled",
			Columns: []indexColumn{
				{
					Name:         "enabled",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
			Partial: false,
		},
		IdxScheduledTaskGameServerID: index{
			Type: "c",
			Name: "idx_scheduled_task_game_server_id",
			Columns: []indexColumn{
				{
					Name:         "game_server_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
			Partial: false,
		},
		SqliteAutoindexScheduledTask1: index{
			Type: "pk",
			Name: "sqlite_autoindex_scheduled_task_1",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_scheduled_task",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: scheduledTaskForeignKeys{
		FKScheduledTask0: foreignKey{
			constraint: constraint{
				Name:    "fk_scheduled_task_0",
				Columns: []string{"created_by"},
				Comment: "",
			},
			ForeignTable:   "user",
			ForeignColumns: []string{"id"},
		},
		FKScheduledTask1: foreignKey{
			constraint: constraint{
				Name:    "fk_scheduled_task_1",
				Columns: []string{"game_server_id"},
				Comment: "",
			},
			ForeignTable:   "game_server",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type scheduledTaskColumns struct {
	ID             column
	GameServerID   column
	CreatedBy      column
	Name           column
	TaskType       column
	CronExpression column
	Timezone       column
	ConsoleCommand column
	Enabled        column
	LastRunAt      column
	NextRunAt      column
	CreatedAt      column
	UpdatedAt      column
}

func (c scheduledTaskColumns) AsSlice() []column {
	return []column{
		c.ID, c.GameServerID, c.CreatedBy, c.Name, c.TaskType, c.CronExpression, c.Timezone, c.ConsoleCommand, c.Enabled, c.LastRunAt, c.NextRunAt, c.CreatedAt, c.UpdatedAt,
	}
}

type scheduledTaskIndexes struct {
	IdxScheduledTaskServerName    index
	IdxScheduledTaskEnabled       index
	IdxScheduledTaskGameServerID  index
	SqliteAutoindexScheduledTask1 index
}

func (i scheduledTaskIndexes) AsSlice() []index {
	return []index{
		i.IdxScheduledTaskServerName, i.IdxScheduledTaskEnabled, i.IdxScheduledTaskGameServerID, i.SqliteAutoindexScheduledTask1,
	}
}

type scheduledTaskForeignKeys struct {
	FKScheduledTask0 foreignKey
	FKScheduledTask1 foreignKey
}

func (f scheduledTaskForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKScheduledTask0, f.FKScheduledTask1,
	}
}

type scheduledTaskUniques struct{}

func (u scheduledTaskUniques) AsSlice() []constraint {
	return []constraint{}
}

type scheduledTaskChecks struct{}

func (c scheduledTaskChecks) AsSlice() []check {
	return []check{}
}
