// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var SystemConfigs = Table[
	systemConfigColumns,
	systemConfigIndexes,
	systemConfigForeignKeys,
	systemConfigUniques,
	systemConfigChecks,
]{
	Schema: "",
	Name:   "system_config",
	Columns: systemConfigColumns{
		Key: column{
			Name:      "key",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Value: column{
			Name:      "value",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "DATETIME",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: systemConfigIndexes{
		SqliteAutoindexSystemConfig1: index{
			Type: "pk",
			Name: "sqlite_autoindex_system_config_1",
			Columns: []indexColumn{
				{
					Name:         "key",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_system_config",
		Columns: []string{"key"},
		Comment: "",
	},

	Comment: "",
}

type systemConfigColumns struct {
	Key       column
	Value     column
	UpdatedAt column
}

func (c systemConfigColumns) AsSlice() []column {
	return []column{
		c.Key, c.Value, c.UpdatedAt,
	}
}

type systemConfigIndexes struct {
	SqliteAutoindexSystemConfig1 index
}

func (i systemConfigIndexes) AsSlice() []index {
	return []index{
		i.SqliteAutoindexSystemConfig1,
	}
}

type systemConfigForeignKeys struct{}

func (f systemConfigForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type systemConfigUniques struct{}

func (u systemConfigUniques) AsSlice() []constraint {
	return []constraint{}
}

type systemConfigChecks struct{}

func (c systemConfigChecks) AsSlice() []check {
	return []check{}
}
