## Setup Caddy
name: xylona-development
services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:2019:2019"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile