version: 2

# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - id: xylona
    binary: xylona
    main: ./cmd/xylona
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - >-
        -s -w
        -X github.com/ClintonCollins/Xylona/pkg/version.softwareVersionStamp={{ if .Tag }}{{ .Tag }}{{ else }}{{ .Version }}-g{{ .ShortCommit }}{{ end }}
  - id: xylona-node
    binary: xylona-node
    main: ./cmd/xylona-node
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - >-
        -s -w
        -X github.com/ClintonCollins/Xylona/pkg/version.softwareVersionStamp={{ if .Tag }}{{ .Tag }}{{ else }}{{ .Version }}-g{{ .ShortCommit }}{{ end }}

archives:
  - id: xylona-binary
    ids:
      - xylona
    formats:
      - binary
    name_template: >-
      xylona_
      {{- .Os }}_
      {{- .Arch }}
  - id: xylona-node-binary
    ids:
      - xylona-node
    formats:
      - binary
    name_template: >-
      xylona-node_
      {{- .Os }}_
      {{- .Arch }}
checksum:
  name_template: 'checksums.txt'
signs:
  - id: legacy-gpg
    cmd: gpg
    signature: '${artifact}.sig'
    args:
      - '--batch'
      - '--output'
      - '${signature}'
      - '--detach-sign'
      - '${artifact}'
    artifacts: checksum
  - id: sigstore
    cmd: cosign
    signature: '${artifact}.sigstore.json'
    args:
      - 'sign-blob'
      - '--bundle=${signature}'
      - '${artifact}'
      - '--yes'
    artifacts: checksum
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
