version: 3

tasks:
  sql-migrate-up:
    dir: ./sql
    cmds:
      - sql-migrate up
    desc: Migrate SQL schema up

  sql-migrate-down:
    dir: ./sql
    cmds:
      - sql-migrate down
    desc: Migrate SQL schema down

  bobgen:
    dir: ./sql
    cmds:
      - go run github.com/stephenafamo/bob/gen/bobgen-sqlite@v0.25.0 -c ./bobgen.yaml
    desc: Generate boilerplate code

  proto-gen:
    dir: ./proto
    cmds:
      - buf generate
    desc: Generate connect_rpc code