// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var FederationLocalIdentityErrors = &federationLocalIdentityErrors{
	ErrUniquePkMainFederationLocalIdentity: &UniqueConstraintError{
		schema:  "",
		table:   "federation_local_identity",
		columns: []string{"id"},
		s:       "pk_main_federation_local_identity",
	},
}

type federationLocalIdentityErrors struct {
	ErrUniquePkMainFederationLocalIdentity *UniqueConstraintError
}
