// Code generated by BobGen sqlite v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var GameServerSevenDaysToDieMapShareErrors = &gameServerSevenDaysToDieMapShareErrors{
	ErrUniquePkMainGameServerSevenDaysToDieMapShare: &UniqueConstraintError{
		schema:  "",
		table:   "game_server_seven_days_to_die_map_share",
		columns: []string{"id"},
		s:       "pk_main_game_server_seven_days_to_die_map_share",
	},

	ErrUniqueSqliteAutoindexGameServerSevenDaysToDieMapShare2: &UniqueConstraintError{
		schema:  "",
		table:   "game_server_seven_days_to_die_map_share",
		columns: []string{"token_hash"},
		s:       "sqlite_autoindex_game_server_seven_days_to_die_map_share_2",
	},
}

type gameServerSevenDaysToDieMapShareErrors struct {
	ErrUniquePkMainGameServerSevenDaysToDieMapShare *UniqueConstraintError

	ErrUniqueSqliteAutoindexGameServerSevenDaysToDieMapShare2 *UniqueConstraintError
}
