// Code generated by BobGen sqlite v0.48.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var GameServerMapShareErrors = &gameServerMapShareErrors{
	ErrUniquePkMainGameServerMapShare: &UniqueConstraintError{
		schema:  "",
		table:   "game_server_map_share",
		columns: []string{"game_server_id"},
		s:       "pk_main_game_server_map_share",
	},

	ErrUniqueSqliteAutoindexGameServerMapShare2: &UniqueConstraintError{
		schema:  "",
		table:   "game_server_map_share",
		columns: []string{"public_identifier"},
		s:       "sqlite_autoindex_game_server_map_share_2",
	},
}

type gameServerMapShareErrors struct {
	ErrUniquePkMainGameServerMapShare *UniqueConstraintError

	ErrUniqueSqliteAutoindexGameServerMapShare2 *UniqueConstraintError
}
