// Code generated by BobGen sqlite v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var InstalledModErrors = &installedModErrors{
	ErrUniquePkMainInstalledMod: &UniqueConstraintError{
		schema:  "",
		table:   "installed_mod",
		columns: []string{"id"},
		s:       "pk_main_installed_mod",
	},

	ErrUniqueSqliteAutoindexInstalledMod2: &UniqueConstraintError{
		schema:  "",
		table:   "installed_mod",
		columns: []string{"game_server_id", "source", "source_id"},
		s:       "sqlite_autoindex_installed_mod_2",
	},
}

type installedModErrors struct {
	ErrUniquePkMainInstalledMod *UniqueConstraintError

	ErrUniqueSqliteAutoindexInstalledMod2 *UniqueConstraintError
}
