// Code generated by BobGen sqlite v0.48.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var LocalSettingErrors = &localSettingErrors{
	ErrUniquePkMainLocalSettings: &UniqueConstraintError{
		schema:  "",
		table:   "local_settings",
		columns: []string{"id"},
		s:       "pk_main_local_settings",
	},
}

type localSettingErrors struct {
	ErrUniquePkMainLocalSettings *UniqueConstraintError
}
