// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var MigrationErrors = &migrationErrors{
	ErrUniquePkMainMigrations: &UniqueConstraintError{
		schema:  "",
		table:   "migrations",
		columns: []string{"id"},
		s:       "pk_main_migrations",
	},
}

type migrationErrors struct {
	ErrUniquePkMainMigrations *UniqueConstraintError
}
