// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var NodeAPIKeyErrors = &nodeAPIKeyErrors{
	ErrUniquePkMainNodeApiKey: &UniqueConstraintError{
		schema:  "",
		table:   "node_api_key",
		columns: []string{"id"},
		s:       "pk_main_node_api_key",
	},

	ErrUniqueSqliteAutoindexNodeApiKey2: &UniqueConstraintError{
		schema:  "",
		table:   "node_api_key",
		columns: []string{"service_name"},
		s:       "sqlite_autoindex_node_api_key_2",
	},
}

type nodeAPIKeyErrors struct {
	ErrUniquePkMainNodeApiKey *UniqueConstraintError

	ErrUniqueSqliteAutoindexNodeApiKey2 *UniqueConstraintError
}
