// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var NodeErrors = &nodeErrors{
	ErrUniquePkMainNode: &UniqueConstraintError{
		schema:  "",
		table:   "node",
		columns: []string{"id"},
		s:       "pk_main_node",
	},
}

type nodeErrors struct {
	ErrUniquePkMainNode *UniqueConstraintError
}
