// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var UserAPIKeyErrors = &userAPIKeyErrors{
	ErrUniquePkMainUserApiKey: &UniqueConstraintError{
		schema:  "",
		table:   "user_api_key",
		columns: []string{"id"},
		s:       "pk_main_user_api_key",
	},
}

type userAPIKeyErrors struct {
	ErrUniquePkMainUserApiKey *UniqueConstraintError
}
