// Code generated by BobGen sqlite v0.22.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	models "github.com/ClintonCollins/Xylona/sql/models"
	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker"
	"github.com/stephenafamo/bob"
)

type MigrationMod interface {
	Apply(*MigrationTemplate)
}

type MigrationModFunc func(*MigrationTemplate)

func (f MigrationModFunc) Apply(n *MigrationTemplate) {
	f(n)
}

type MigrationModSlice []MigrationMod

func (mods MigrationModSlice) Apply(n *MigrationTemplate) {
	for _, f := range mods {
		f.Apply(n)
	}
}

// MigrationTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type MigrationTemplate struct {
	ID        func() string
	AppliedAt func() null.Val[time.Time]

	f *Factory
}

// Apply mods to the MigrationTemplate
func (o *MigrationTemplate) Apply(mods ...MigrationMod) {
	for _, mod := range mods {
		mod.Apply(o)
	}
}

// toModel returns an *models.Migration
// this does nothing with the relationship templates
func (o MigrationTemplate) toModel() *models.Migration {
	m := &models.Migration{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.AppliedAt != nil {
		m.AppliedAt = o.AppliedAt()
	}

	return m
}

// toModels returns an models.MigrationSlice
// this does nothing with the relationship templates
func (o MigrationTemplate) toModels(number int) models.MigrationSlice {
	m := make(models.MigrationSlice, number)

	for i := range m {
		m[i] = o.toModel()
	}

	return m
}

// setModelRels creates and sets the relationships on *models.Migration
// according to the relationships in the template. Nothing is inserted into the db
func (t MigrationTemplate) setModelRels(o *models.Migration) {}

// BuildSetter returns an *models.MigrationSetter
// this does nothing with the relationship templates
func (o MigrationTemplate) BuildSetter() *models.MigrationSetter {
	m := &models.MigrationSetter{}

	if o.ID != nil {
		m.ID = omit.From(o.ID())
	}
	if o.AppliedAt != nil {
		m.AppliedAt = omitnull.FromNull(o.AppliedAt())
	}

	return m
}

// BuildManySetter returns an []*models.MigrationSetter
// this does nothing with the relationship templates
func (o MigrationTemplate) BuildManySetter(number int) []*models.MigrationSetter {
	m := make([]*models.MigrationSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Migration
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MigrationTemplate.Create
func (o MigrationTemplate) Build() *models.Migration {
	m := o.toModel()
	o.setModelRels(m)

	return m
}

// BuildMany returns an models.MigrationSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MigrationTemplate.CreateMany
func (o MigrationTemplate) BuildMany(number int) models.MigrationSlice {
	m := make(models.MigrationSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableMigration(m *models.MigrationSetter) {
	if m.ID.IsUnset() {
		m.ID = omit.From(random[string](nil))
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Migration
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *MigrationTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Migration) (context.Context, error) {
	var err error

	return ctx, err
}

// Create builds a migration and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *MigrationTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Migration, error) {
	_, m, err := o.create(ctx, exec)
	return m, err
}

// create builds a migration and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted model
func (o *MigrationTemplate) create(ctx context.Context, exec bob.Executor) (context.Context, *models.Migration, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableMigration(opt)

	m, err := models.Migrations.Insert(ctx, exec, opt)
	if err != nil {
		return ctx, nil, err
	}
	ctx = migrationCtx.WithValue(ctx, m)

	ctx, err = o.insertOptRels(ctx, exec, m)
	return ctx, m, err
}

// CreateMany builds multiple migrations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o MigrationTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.MigrationSlice, error) {
	_, m, err := o.createMany(ctx, exec, number)
	return m, err
}

// createMany builds multiple migrations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted models
func (o MigrationTemplate) createMany(ctx context.Context, exec bob.Executor, number int) (context.Context, models.MigrationSlice, error) {
	var err error
	m := make(models.MigrationSlice, number)

	for i := range m {
		ctx, m[i], err = o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}

	return ctx, m, nil
}

// Migration has methods that act as mods for the MigrationTemplate
var MigrationMods migrationMods

type migrationMods struct{}

func (m migrationMods) RandomizeAllColumns(f *faker.Faker) MigrationMod {
	return MigrationModSlice{
		MigrationMods.RandomID(f),
		MigrationMods.RandomAppliedAt(f),
	}
}

// Set the model columns to this value
func (m migrationMods) ID(val string) MigrationMod {
	return MigrationModFunc(func(o *MigrationTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m migrationMods) IDFunc(f func() string) MigrationMod {
	return MigrationModFunc(func(o *MigrationTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m migrationMods) UnsetID() MigrationMod {
	return MigrationModFunc(func(o *MigrationTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m migrationMods) RandomID(f *faker.Faker) MigrationMod {
	return MigrationModFunc(func(o *MigrationTemplate) {
		o.ID = func() string {
			return random[string](f)
		}
	})
}

func (m migrationMods) ensureID(f *faker.Faker) MigrationMod {
	return MigrationModFunc(func(o *MigrationTemplate) {
		if o.ID != nil {
			return
		}

		o.ID = func() string {
			return random[string](f)
		}
	})
}

// Set the model columns to this value
func (m migrationMods) AppliedAt(val null.Val[time.Time]) MigrationMod {
	return MigrationModFunc(func(o *MigrationTemplate) {
		o.AppliedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m migrationMods) AppliedAtFunc(f func() null.Val[time.Time]) MigrationMod {
	return MigrationModFunc(func(o *MigrationTemplate) {
		o.AppliedAt = f
	})
}

// Clear any values for the column
func (m migrationMods) UnsetAppliedAt() MigrationMod {
	return MigrationModFunc(func(o *MigrationTemplate) {
		o.AppliedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m migrationMods) RandomAppliedAt(f *faker.Faker) MigrationMod {
	return MigrationModFunc(func(o *MigrationTemplate) {
		o.AppliedAt = func() null.Val[time.Time] {
			return randomNull[time.Time](f)
		}
	})
}

func (m migrationMods) ensureAppliedAt(f *faker.Faker) MigrationMod {
	return MigrationModFunc(func(o *MigrationTemplate) {
		if o.AppliedAt != nil {
			return
		}

		o.AppliedAt = func() null.Val[time.Time] {
			return randomNull[time.Time](f)
		}
	})
}
