// Code generated by BobGen sqlite v0.22.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	models "github.com/ClintonCollins/Xylona/sql/models"
	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker"
	"github.com/stephenafamo/bob"
)

type NotificationMod interface {
	Apply(*NotificationTemplate)
}

type NotificationModFunc func(*NotificationTemplate)

func (f NotificationModFunc) Apply(n *NotificationTemplate) {
	f(n)
}

type NotificationModSlice []NotificationMod

func (mods NotificationModSlice) Apply(n *NotificationTemplate) {
	for _, f := range mods {
		f.Apply(n)
	}
}

// NotificationTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type NotificationTemplate struct {
	ID           func() string
	Event        func() string
	Error        func() string
	Message      func() string
	GameID       func() string
	GameServerID func() string
	Read         func() bool
	CreatedAt    func() time.Time
	UpdatedAt    func() time.Time

	f *Factory
}

// Apply mods to the NotificationTemplate
func (o *NotificationTemplate) Apply(mods ...NotificationMod) {
	for _, mod := range mods {
		mod.Apply(o)
	}
}

// toModel returns an *models.Notification
// this does nothing with the relationship templates
func (o NotificationTemplate) toModel() *models.Notification {
	m := &models.Notification{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Event != nil {
		m.Event = o.Event()
	}
	if o.Error != nil {
		m.Error = o.Error()
	}
	if o.Message != nil {
		m.Message = o.Message()
	}
	if o.GameID != nil {
		m.GameID = o.GameID()
	}
	if o.GameServerID != nil {
		m.GameServerID = o.GameServerID()
	}
	if o.Read != nil {
		m.Read = o.Read()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	return m
}

// toModels returns an models.NotificationSlice
// this does nothing with the relationship templates
func (o NotificationTemplate) toModels(number int) models.NotificationSlice {
	m := make(models.NotificationSlice, number)

	for i := range m {
		m[i] = o.toModel()
	}

	return m
}

// setModelRels creates and sets the relationships on *models.Notification
// according to the relationships in the template. Nothing is inserted into the db
func (t NotificationTemplate) setModelRels(o *models.Notification) {}

// BuildSetter returns an *models.NotificationSetter
// this does nothing with the relationship templates
func (o NotificationTemplate) BuildSetter() *models.NotificationSetter {
	m := &models.NotificationSetter{}

	if o.ID != nil {
		m.ID = omit.From(o.ID())
	}
	if o.Event != nil {
		m.Event = omit.From(o.Event())
	}
	if o.Error != nil {
		m.Error = omit.From(o.Error())
	}
	if o.Message != nil {
		m.Message = omit.From(o.Message())
	}
	if o.GameID != nil {
		m.GameID = omit.From(o.GameID())
	}
	if o.GameServerID != nil {
		m.GameServerID = omit.From(o.GameServerID())
	}
	if o.Read != nil {
		m.Read = omit.From(o.Read())
	}
	if o.CreatedAt != nil {
		m.CreatedAt = omit.From(o.CreatedAt())
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = omit.From(o.UpdatedAt())
	}

	return m
}

// BuildManySetter returns an []*models.NotificationSetter
// this does nothing with the relationship templates
func (o NotificationTemplate) BuildManySetter(number int) []*models.NotificationSetter {
	m := make([]*models.NotificationSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Notification
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use NotificationTemplate.Create
func (o NotificationTemplate) Build() *models.Notification {
	m := o.toModel()
	o.setModelRels(m)

	return m
}

// BuildMany returns an models.NotificationSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use NotificationTemplate.CreateMany
func (o NotificationTemplate) BuildMany(number int) models.NotificationSlice {
	m := make(models.NotificationSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableNotification(m *models.NotificationSetter) {
	if m.ID.IsUnset() {
		m.ID = omit.From(random[string](nil))
	}
	if m.Event.IsUnset() {
		m.Event = omit.From(random[string](nil))
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Notification
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *NotificationTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Notification) (context.Context, error) {
	var err error

	return ctx, err
}

// Create builds a notification and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *NotificationTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Notification, error) {
	_, m, err := o.create(ctx, exec)
	return m, err
}

// create builds a notification and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted model
func (o *NotificationTemplate) create(ctx context.Context, exec bob.Executor) (context.Context, *models.Notification, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableNotification(opt)

	m, err := models.Notifications.Insert(ctx, exec, opt)
	if err != nil {
		return ctx, nil, err
	}
	ctx = notificationCtx.WithValue(ctx, m)

	ctx, err = o.insertOptRels(ctx, exec, m)
	return ctx, m, err
}

// CreateMany builds multiple notifications and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o NotificationTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.NotificationSlice, error) {
	_, m, err := o.createMany(ctx, exec, number)
	return m, err
}

// createMany builds multiple notifications and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted models
func (o NotificationTemplate) createMany(ctx context.Context, exec bob.Executor, number int) (context.Context, models.NotificationSlice, error) {
	var err error
	m := make(models.NotificationSlice, number)

	for i := range m {
		ctx, m[i], err = o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}

	return ctx, m, nil
}

// Notification has methods that act as mods for the NotificationTemplate
var NotificationMods notificationMods

type notificationMods struct{}

func (m notificationMods) RandomizeAllColumns(f *faker.Faker) NotificationMod {
	return NotificationModSlice{
		NotificationMods.RandomID(f),
		NotificationMods.RandomEvent(f),
		NotificationMods.RandomError(f),
		NotificationMods.RandomMessage(f),
		NotificationMods.RandomGameID(f),
		NotificationMods.RandomGameServerID(f),
		NotificationMods.RandomRead(f),
		NotificationMods.RandomCreatedAt(f),
		NotificationMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m notificationMods) ID(val string) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m notificationMods) IDFunc(f func() string) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m notificationMods) UnsetID() NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m notificationMods) RandomID(f *faker.Faker) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.ID = func() string {
			return random[string](f)
		}
	})
}

func (m notificationMods) ensureID(f *faker.Faker) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		if o.ID != nil {
			return
		}

		o.ID = func() string {
			return random[string](f)
		}
	})
}

// Set the model columns to this value
func (m notificationMods) Event(val string) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.Event = func() string { return val }
	})
}

// Set the Column from the function
func (m notificationMods) EventFunc(f func() string) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.Event = f
	})
}

// Clear any values for the column
func (m notificationMods) UnsetEvent() NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.Event = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m notificationMods) RandomEvent(f *faker.Faker) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.Event = func() string {
			return random[string](f)
		}
	})
}

func (m notificationMods) ensureEvent(f *faker.Faker) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		if o.Event != nil {
			return
		}

		o.Event = func() string {
			return random[string](f)
		}
	})
}

// Set the model columns to this value
func (m notificationMods) Error(val string) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.Error = func() string { return val }
	})
}

// Set the Column from the function
func (m notificationMods) ErrorFunc(f func() string) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.Error = f
	})
}

// Clear any values for the column
func (m notificationMods) UnsetError() NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.Error = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m notificationMods) RandomError(f *faker.Faker) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.Error = func() string {
			return random[string](f)
		}
	})
}

func (m notificationMods) ensureError(f *faker.Faker) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		if o.Error != nil {
			return
		}

		o.Error = func() string {
			return random[string](f)
		}
	})
}

// Set the model columns to this value
func (m notificationMods) Message(val string) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.Message = func() string { return val }
	})
}

// Set the Column from the function
func (m notificationMods) MessageFunc(f func() string) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.Message = f
	})
}

// Clear any values for the column
func (m notificationMods) UnsetMessage() NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.Message = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m notificationMods) RandomMessage(f *faker.Faker) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.Message = func() string {
			return random[string](f)
		}
	})
}

func (m notificationMods) ensureMessage(f *faker.Faker) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		if o.Message != nil {
			return
		}

		o.Message = func() string {
			return random[string](f)
		}
	})
}

// Set the model columns to this value
func (m notificationMods) GameID(val string) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.GameID = func() string { return val }
	})
}

// Set the Column from the function
func (m notificationMods) GameIDFunc(f func() string) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.GameID = f
	})
}

// Clear any values for the column
func (m notificationMods) UnsetGameID() NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.GameID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m notificationMods) RandomGameID(f *faker.Faker) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.GameID = func() string {
			return random[string](f)
		}
	})
}

func (m notificationMods) ensureGameID(f *faker.Faker) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		if o.GameID != nil {
			return
		}

		o.GameID = func() string {
			return random[string](f)
		}
	})
}

// Set the model columns to this value
func (m notificationMods) GameServerID(val string) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.GameServerID = func() string { return val }
	})
}

// Set the Column from the function
func (m notificationMods) GameServerIDFunc(f func() string) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.GameServerID = f
	})
}

// Clear any values for the column
func (m notificationMods) UnsetGameServerID() NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.GameServerID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m notificationMods) RandomGameServerID(f *faker.Faker) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.GameServerID = func() string {
			return random[string](f)
		}
	})
}

func (m notificationMods) ensureGameServerID(f *faker.Faker) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		if o.GameServerID != nil {
			return
		}

		o.GameServerID = func() string {
			return random[string](f)
		}
	})
}

// Set the model columns to this value
func (m notificationMods) Read(val bool) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.Read = func() bool { return val }
	})
}

// Set the Column from the function
func (m notificationMods) ReadFunc(f func() bool) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.Read = f
	})
}

// Clear any values for the column
func (m notificationMods) UnsetRead() NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.Read = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m notificationMods) RandomRead(f *faker.Faker) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.Read = func() bool {
			return random[bool](f)
		}
	})
}

func (m notificationMods) ensureRead(f *faker.Faker) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		if o.Read != nil {
			return
		}

		o.Read = func() bool {
			return random[bool](f)
		}
	})
}

// Set the model columns to this value
func (m notificationMods) CreatedAt(val time.Time) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m notificationMods) CreatedAtFunc(f func() time.Time) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m notificationMods) UnsetCreatedAt() NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m notificationMods) RandomCreatedAt(f *faker.Faker) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.CreatedAt = func() time.Time {
			return random[time.Time](f)
		}
	})
}

func (m notificationMods) ensureCreatedAt(f *faker.Faker) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		if o.CreatedAt != nil {
			return
		}

		o.CreatedAt = func() time.Time {
			return random[time.Time](f)
		}
	})
}

// Set the model columns to this value
func (m notificationMods) UpdatedAt(val time.Time) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m notificationMods) UpdatedAtFunc(f func() time.Time) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m notificationMods) UnsetUpdatedAt() NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m notificationMods) RandomUpdatedAt(f *faker.Faker) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		o.UpdatedAt = func() time.Time {
			return random[time.Time](f)
		}
	})
}

func (m notificationMods) ensureUpdatedAt(f *faker.Faker) NotificationMod {
	return NotificationModFunc(func(o *NotificationTemplate) {
		if o.UpdatedAt != nil {
			return
		}

		o.UpdatedAt = func() time.Time {
			return random[time.Time](f)
		}
	})
}
