// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "github.com/stephenafamo/bob"

// Set the testDB to enable tests that use the database
var testDB bob.Transactor[bob.Tx]

// Make sure the type AlertHistory runs hooks after queries
var _ bob.HookableType = &AlertHistory{}

// Make sure the type AlertRule runs hooks after queries
var _ bob.HookableType = &AlertRule{}

// Make sure the type AlertState runs hooks after queries
var _ bob.HookableType = &AlertState{}

// Make sure the type FederatedAccessGrant runs hooks after queries
var _ bob.HookableType = &FederatedAccessGrant{}

// Make sure the type FederationAdvisory runs hooks after queries
var _ bob.HookableType = &FederationAdvisory{}

// Make sure the type FederationLocalIdentity runs hooks after queries
var _ bob.HookableType = &FederationLocalIdentity{}

// Make sure the type FederationPairingToken runs hooks after queries
var _ bob.HookableType = &FederationPairingToken{}

// Make sure the type FederationTrustedPeer runs hooks after queries
var _ bob.HookableType = &FederationTrustedPeer{}

// Make sure the type Game runs hooks after queries
var _ bob.HookableType = &Game{}

// Make sure the type GameServer runs hooks after queries
var _ bob.HookableType = &GameServer{}

// Make sure the type GameServerBackup runs hooks after queries
var _ bob.HookableType = &GameServerBackup{}

// Make sure the type GameServerMetricsHistory runs hooks after queries
var _ bob.HookableType = &GameServerMetricsHistory{}

// Make sure the type InstalledMod runs hooks after queries
var _ bob.HookableType = &InstalledMod{}

// Make sure the type InstalledModFile runs hooks after queries
var _ bob.HookableType = &InstalledModFile{}

// Make sure the type IP runs hooks after queries
var _ bob.HookableType = &IP{}

// Make sure the type LocalSecretKey runs hooks after queries
var _ bob.HookableType = &LocalSecretKey{}

// Make sure the type LocalSetting runs hooks after queries
var _ bob.HookableType = &LocalSetting{}

// Make sure the type Log runs hooks after queries
var _ bob.HookableType = &Log{}

// Make sure the type Migration runs hooks after queries
var _ bob.HookableType = &Migration{}

// Make sure the type Node runs hooks after queries
var _ bob.HookableType = &Node{}

// Make sure the type NodeAPIKey runs hooks after queries
var _ bob.HookableType = &NodeAPIKey{}

// Make sure the type NodeMetricsHistory runs hooks after queries
var _ bob.HookableType = &NodeMetricsHistory{}

// Make sure the type NodeSyncQueue runs hooks after queries
var _ bob.HookableType = &NodeSyncQueue{}

// Make sure the type Notification runs hooks after queries
var _ bob.HookableType = &Notification{}

// Make sure the type NotificationChannel runs hooks after queries
var _ bob.HookableType = &NotificationChannel{}

// Make sure the type PeerSyncState runs hooks after queries
var _ bob.HookableType = &PeerSyncState{}

// Make sure the type Permission runs hooks after queries
var _ bob.HookableType = &Permission{}

// Make sure the type RemoteServerCache runs hooks after queries
var _ bob.HookableType = &RemoteServerCache{}

// Make sure the type RevokedJWT runs hooks after queries
var _ bob.HookableType = &RevokedJWT{}

// Make sure the type Role runs hooks after queries
var _ bob.HookableType = &Role{}

// Make sure the type RolePermission runs hooks after queries
var _ bob.HookableType = &RolePermission{}

// Make sure the type ScheduledTask runs hooks after queries
var _ bob.HookableType = &ScheduledTask{}

// Make sure the type ScheduledTaskLog runs hooks after queries
var _ bob.HookableType = &ScheduledTaskLog{}

// Make sure the type SystemConfig runs hooks after queries
var _ bob.HookableType = &SystemConfig{}

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &User{}

// Make sure the type UserAPIKey runs hooks after queries
var _ bob.HookableType = &UserAPIKey{}

// Make sure the type UserRoleAssignment runs hooks after queries
var _ bob.HookableType = &UserRoleAssignment{}

// Make sure the type UserSession runs hooks after queries
var _ bob.HookableType = &UserSession{}
