// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
)

var (
	SelectWhere     = Where[*dialect.SelectQuery]()
	UpdateWhere     = Where[*dialect.UpdateQuery]()
	DeleteWhere     = Where[*dialect.DeleteQuery]()
	OnConflictWhere = Where[*clause.ConflictClause]() // Used in ON CONFLICT DO UPDATE
)

func Where[Q sqlite.Filterable]() struct {
	AlertHistories             alertHistoryWhere[Q]
	AlertRules                 alertRuleWhere[Q]
	AlertStates                alertStateWhere[Q]
	FederatedAccessGrants      federatedAccessGrantWhere[Q]
	FederationAdvisories       federationAdvisoryWhere[Q]
	FederationLocalIdentities  federationLocalIdentityWhere[Q]
	FederationPairingTokens    federationPairingTokenWhere[Q]
	FederationTrustedPeers     federationTrustedPeerWhere[Q]
	Games                      gameWhere[Q]
	GameServers                gameServerWhere[Q]
	GameServerMetricsHistories gameServerMetricsHistoryWhere[Q]
	InstalledMods              installedModWhere[Q]
	InstalledModFiles          installedModFileWhere[Q]
	Ips                        ipWhere[Q]
	LocalSecretKeys            localSecretKeyWhere[Q]
	LocalSettings              localSettingWhere[Q]
	Logs                       logWhere[Q]
	Migrations                 migrationWhere[Q]
	Nodes                      nodeWhere[Q]
	NodeAPIKeys                nodeAPIKeyWhere[Q]
	NodeMetricsHistories       nodeMetricsHistoryWhere[Q]
	NodeSyncQueues             nodeSyncQueueWhere[Q]
	Notifications              notificationWhere[Q]
	NotificationChannels       notificationChannelWhere[Q]
	PeerSyncStates             peerSyncStateWhere[Q]
	Permissions                permissionWhere[Q]
	RemoteServerCaches         remoteServerCacheWhere[Q]
	RevokedJWTS                revokedJWTWhere[Q]
	Roles                      roleWhere[Q]
	RolePermissions            rolePermissionWhere[Q]
	SystemConfigs              systemConfigWhere[Q]
	Users                      userWhere[Q]
	UserAPIKeys                userAPIKeyWhere[Q]
	UserRoleAssignments        userRoleAssignmentWhere[Q]
	UserSessions               userSessionWhere[Q]
} {
	return struct {
		AlertHistories             alertHistoryWhere[Q]
		AlertRules                 alertRuleWhere[Q]
		AlertStates                alertStateWhere[Q]
		FederatedAccessGrants      federatedAccessGrantWhere[Q]
		FederationAdvisories       federationAdvisoryWhere[Q]
		FederationLocalIdentities  federationLocalIdentityWhere[Q]
		FederationPairingTokens    federationPairingTokenWhere[Q]
		FederationTrustedPeers     federationTrustedPeerWhere[Q]
		Games                      gameWhere[Q]
		GameServers                gameServerWhere[Q]
		GameServerMetricsHistories gameServerMetricsHistoryWhere[Q]
		InstalledMods              installedModWhere[Q]
		InstalledModFiles          installedModFileWhere[Q]
		Ips                        ipWhere[Q]
		LocalSecretKeys            localSecretKeyWhere[Q]
		LocalSettings              localSettingWhere[Q]
		Logs                       logWhere[Q]
		Migrations                 migrationWhere[Q]
		Nodes                      nodeWhere[Q]
		NodeAPIKeys                nodeAPIKeyWhere[Q]
		NodeMetricsHistories       nodeMetricsHistoryWhere[Q]
		NodeSyncQueues             nodeSyncQueueWhere[Q]
		Notifications              notificationWhere[Q]
		NotificationChannels       notificationChannelWhere[Q]
		PeerSyncStates             peerSyncStateWhere[Q]
		Permissions                permissionWhere[Q]
		RemoteServerCaches         remoteServerCacheWhere[Q]
		RevokedJWTS                revokedJWTWhere[Q]
		Roles                      roleWhere[Q]
		RolePermissions            rolePermissionWhere[Q]
		SystemConfigs              systemConfigWhere[Q]
		Users                      userWhere[Q]
		UserAPIKeys                userAPIKeyWhere[Q]
		UserRoleAssignments        userRoleAssignmentWhere[Q]
		UserSessions               userSessionWhere[Q]
	}{
		AlertHistories:             buildAlertHistoryWhere[Q](AlertHistories.Columns),
		AlertRules:                 buildAlertRuleWhere[Q](AlertRules.Columns),
		AlertStates:                buildAlertStateWhere[Q](AlertStates.Columns),
		FederatedAccessGrants:      buildFederatedAccessGrantWhere[Q](FederatedAccessGrants.Columns),
		FederationAdvisories:       buildFederationAdvisoryWhere[Q](FederationAdvisories.Columns),
		FederationLocalIdentities:  buildFederationLocalIdentityWhere[Q](FederationLocalIdentities.Columns),
		FederationPairingTokens:    buildFederationPairingTokenWhere[Q](FederationPairingTokens.Columns),
		FederationTrustedPeers:     buildFederationTrustedPeerWhere[Q](FederationTrustedPeers.Columns),
		Games:                      buildGameWhere[Q](Games.Columns),
		GameServers:                buildGameServerWhere[Q](GameServers.Columns),
		GameServerMetricsHistories: buildGameServerMetricsHistoryWhere[Q](GameServerMetricsHistories.Columns),
		InstalledMods:              buildInstalledModWhere[Q](InstalledMods.Columns),
		InstalledModFiles:          buildInstalledModFileWhere[Q](InstalledModFiles.Columns),
		Ips:                        buildIPWhere[Q](Ips.Columns),
		LocalSecretKeys:            buildLocalSecretKeyWhere[Q](LocalSecretKeys.Columns),
		LocalSettings:              buildLocalSettingWhere[Q](LocalSettings.Columns),
		Logs:                       buildLogWhere[Q](Logs.Columns),
		Migrations:                 buildMigrationWhere[Q](Migrations.Columns),
		Nodes:                      buildNodeWhere[Q](Nodes.Columns),
		NodeAPIKeys:                buildNodeAPIKeyWhere[Q](NodeAPIKeys.Columns),
		NodeMetricsHistories:       buildNodeMetricsHistoryWhere[Q](NodeMetricsHistories.Columns),
		NodeSyncQueues:             buildNodeSyncQueueWhere[Q](NodeSyncQueues.Columns),
		Notifications:              buildNotificationWhere[Q](Notifications.Columns),
		NotificationChannels:       buildNotificationChannelWhere[Q](NotificationChannels.Columns),
		PeerSyncStates:             buildPeerSyncStateWhere[Q](PeerSyncStates.Columns),
		Permissions:                buildPermissionWhere[Q](Permissions.Columns),
		RemoteServerCaches:         buildRemoteServerCacheWhere[Q](RemoteServerCaches.Columns),
		RevokedJWTS:                buildRevokedJWTWhere[Q](RevokedJWTS.Columns),
		Roles:                      buildRoleWhere[Q](Roles.Columns),
		RolePermissions:            buildRolePermissionWhere[Q](RolePermissions.Columns),
		SystemConfigs:              buildSystemConfigWhere[Q](SystemConfigs.Columns),
		Users:                      buildUserWhere[Q](Users.Columns),
		UserAPIKeys:                buildUserAPIKeyWhere[Q](UserAPIKeys.Columns),
		UserRoleAssignments:        buildUserRoleAssignmentWhere[Q](UserRoleAssignments.Columns),
		UserSessions:               buildUserSessionWhere[Q](UserSessions.Columns),
	}
}
