// Code generated by BobGen sqlite v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/scan"
)

// Game is an object representing the database table.
type Game struct {
	ID                                string           `db:"id,pk" `
	Name                              string           `db:"name" `
	DefaultPort                       int64            `db:"default_port" `
	DefaultQueryPort                  int64            `db:"default_query_port" `
	DefaultMaxPlayers                 int64            `db:"default_max_players" `
	RequireDedicatedIP                bool             `db:"require_dedicated_ip" `
	UsesSourceQuery                   bool             `db:"uses_source_query" `
	UsesSteamcmd                      bool             `db:"uses_steamcmd" `
	SteamAppID                        string           `db:"steam_app_id" `
	RequiresSteamGameServerLoginToken bool             `db:"requires_steam_game_server_login_token" `
	LinuxSupport                      bool             `db:"linux_support" `
	LinuxStopCommand                  string           `db:"linux_stop_command" `
	LinuxInstallCommand               string           `db:"linux_install_command" `
	LinuxInstallCommandType           string           `db:"linux_install_command_type" `
	LinuxUpdateCommand                string           `db:"linux_update_command" `
	LinuxUpdateCommandType            string           `db:"linux_update_command_type" `
	LinuxWorkingDirectory             string           `db:"linux_working_directory" `
	WindowsSupport                    bool             `db:"windows_support" `
	WindowsStopCommand                string           `db:"windows_stop_command" `
	WindowsInstallCommand             string           `db:"windows_install_command" `
	WindowsInstallCommandType         string           `db:"windows_install_command_type" `
	WindowsUpdateCommand              string           `db:"windows_update_command" `
	WindowsUpdateCommandType          string           `db:"windows_update_command_type" `
	WindowsWorkingDirectory           string           `db:"windows_working_directory" `
	BindsToAllIps                     bool             `db:"binds_to_all_ips" `
	CreatedAt                         time.Time        `db:"created_at" `
	UpdatedAt                         time.Time        `db:"updated_at" `
	XylonaOfficial                    bool             `db:"xylona_official" `
	ConfigSchemas                     null.Val[string] `db:"config_schemas" `
	ServerSoftware                    null.Val[string] `db:"server_software" `
	LinuxStartArgsTemplate            null.Val[string] `db:"linux_start_args_template" `
	WindowsStartArgsTemplate          null.Val[string] `db:"windows_start_args_template" `
	LinuxBaseCommand                  string           `db:"linux_base_command" `
	WindowsBaseCommand                string           `db:"windows_base_command" `
	StartArgBlocklist                 string           `db:"start_arg_blocklist" `
	AllowStartArgEditing              bool             `db:"allow_start_arg_editing" `
	OfficialDefinitionHash            string           `db:"official_definition_hash" `
	OfficialDefinitionSource          string           `db:"official_definition_source" `
	OfficialDefinitionSchemaVersion   int64            `db:"official_definition_schema_version" `
	OfficialDefinitionDiverged        bool             `db:"official_definition_diverged" `
	DefaultEnvVars                    string           `db:"default_env_vars" `
	LinuxAllowBackups                 bool             `db:"linux_allow_backups" `
	WindowsAllowBackups               bool             `db:"windows_allow_backups" `
	ConsoleCommands                   string           `db:"console_commands" `

	R gameR `db:"-" `

	C gameC `db:"-" `
}

// GameSlice is an alias for a slice of pointers to Game.
// This should almost always be used instead of []*Game.
type GameSlice []*Game

// Games contains methods to work with the game table
var Games = sqlite.NewTablex[*Game, GameSlice, *GameSetter]("", "game", buildGameColumns("game"), gameScanMapper)

// GamesQuery is a query on the game table
type GamesQuery = *sqlite.ViewQuery[*Game, GameSlice]

// gameR is where relationships are stored.
type gameR struct {
	GameServers GameServerSlice // fk_game_server_2
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded gameRLoaded `db:"-" `
}

// gameRLoaded tracks which relationships on Game have been loaded.
type gameRLoaded struct {
	GameServers bool // fk_game_server_2
}

func buildGameColumns(tableName string) gameColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "name", "default_port", "default_query_port", "default_max_players", "require_dedicated_ip", "uses_source_query", "uses_steamcmd", "steam_app_id", "requires_steam_game_server_login_token", "linux_support", "linux_stop_command", "linux_install_command", "linux_install_command_type", "linux_update_command", "linux_update_command_type", "linux_working_directory", "windows_support", "windows_stop_command", "windows_install_command", "windows_install_command_type", "windows_update_command", "windows_update_command_type", "windows_working_directory", "binds_to_all_ips", "created_at", "updated_at", "xylona_official", "config_schemas", "server_software", "linux_start_args_template", "windows_start_args_template", "linux_base_command", "windows_base_command", "start_arg_blocklist", "allow_start_arg_editing", "official_definition_hash", "official_definition_source", "official_definition_schema_version", "official_definition_diverged", "default_env_vars", "linux_allow_backups", "windows_allow_backups", "console_commands",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return gameColumns{
		ColumnsExpr:                       columnsExpr,
		tableAlias:                        tableName,
		ID:                                buildGameColumn(tableName, "id"),
		Name:                              buildGameColumn(tableName, "name"),
		DefaultPort:                       buildGameColumn(tableName, "default_port"),
		DefaultQueryPort:                  buildGameColumn(tableName, "default_query_port"),
		DefaultMaxPlayers:                 buildGameColumn(tableName, "default_max_players"),
		RequireDedicatedIP:                buildGameColumn(tableName, "require_dedicated_ip"),
		UsesSourceQuery:                   buildGameColumn(tableName, "uses_source_query"),
		UsesSteamcmd:                      buildGameColumn(tableName, "uses_steamcmd"),
		SteamAppID:                        buildGameColumn(tableName, "steam_app_id"),
		RequiresSteamGameServerLoginToken: buildGameColumn(tableName, "requires_steam_game_server_login_token"),
		LinuxSupport:                      buildGameColumn(tableName, "linux_support"),
		LinuxStopCommand:                  buildGameColumn(tableName, "linux_stop_command"),
		LinuxInstallCommand:               buildGameColumn(tableName, "linux_install_command"),
		LinuxInstallCommandType:           buildGameColumn(tableName, "linux_install_command_type"),
		LinuxUpdateCommand:                buildGameColumn(tableName, "linux_update_command"),
		LinuxUpdateCommandType:            buildGameColumn(tableName, "linux_update_command_type"),
		LinuxWorkingDirectory:             buildGameColumn(tableName, "linux_working_directory"),
		WindowsSupport:                    buildGameColumn(tableName, "windows_support"),
		WindowsStopCommand:                buildGameColumn(tableName, "windows_stop_command"),
		WindowsInstallCommand:             buildGameColumn(tableName, "windows_install_command"),
		WindowsInstallCommandType:         buildGameColumn(tableName, "windows_install_command_type"),
		WindowsUpdateCommand:              buildGameColumn(tableName, "windows_update_command"),
		WindowsUpdateCommandType:          buildGameColumn(tableName, "windows_update_command_type"),
		WindowsWorkingDirectory:           buildGameColumn(tableName, "windows_working_directory"),
		BindsToAllIps:                     buildGameColumn(tableName, "binds_to_all_ips"),
		CreatedAt:                         buildGameColumn(tableName, "created_at"),
		UpdatedAt:                         buildGameColumn(tableName, "updated_at"),
		XylonaOfficial:                    buildGameColumn(tableName, "xylona_official"),
		ConfigSchemas:                     buildGameColumn(tableName, "config_schemas"),
		ServerSoftware:                    buildGameColumn(tableName, "server_software"),
		LinuxStartArgsTemplate:            buildGameColumn(tableName, "linux_start_args_template"),
		WindowsStartArgsTemplate:          buildGameColumn(tableName, "windows_start_args_template"),
		LinuxBaseCommand:                  buildGameColumn(tableName, "linux_base_command"),
		WindowsBaseCommand:                buildGameColumn(tableName, "windows_base_command"),
		StartArgBlocklist:                 buildGameColumn(tableName, "start_arg_blocklist"),
		AllowStartArgEditing:              buildGameColumn(tableName, "allow_start_arg_editing"),
		OfficialDefinitionHash:            buildGameColumn(tableName, "official_definition_hash"),
		OfficialDefinitionSource:          buildGameColumn(tableName, "official_definition_source"),
		OfficialDefinitionSchemaVersion:   buildGameColumn(tableName, "official_definition_schema_version"),
		OfficialDefinitionDiverged:        buildGameColumn(tableName, "official_definition_diverged"),
		DefaultEnvVars:                    buildGameColumn(tableName, "default_env_vars"),
		LinuxAllowBackups:                 buildGameColumn(tableName, "linux_allow_backups"),
		WindowsAllowBackups:               buildGameColumn(tableName, "windows_allow_backups"),
		ConsoleCommands:                   buildGameColumn(tableName, "console_commands"),
	}
}

type gameColumns struct {
	expr.ColumnsExpr
	tableAlias                        string
	ID                                gameColumn
	Name                              gameColumn
	DefaultPort                       gameColumn
	DefaultQueryPort                  gameColumn
	DefaultMaxPlayers                 gameColumn
	RequireDedicatedIP                gameColumn
	UsesSourceQuery                   gameColumn
	UsesSteamcmd                      gameColumn
	SteamAppID                        gameColumn
	RequiresSteamGameServerLoginToken gameColumn
	LinuxSupport                      gameColumn
	LinuxStopCommand                  gameColumn
	LinuxInstallCommand               gameColumn
	LinuxInstallCommandType           gameColumn
	LinuxUpdateCommand                gameColumn
	LinuxUpdateCommandType            gameColumn
	LinuxWorkingDirectory             gameColumn
	WindowsSupport                    gameColumn
	WindowsStopCommand                gameColumn
	WindowsInstallCommand             gameColumn
	WindowsInstallCommandType         gameColumn
	WindowsUpdateCommand              gameColumn
	WindowsUpdateCommandType          gameColumn
	WindowsWorkingDirectory           gameColumn
	BindsToAllIps                     gameColumn
	CreatedAt                         gameColumn
	UpdatedAt                         gameColumn
	XylonaOfficial                    gameColumn
	ConfigSchemas                     gameColumn
	ServerSoftware                    gameColumn
	LinuxStartArgsTemplate            gameColumn
	WindowsStartArgsTemplate          gameColumn
	LinuxBaseCommand                  gameColumn
	WindowsBaseCommand                gameColumn
	StartArgBlocklist                 gameColumn
	AllowStartArgEditing              gameColumn
	OfficialDefinitionHash            gameColumn
	OfficialDefinitionSource          gameColumn
	OfficialDefinitionSchemaVersion   gameColumn
	OfficialDefinitionDiverged        gameColumn
	DefaultEnvVars                    gameColumn
	LinuxAllowBackups                 gameColumn
	WindowsAllowBackups               gameColumn
	ConsoleCommands                   gameColumn
}

// Alias returns the current table alias for the columns set.
func (c gameColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (gameColumns) AliasedAs(tableName string) gameColumns {
	return buildGameColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c gameColumns) Unqualified() gameColumns {
	return buildGameColumns("")
}

func buildGameColumn(alias, name string) gameColumn {
	return gameColumn{
		Expression: sqlite.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type gameColumn struct {
	sqlite.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c gameColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c gameColumn) ShouldOmitParens() bool {
	return true
}

// GameSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type GameSetter struct {
	ID                                omit.Val[string]     `db:"id,pk" `
	Name                              omit.Val[string]     `db:"name" `
	DefaultPort                       omit.Val[int64]      `db:"default_port" `
	DefaultQueryPort                  omit.Val[int64]      `db:"default_query_port" `
	DefaultMaxPlayers                 omit.Val[int64]      `db:"default_max_players" `
	RequireDedicatedIP                omit.Val[bool]       `db:"require_dedicated_ip" `
	UsesSourceQuery                   omit.Val[bool]       `db:"uses_source_query" `
	UsesSteamcmd                      omit.Val[bool]       `db:"uses_steamcmd" `
	SteamAppID                        omit.Val[string]     `db:"steam_app_id" `
	RequiresSteamGameServerLoginToken omit.Val[bool]       `db:"requires_steam_game_server_login_token" `
	LinuxSupport                      omit.Val[bool]       `db:"linux_support" `
	LinuxStopCommand                  omit.Val[string]     `db:"linux_stop_command" `
	LinuxInstallCommand               omit.Val[string]     `db:"linux_install_command" `
	LinuxInstallCommandType           omit.Val[string]     `db:"linux_install_command_type" `
	LinuxUpdateCommand                omit.Val[string]     `db:"linux_update_command" `
	LinuxUpdateCommandType            omit.Val[string]     `db:"linux_update_command_type" `
	LinuxWorkingDirectory             omit.Val[string]     `db:"linux_working_directory" `
	WindowsSupport                    omit.Val[bool]       `db:"windows_support" `
	WindowsStopCommand                omit.Val[string]     `db:"windows_stop_command" `
	WindowsInstallCommand             omit.Val[string]     `db:"windows_install_command" `
	WindowsInstallCommandType         omit.Val[string]     `db:"windows_install_command_type" `
	WindowsUpdateCommand              omit.Val[string]     `db:"windows_update_command" `
	WindowsUpdateCommandType          omit.Val[string]     `db:"windows_update_command_type" `
	WindowsWorkingDirectory           omit.Val[string]     `db:"windows_working_directory" `
	BindsToAllIps                     omit.Val[bool]       `db:"binds_to_all_ips" `
	CreatedAt                         omit.Val[time.Time]  `db:"created_at" `
	UpdatedAt                         omit.Val[time.Time]  `db:"updated_at" `
	XylonaOfficial                    omit.Val[bool]       `db:"xylona_official" `
	ConfigSchemas                     omitnull.Val[string] `db:"config_schemas" `
	ServerSoftware                    omitnull.Val[string] `db:"server_software" `
	LinuxStartArgsTemplate            omitnull.Val[string] `db:"linux_start_args_template" `
	WindowsStartArgsTemplate          omitnull.Val[string] `db:"windows_start_args_template" `
	LinuxBaseCommand                  omit.Val[string]     `db:"linux_base_command" `
	WindowsBaseCommand                omit.Val[string]     `db:"windows_base_command" `
	StartArgBlocklist                 omit.Val[string]     `db:"start_arg_blocklist" `
	AllowStartArgEditing              omit.Val[bool]       `db:"allow_start_arg_editing" `
	OfficialDefinitionHash            omit.Val[string]     `db:"official_definition_hash" `
	OfficialDefinitionSource          omit.Val[string]     `db:"official_definition_source" `
	OfficialDefinitionSchemaVersion   omit.Val[int64]      `db:"official_definition_schema_version" `
	OfficialDefinitionDiverged        omit.Val[bool]       `db:"official_definition_diverged" `
	DefaultEnvVars                    omit.Val[string]     `db:"default_env_vars" `
	LinuxAllowBackups                 omit.Val[bool]       `db:"linux_allow_backups" `
	WindowsAllowBackups               omit.Val[bool]       `db:"windows_allow_backups" `
	ConsoleCommands                   omit.Val[string]     `db:"console_commands" `
}

func (s GameSetter) SetColumns() []string {
	vals := make([]string, 0, 44)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.DefaultPort.IsValue() {
		vals = append(vals, "default_port")
	}
	if s.DefaultQueryPort.IsValue() {
		vals = append(vals, "default_query_port")
	}
	if s.DefaultMaxPlayers.IsValue() {
		vals = append(vals, "default_max_players")
	}
	if s.RequireDedicatedIP.IsValue() {
		vals = append(vals, "require_dedicated_ip")
	}
	if s.UsesSourceQuery.IsValue() {
		vals = append(vals, "uses_source_query")
	}
	if s.UsesSteamcmd.IsValue() {
		vals = append(vals, "uses_steamcmd")
	}
	if s.SteamAppID.IsValue() {
		vals = append(vals, "steam_app_id")
	}
	if s.RequiresSteamGameServerLoginToken.IsValue() {
		vals = append(vals, "requires_steam_game_server_login_token")
	}
	if s.LinuxSupport.IsValue() {
		vals = append(vals, "linux_support")
	}
	if s.LinuxStopCommand.IsValue() {
		vals = append(vals, "linux_stop_command")
	}
	if s.LinuxInstallCommand.IsValue() {
		vals = append(vals, "linux_install_command")
	}
	if s.LinuxInstallCommandType.IsValue() {
		vals = append(vals, "linux_install_command_type")
	}
	if s.LinuxUpdateCommand.IsValue() {
		vals = append(vals, "linux_update_command")
	}
	if s.LinuxUpdateCommandType.IsValue() {
		vals = append(vals, "linux_update_command_type")
	}
	if s.LinuxWorkingDirectory.IsValue() {
		vals = append(vals, "linux_working_directory")
	}
	if s.WindowsSupport.IsValue() {
		vals = append(vals, "windows_support")
	}
	if s.WindowsStopCommand.IsValue() {
		vals = append(vals, "windows_stop_command")
	}
	if s.WindowsInstallCommand.IsValue() {
		vals = append(vals, "windows_install_command")
	}
	if s.WindowsInstallCommandType.IsValue() {
		vals = append(vals, "windows_install_command_type")
	}
	if s.WindowsUpdateCommand.IsValue() {
		vals = append(vals, "windows_update_command")
	}
	if s.WindowsUpdateCommandType.IsValue() {
		vals = append(vals, "windows_update_command_type")
	}
	if s.WindowsWorkingDirectory.IsValue() {
		vals = append(vals, "windows_working_directory")
	}
	if s.BindsToAllIps.IsValue() {
		vals = append(vals, "binds_to_all_ips")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	if s.XylonaOfficial.IsValue() {
		vals = append(vals, "xylona_official")
	}
	if s.ConfigSchemas.IsValue() || s.ConfigSchemas.IsNull() {
		vals = append(vals, "config_schemas")
	}
	if s.ServerSoftware.IsValue() || s.ServerSoftware.IsNull() {
		vals = append(vals, "server_software")
	}
	if s.LinuxStartArgsTemplate.IsValue() || s.LinuxStartArgsTemplate.IsNull() {
		vals = append(vals, "linux_start_args_template")
	}
	if s.WindowsStartArgsTemplate.IsValue() || s.WindowsStartArgsTemplate.IsNull() {
		vals = append(vals, "windows_start_args_template")
	}
	if s.LinuxBaseCommand.IsValue() {
		vals = append(vals, "linux_base_command")
	}
	if s.WindowsBaseCommand.IsValue() {
		vals = append(vals, "windows_base_command")
	}
	if s.StartArgBlocklist.IsValue() {
		vals = append(vals, "start_arg_blocklist")
	}
	if s.AllowStartArgEditing.IsValue() {
		vals = append(vals, "allow_start_arg_editing")
	}
	if s.OfficialDefinitionHash.IsValue() {
		vals = append(vals, "official_definition_hash")
	}
	if s.OfficialDefinitionSource.IsValue() {
		vals = append(vals, "official_definition_source")
	}
	if s.OfficialDefinitionSchemaVersion.IsValue() {
		vals = append(vals, "official_definition_schema_version")
	}
	if s.OfficialDefinitionDiverged.IsValue() {
		vals = append(vals, "official_definition_diverged")
	}
	if s.DefaultEnvVars.IsValue() {
		vals = append(vals, "default_env_vars")
	}
	if s.LinuxAllowBackups.IsValue() {
		vals = append(vals, "linux_allow_backups")
	}
	if s.WindowsAllowBackups.IsValue() {
		vals = append(vals, "windows_allow_backups")
	}
	if s.ConsoleCommands.IsValue() {
		vals = append(vals, "console_commands")
	}
	return vals
}

func (s GameSetter) Overwrite(t *Game) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.DefaultPort.IsValue() {
		t.DefaultPort = s.DefaultPort.MustGet()
	}
	if s.DefaultQueryPort.IsValue() {
		t.DefaultQueryPort = s.DefaultQueryPort.MustGet()
	}
	if s.DefaultMaxPlayers.IsValue() {
		t.DefaultMaxPlayers = s.DefaultMaxPlayers.MustGet()
	}
	if s.RequireDedicatedIP.IsValue() {
		t.RequireDedicatedIP = s.RequireDedicatedIP.MustGet()
	}
	if s.UsesSourceQuery.IsValue() {
		t.UsesSourceQuery = s.UsesSourceQuery.MustGet()
	}
	if s.UsesSteamcmd.IsValue() {
		t.UsesSteamcmd = s.UsesSteamcmd.MustGet()
	}
	if s.SteamAppID.IsValue() {
		t.SteamAppID = s.SteamAppID.MustGet()
	}
	if s.RequiresSteamGameServerLoginToken.IsValue() {
		t.RequiresSteamGameServerLoginToken = s.RequiresSteamGameServerLoginToken.MustGet()
	}
	if s.LinuxSupport.IsValue() {
		t.LinuxSupport = s.LinuxSupport.MustGet()
	}
	if s.LinuxStopCommand.IsValue() {
		t.LinuxStopCommand = s.LinuxStopCommand.MustGet()
	}
	if s.LinuxInstallCommand.IsValue() {
		t.LinuxInstallCommand = s.LinuxInstallCommand.MustGet()
	}
	if s.LinuxInstallCommandType.IsValue() {
		t.LinuxInstallCommandType = s.LinuxInstallCommandType.MustGet()
	}
	if s.LinuxUpdateCommand.IsValue() {
		t.LinuxUpdateCommand = s.LinuxUpdateCommand.MustGet()
	}
	if s.LinuxUpdateCommandType.IsValue() {
		t.LinuxUpdateCommandType = s.LinuxUpdateCommandType.MustGet()
	}
	if s.LinuxWorkingDirectory.IsValue() {
		t.LinuxWorkingDirectory = s.LinuxWorkingDirectory.MustGet()
	}
	if s.WindowsSupport.IsValue() {
		t.WindowsSupport = s.WindowsSupport.MustGet()
	}
	if s.WindowsStopCommand.IsValue() {
		t.WindowsStopCommand = s.WindowsStopCommand.MustGet()
	}
	if s.WindowsInstallCommand.IsValue() {
		t.WindowsInstallCommand = s.WindowsInstallCommand.MustGet()
	}
	if s.WindowsInstallCommandType.IsValue() {
		t.WindowsInstallCommandType = s.WindowsInstallCommandType.MustGet()
	}
	if s.WindowsUpdateCommand.IsValue() {
		t.WindowsUpdateCommand = s.WindowsUpdateCommand.MustGet()
	}
	if s.WindowsUpdateCommandType.IsValue() {
		t.WindowsUpdateCommandType = s.WindowsUpdateCommandType.MustGet()
	}
	if s.WindowsWorkingDirectory.IsValue() {
		t.WindowsWorkingDirectory = s.WindowsWorkingDirectory.MustGet()
	}
	if s.BindsToAllIps.IsValue() {
		t.BindsToAllIps = s.BindsToAllIps.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
	if s.XylonaOfficial.IsValue() {
		t.XylonaOfficial = s.XylonaOfficial.MustGet()
	}
	if s.ConfigSchemas.IsValue() || s.ConfigSchemas.IsNull() {
		t.ConfigSchemas = s.ConfigSchemas.MustGetNull()
	}
	if s.ServerSoftware.IsValue() || s.ServerSoftware.IsNull() {
		t.ServerSoftware = s.ServerSoftware.MustGetNull()
	}
	if s.LinuxStartArgsTemplate.IsValue() || s.LinuxStartArgsTemplate.IsNull() {
		t.LinuxStartArgsTemplate = s.LinuxStartArgsTemplate.MustGetNull()
	}
	if s.WindowsStartArgsTemplate.IsValue() || s.WindowsStartArgsTemplate.IsNull() {
		t.WindowsStartArgsTemplate = s.WindowsStartArgsTemplate.MustGetNull()
	}
	if s.LinuxBaseCommand.IsValue() {
		t.LinuxBaseCommand = s.LinuxBaseCommand.MustGet()
	}
	if s.WindowsBaseCommand.IsValue() {
		t.WindowsBaseCommand = s.WindowsBaseCommand.MustGet()
	}
	if s.StartArgBlocklist.IsValue() {
		t.StartArgBlocklist = s.StartArgBlocklist.MustGet()
	}
	if s.AllowStartArgEditing.IsValue() {
		t.AllowStartArgEditing = s.AllowStartArgEditing.MustGet()
	}
	if s.OfficialDefinitionHash.IsValue() {
		t.OfficialDefinitionHash = s.OfficialDefinitionHash.MustGet()
	}
	if s.OfficialDefinitionSource.IsValue() {
		t.OfficialDefinitionSource = s.OfficialDefinitionSource.MustGet()
	}
	if s.OfficialDefinitionSchemaVersion.IsValue() {
		t.OfficialDefinitionSchemaVersion = s.OfficialDefinitionSchemaVersion.MustGet()
	}
	if s.OfficialDefinitionDiverged.IsValue() {
		t.OfficialDefinitionDiverged = s.OfficialDefinitionDiverged.MustGet()
	}
	if s.DefaultEnvVars.IsValue() {
		t.DefaultEnvVars = s.DefaultEnvVars.MustGet()
	}
	if s.LinuxAllowBackups.IsValue() {
		t.LinuxAllowBackups = s.LinuxAllowBackups.MustGet()
	}
	if s.WindowsAllowBackups.IsValue() {
		t.WindowsAllowBackups = s.WindowsAllowBackups.MustGet()
	}
	if s.ConsoleCommands.IsValue() {
		t.ConsoleCommands = s.ConsoleCommands.MustGet()
	}
}

func (s *GameSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Games.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	vals := make([]bob.Expression, 0, len(q.TableRef.Columns))
	for _, col := range q.TableRef.Columns {
		switch col {
		case "id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ID.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "name":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Name.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.Name.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "default_port":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.DefaultPort.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.DefaultPort.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "default_query_port":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.DefaultQueryPort.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.DefaultQueryPort.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "default_max_players":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.DefaultMaxPlayers.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.DefaultMaxPlayers.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "require_dedicated_ip":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.RequireDedicatedIP.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.RequireDedicatedIP.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "uses_source_query":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.UsesSourceQuery.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.UsesSourceQuery.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "uses_steamcmd":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.UsesSteamcmd.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.UsesSteamcmd.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "steam_app_id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.SteamAppID.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.SteamAppID.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "requires_steam_game_server_login_token":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.RequiresSteamGameServerLoginToken.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.RequiresSteamGameServerLoginToken.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "linux_support":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.LinuxSupport.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.LinuxSupport.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "linux_stop_command":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.LinuxStopCommand.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.LinuxStopCommand.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "linux_install_command":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.LinuxInstallCommand.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.LinuxInstallCommand.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "linux_install_command_type":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.LinuxInstallCommandType.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.LinuxInstallCommandType.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "linux_update_command":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.LinuxUpdateCommand.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.LinuxUpdateCommand.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "linux_update_command_type":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.LinuxUpdateCommandType.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.LinuxUpdateCommandType.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "linux_working_directory":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.LinuxWorkingDirectory.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.LinuxWorkingDirectory.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "windows_support":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.WindowsSupport.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.WindowsSupport.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "windows_stop_command":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.WindowsStopCommand.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.WindowsStopCommand.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "windows_install_command":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.WindowsInstallCommand.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.WindowsInstallCommand.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "windows_install_command_type":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.WindowsInstallCommandType.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.WindowsInstallCommandType.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "windows_update_command":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.WindowsUpdateCommand.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.WindowsUpdateCommand.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "windows_update_command_type":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.WindowsUpdateCommandType.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.WindowsUpdateCommandType.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "windows_working_directory":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.WindowsWorkingDirectory.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.WindowsWorkingDirectory.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "binds_to_all_ips":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.BindsToAllIps.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.BindsToAllIps.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "created_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.CreatedAt.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "updated_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.UpdatedAt.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.UpdatedAt.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "xylona_official":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.XylonaOfficial.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.XylonaOfficial.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "config_schemas":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ConfigSchemas.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.ConfigSchemas.MustGetNull()).WriteSQL(ctx, w, d, start)
			}))
		case "server_software":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ServerSoftware.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.ServerSoftware.MustGetNull()).WriteSQL(ctx, w, d, start)
			}))
		case "linux_start_args_template":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.LinuxStartArgsTemplate.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.LinuxStartArgsTemplate.MustGetNull()).WriteSQL(ctx, w, d, start)
			}))
		case "windows_start_args_template":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.WindowsStartArgsTemplate.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.WindowsStartArgsTemplate.MustGetNull()).WriteSQL(ctx, w, d, start)
			}))
		case "linux_base_command":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.LinuxBaseCommand.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.LinuxBaseCommand.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "windows_base_command":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.WindowsBaseCommand.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.WindowsBaseCommand.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "start_arg_blocklist":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.StartArgBlocklist.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.StartArgBlocklist.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "allow_start_arg_editing":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.AllowStartArgEditing.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.AllowStartArgEditing.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "official_definition_hash":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.OfficialDefinitionHash.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.OfficialDefinitionHash.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "official_definition_source":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.OfficialDefinitionSource.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.OfficialDefinitionSource.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "official_definition_schema_version":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.OfficialDefinitionSchemaVersion.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.OfficialDefinitionSchemaVersion.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "official_definition_diverged":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.OfficialDefinitionDiverged.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.OfficialDefinitionDiverged.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "default_env_vars":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.DefaultEnvVars.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.DefaultEnvVars.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "linux_allow_backups":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.LinuxAllowBackups.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.LinuxAllowBackups.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "windows_allow_backups":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.WindowsAllowBackups.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.WindowsAllowBackups.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "console_commands":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ConsoleCommands.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.ConsoleCommands.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		}
	}

	q.AppendValues(vals...)
}

func (s GameSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s GameSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 44)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "name")...),
			sqlite.Arg(s.Name),
		}})
	}

	if s.DefaultPort.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "default_port")...),
			sqlite.Arg(s.DefaultPort),
		}})
	}

	if s.DefaultQueryPort.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "default_query_port")...),
			sqlite.Arg(s.DefaultQueryPort),
		}})
	}

	if s.DefaultMaxPlayers.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "default_max_players")...),
			sqlite.Arg(s.DefaultMaxPlayers),
		}})
	}

	if s.RequireDedicatedIP.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "require_dedicated_ip")...),
			sqlite.Arg(s.RequireDedicatedIP),
		}})
	}

	if s.UsesSourceQuery.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "uses_source_query")...),
			sqlite.Arg(s.UsesSourceQuery),
		}})
	}

	if s.UsesSteamcmd.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "uses_steamcmd")...),
			sqlite.Arg(s.UsesSteamcmd),
		}})
	}

	if s.SteamAppID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "steam_app_id")...),
			sqlite.Arg(s.SteamAppID),
		}})
	}

	if s.RequiresSteamGameServerLoginToken.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "requires_steam_game_server_login_token")...),
			sqlite.Arg(s.RequiresSteamGameServerLoginToken),
		}})
	}

	if s.LinuxSupport.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "linux_support")...),
			sqlite.Arg(s.LinuxSupport),
		}})
	}

	if s.LinuxStopCommand.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "linux_stop_command")...),
			sqlite.Arg(s.LinuxStopCommand),
		}})
	}

	if s.LinuxInstallCommand.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "linux_install_command")...),
			sqlite.Arg(s.LinuxInstallCommand),
		}})
	}

	if s.LinuxInstallCommandType.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "linux_install_command_type")...),
			sqlite.Arg(s.LinuxInstallCommandType),
		}})
	}

	if s.LinuxUpdateCommand.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "linux_update_command")...),
			sqlite.Arg(s.LinuxUpdateCommand),
		}})
	}

	if s.LinuxUpdateCommandType.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "linux_update_command_type")...),
			sqlite.Arg(s.LinuxUpdateCommandType),
		}})
	}

	if s.LinuxWorkingDirectory.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "linux_working_directory")...),
			sqlite.Arg(s.LinuxWorkingDirectory),
		}})
	}

	if s.WindowsSupport.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "windows_support")...),
			sqlite.Arg(s.WindowsSupport),
		}})
	}

	if s.WindowsStopCommand.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "windows_stop_command")...),
			sqlite.Arg(s.WindowsStopCommand),
		}})
	}

	if s.WindowsInstallCommand.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "windows_install_command")...),
			sqlite.Arg(s.WindowsInstallCommand),
		}})
	}

	if s.WindowsInstallCommandType.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "windows_install_command_type")...),
			sqlite.Arg(s.WindowsInstallCommandType),
		}})
	}

	if s.WindowsUpdateCommand.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "windows_update_command")...),
			sqlite.Arg(s.WindowsUpdateCommand),
		}})
	}

	if s.WindowsUpdateCommandType.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "windows_update_command_type")...),
			sqlite.Arg(s.WindowsUpdateCommandType),
		}})
	}

	if s.WindowsWorkingDirectory.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "windows_working_directory")...),
			sqlite.Arg(s.WindowsWorkingDirectory),
		}})
	}

	if s.BindsToAllIps.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "binds_to_all_ips")...),
			sqlite.Arg(s.BindsToAllIps),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "created_at")...),
			sqlite.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "updated_at")...),
			sqlite.Arg(s.UpdatedAt),
		}})
	}

	if s.XylonaOfficial.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "xylona_official")...),
			sqlite.Arg(s.XylonaOfficial),
		}})
	}

	if s.ConfigSchemas.IsValue() || s.ConfigSchemas.IsNull() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "config_schemas")...),
			sqlite.Arg(s.ConfigSchemas),
		}})
	}

	if s.ServerSoftware.IsValue() || s.ServerSoftware.IsNull() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "server_software")...),
			sqlite.Arg(s.ServerSoftware),
		}})
	}

	if s.LinuxStartArgsTemplate.IsValue() || s.LinuxStartArgsTemplate.IsNull() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "linux_start_args_template")...),
			sqlite.Arg(s.LinuxStartArgsTemplate),
		}})
	}

	if s.WindowsStartArgsTemplate.IsValue() || s.WindowsStartArgsTemplate.IsNull() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "windows_start_args_template")...),
			sqlite.Arg(s.WindowsStartArgsTemplate),
		}})
	}

	if s.LinuxBaseCommand.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "linux_base_command")...),
			sqlite.Arg(s.LinuxBaseCommand),
		}})
	}

	if s.WindowsBaseCommand.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "windows_base_command")...),
			sqlite.Arg(s.WindowsBaseCommand),
		}})
	}

	if s.StartArgBlocklist.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "start_arg_blocklist")...),
			sqlite.Arg(s.StartArgBlocklist),
		}})
	}

	if s.AllowStartArgEditing.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "allow_start_arg_editing")...),
			sqlite.Arg(s.AllowStartArgEditing),
		}})
	}

	if s.OfficialDefinitionHash.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "official_definition_hash")...),
			sqlite.Arg(s.OfficialDefinitionHash),
		}})
	}

	if s.OfficialDefinitionSource.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "official_definition_source")...),
			sqlite.Arg(s.OfficialDefinitionSource),
		}})
	}

	if s.OfficialDefinitionSchemaVersion.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "official_definition_schema_version")...),
			sqlite.Arg(s.OfficialDefinitionSchemaVersion),
		}})
	}

	if s.OfficialDefinitionDiverged.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "official_definition_diverged")...),
			sqlite.Arg(s.OfficialDefinitionDiverged),
		}})
	}

	if s.DefaultEnvVars.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "default_env_vars")...),
			sqlite.Arg(s.DefaultEnvVars),
		}})
	}

	if s.LinuxAllowBackups.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "linux_allow_backups")...),
			sqlite.Arg(s.LinuxAllowBackups),
		}})
	}

	if s.WindowsAllowBackups.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "windows_allow_backups")...),
			sqlite.Arg(s.WindowsAllowBackups),
		}})
	}

	if s.ConsoleCommands.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "console_commands")...),
			sqlite.Arg(s.ConsoleCommands),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func gameScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*Game, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *Game) any
	}
	targets := make([]target, 0, 44)
	for i, col := range cols {
		switch col {
		case "id":
			targets = append(targets, target{i, func(o *Game) any { return &o.ID }})
		case "name":
			targets = append(targets, target{i, func(o *Game) any { return &o.Name }})
		case "default_port":
			targets = append(targets, target{i, func(o *Game) any { return &o.DefaultPort }})
		case "default_query_port":
			targets = append(targets, target{i, func(o *Game) any { return &o.DefaultQueryPort }})
		case "default_max_players":
			targets = append(targets, target{i, func(o *Game) any { return &o.DefaultMaxPlayers }})
		case "require_dedicated_ip":
			targets = append(targets, target{i, func(o *Game) any { return &o.RequireDedicatedIP }})
		case "uses_source_query":
			targets = append(targets, target{i, func(o *Game) any { return &o.UsesSourceQuery }})
		case "uses_steamcmd":
			targets = append(targets, target{i, func(o *Game) any { return &o.UsesSteamcmd }})
		case "steam_app_id":
			targets = append(targets, target{i, func(o *Game) any { return &o.SteamAppID }})
		case "requires_steam_game_server_login_token":
			targets = append(targets, target{i, func(o *Game) any { return &o.RequiresSteamGameServerLoginToken }})
		case "linux_support":
			targets = append(targets, target{i, func(o *Game) any { return &o.LinuxSupport }})
		case "linux_stop_command":
			targets = append(targets, target{i, func(o *Game) any { return &o.LinuxStopCommand }})
		case "linux_install_command":
			targets = append(targets, target{i, func(o *Game) any { return &o.LinuxInstallCommand }})
		case "linux_install_command_type":
			targets = append(targets, target{i, func(o *Game) any { return &o.LinuxInstallCommandType }})
		case "linux_update_command":
			targets = append(targets, target{i, func(o *Game) any { return &o.LinuxUpdateCommand }})
		case "linux_update_command_type":
			targets = append(targets, target{i, func(o *Game) any { return &o.LinuxUpdateCommandType }})
		case "linux_working_directory":
			targets = append(targets, target{i, func(o *Game) any { return &o.LinuxWorkingDirectory }})
		case "windows_support":
			targets = append(targets, target{i, func(o *Game) any { return &o.WindowsSupport }})
		case "windows_stop_command":
			targets = append(targets, target{i, func(o *Game) any { return &o.WindowsStopCommand }})
		case "windows_install_command":
			targets = append(targets, target{i, func(o *Game) any { return &o.WindowsInstallCommand }})
		case "windows_install_command_type":
			targets = append(targets, target{i, func(o *Game) any { return &o.WindowsInstallCommandType }})
		case "windows_update_command":
			targets = append(targets, target{i, func(o *Game) any { return &o.WindowsUpdateCommand }})
		case "windows_update_command_type":
			targets = append(targets, target{i, func(o *Game) any { return &o.WindowsUpdateCommandType }})
		case "windows_working_directory":
			targets = append(targets, target{i, func(o *Game) any { return &o.WindowsWorkingDirectory }})
		case "binds_to_all_ips":
			targets = append(targets, target{i, func(o *Game) any { return &o.BindsToAllIps }})
		case "created_at":
			targets = append(targets, target{i, func(o *Game) any { return &o.CreatedAt }})
		case "updated_at":
			targets = append(targets, target{i, func(o *Game) any { return &o.UpdatedAt }})
		case "xylona_official":
			targets = append(targets, target{i, func(o *Game) any { return &o.XylonaOfficial }})
		case "config_schemas":
			targets = append(targets, target{i, func(o *Game) any { return &o.ConfigSchemas }})
		case "server_software":
			targets = append(targets, target{i, func(o *Game) any { return &o.ServerSoftware }})
		case "linux_start_args_template":
			targets = append(targets, target{i, func(o *Game) any { return &o.LinuxStartArgsTemplate }})
		case "windows_start_args_template":
			targets = append(targets, target{i, func(o *Game) any { return &o.WindowsStartArgsTemplate }})
		case "linux_base_command":
			targets = append(targets, target{i, func(o *Game) any { return &o.LinuxBaseCommand }})
		case "windows_base_command":
			targets = append(targets, target{i, func(o *Game) any { return &o.WindowsBaseCommand }})
		case "start_arg_blocklist":
			targets = append(targets, target{i, func(o *Game) any { return &o.StartArgBlocklist }})
		case "allow_start_arg_editing":
			targets = append(targets, target{i, func(o *Game) any { return &o.AllowStartArgEditing }})
		case "official_definition_hash":
			targets = append(targets, target{i, func(o *Game) any { return &o.OfficialDefinitionHash }})
		case "official_definition_source":
			targets = append(targets, target{i, func(o *Game) any { return &o.OfficialDefinitionSource }})
		case "official_definition_schema_version":
			targets = append(targets, target{i, func(o *Game) any { return &o.OfficialDefinitionSchemaVersion }})
		case "official_definition_diverged":
			targets = append(targets, target{i, func(o *Game) any { return &o.OfficialDefinitionDiverged }})
		case "default_env_vars":
			targets = append(targets, target{i, func(o *Game) any { return &o.DefaultEnvVars }})
		case "linux_allow_backups":
			targets = append(targets, target{i, func(o *Game) any { return &o.LinuxAllowBackups }})
		case "windows_allow_backups":
			targets = append(targets, target{i, func(o *Game) any { return &o.WindowsAllowBackups }})
		case "console_commands":
			targets = append(targets, target{i, func(o *Game) any { return &o.ConsoleCommands }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(Game)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*Game, error) {
			return v.(*Game), nil
		}
}

// FindGame retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindGame(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*Game, error) {
	if len(cols) == 0 {
		return Games.Query(
			sm.Where(Games.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Games.Query(
		sm.Where(Games.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(Games.Columns.Only(cols...)),
	).One(ctx, exec)
}

// GameExists checks the presence of a single record by primary key
func GameExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Games.Query(
		sm.Where(Games.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Game is retrieved from the database
func (o *Game) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Games.AfterSelectHooks.RunHooks(ctx, exec, GameSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Games.AfterInsertHooks.RunHooks(ctx, exec, GameSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Games.AfterUpdateHooks.RunHooks(ctx, exec, GameSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Games.AfterDeleteHooks.RunHooks(ctx, exec, GameSlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the Game
func (o *Game) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *Game) pkEQ() dialect.Expression {
	return sqlite.Quote("game", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Game
func (o *Game) Update(ctx context.Context, exec bob.Executor, s *GameSetter) error {
	v, err := Games.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Game record with an executor
func (o *Game) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Games.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Game using the executor
func (o *Game) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Games.Query(
		sm.Where(Games.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after GameSlice is retrieved from the database
func (o GameSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Games.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Games.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Games.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Games.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o GameSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("game", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o GameSlice) copyMatchingRows(from ...*Game) {
	fromByPK := make(map[string]*Game, len(from))
	for _, new := range from {
		// keep the first row for each key, like the nested loop did
		if _, ok := fromByPK[new.ID]; !ok {
			fromByPK[new.ID] = new
		}
	}

	for i, old := range o {
		new, ok := fromByPK[old.ID]
		if !ok {
			continue
		}
		new.R = old.R
		o[i] = new
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o GameSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Games.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Game:
				o.copyMatchingRows(retrieved)
			case []*Game:
				o.copyMatchingRows(retrieved...)
			case GameSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Game or a slice of Game
				// then run the AfterUpdateHooks on the slice
				_, err = Games.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o GameSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Games.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Game:
				o.copyMatchingRows(retrieved)
			case []*Game:
				o.copyMatchingRows(retrieved...)
			case GameSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Game or a slice of Game
				// then run the AfterDeleteHooks on the slice
				_, err = Games.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o GameSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals GameSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Games.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o GameSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Games.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o GameSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Games.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// GameServers starts a query for related objects on game_server
func (o *Game) GameServers(mods ...bob.Mod[*dialect.SelectQuery]) GameServersQuery {
	return GameServers.Query(append(mods,
		sm.Where(GameServers.Columns.GameID.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os GameSlice) GameServers(mods ...bob.Mod[*dialect.SelectQuery]) GameServersQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return GameServers.Query(append(mods,
		sm.Where(sqlite.Group(GameServers.Columns.GameID).OP("IN", PKArgExpr)),
	)...)
}

func insertGameGameServers0(ctx context.Context, exec bob.Executor, gameServers1 []*GameServerSetter, game0 *Game) (GameServerSlice, error) {
	for i := range gameServers1 {
		gameServers1[i].GameID = omit.From(game0.ID)
	}

	ret, err := GameServers.Insert(bob.ToMods(gameServers1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertGameGameServers0: %w", err)
	}

	return ret, nil
}

func attachGameGameServers0(ctx context.Context, exec bob.Executor, count int, gameServers1 GameServerSlice, game0 *Game) (GameServerSlice, error) {
	setter := &GameServerSetter{
		GameID: omit.From(game0.ID),
	}

	err := gameServers1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachGameGameServers0: %w", err)
	}

	return gameServers1, nil
}

func (game0 *Game) InsertGameServers(ctx context.Context, exec bob.Executor, related ...*GameServerSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	gameServers1, err := insertGameGameServers0(ctx, exec, related, game0)
	if err != nil {
		return err
	}

	game0.R.GameServers = append(game0.R.GameServers, gameServers1...)

	for _, rel := range gameServers1 {
		rel.R.Game = game0
		rel.R.Loaded.Game = true
	}
	return nil
}

func (game0 *Game) AttachGameServers(ctx context.Context, exec bob.Executor, related ...*GameServer) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	gameServers1 := GameServerSlice(related)

	_, err = attachGameGameServers0(ctx, exec, len(related), gameServers1, game0)
	if err != nil {
		return err
	}

	game0.R.GameServers = append(game0.R.GameServers, gameServers1...)

	for _, rel := range related {
		rel.R.Game = game0
		rel.R.Loaded.Game = true
	}

	return nil
}

type gameWhere[Q sqlite.Filterable] struct {
	cols                              gameColumns
	ID                                sqlite.WhereMod[Q, string]
	Name                              sqlite.WhereMod[Q, string]
	DefaultPort                       sqlite.WhereMod[Q, int64]
	DefaultQueryPort                  sqlite.WhereMod[Q, int64]
	DefaultMaxPlayers                 sqlite.WhereMod[Q, int64]
	RequireDedicatedIP                sqlite.WhereMod[Q, bool]
	UsesSourceQuery                   sqlite.WhereMod[Q, bool]
	UsesSteamcmd                      sqlite.WhereMod[Q, bool]
	SteamAppID                        sqlite.WhereMod[Q, string]
	RequiresSteamGameServerLoginToken sqlite.WhereMod[Q, bool]
	LinuxSupport                      sqlite.WhereMod[Q, bool]
	LinuxStopCommand                  sqlite.WhereMod[Q, string]
	LinuxInstallCommand               sqlite.WhereMod[Q, string]
	LinuxInstallCommandType           sqlite.WhereMod[Q, string]
	LinuxUpdateCommand                sqlite.WhereMod[Q, string]
	LinuxUpdateCommandType            sqlite.WhereMod[Q, string]
	LinuxWorkingDirectory             sqlite.WhereMod[Q, string]
	WindowsSupport                    sqlite.WhereMod[Q, bool]
	WindowsStopCommand                sqlite.WhereMod[Q, string]
	WindowsInstallCommand             sqlite.WhereMod[Q, string]
	WindowsInstallCommandType         sqlite.WhereMod[Q, string]
	WindowsUpdateCommand              sqlite.WhereMod[Q, string]
	WindowsUpdateCommandType          sqlite.WhereMod[Q, string]
	WindowsWorkingDirectory           sqlite.WhereMod[Q, string]
	BindsToAllIps                     sqlite.WhereMod[Q, bool]
	CreatedAt                         sqlite.WhereMod[Q, time.Time]
	UpdatedAt                         sqlite.WhereMod[Q, time.Time]
	XylonaOfficial                    sqlite.WhereMod[Q, bool]
	ConfigSchemas                     sqlite.WhereNullMod[Q, string]
	ServerSoftware                    sqlite.WhereNullMod[Q, string]
	LinuxStartArgsTemplate            sqlite.WhereNullMod[Q, string]
	WindowsStartArgsTemplate          sqlite.WhereNullMod[Q, string]
	LinuxBaseCommand                  sqlite.WhereMod[Q, string]
	WindowsBaseCommand                sqlite.WhereMod[Q, string]
	StartArgBlocklist                 sqlite.WhereMod[Q, string]
	AllowStartArgEditing              sqlite.WhereMod[Q, bool]
	OfficialDefinitionHash            sqlite.WhereMod[Q, string]
	OfficialDefinitionSource          sqlite.WhereMod[Q, string]
	OfficialDefinitionSchemaVersion   sqlite.WhereMod[Q, int64]
	OfficialDefinitionDiverged        sqlite.WhereMod[Q, bool]
	DefaultEnvVars                    sqlite.WhereMod[Q, string]
	LinuxAllowBackups                 sqlite.WhereMod[Q, bool]
	WindowsAllowBackups               sqlite.WhereMod[Q, bool]
	ConsoleCommands                   sqlite.WhereMod[Q, string]
	R                                 gameWhereR[Q]
}

func (gameWhere[Q]) AliasedAs(alias string) gameWhere[Q] {
	return buildGameWhere[Q](buildGameColumns(alias))
}

func buildGameWhere[Q sqlite.Filterable](cols gameColumns) gameWhere[Q] {
	return gameWhere[Q]{
		cols:                              cols,
		ID:                                sqlite.Where[Q, string](cols.ID.Expression),
		Name:                              sqlite.Where[Q, string](cols.Name.Expression),
		DefaultPort:                       sqlite.Where[Q, int64](cols.DefaultPort.Expression),
		DefaultQueryPort:                  sqlite.Where[Q, int64](cols.DefaultQueryPort.Expression),
		DefaultMaxPlayers:                 sqlite.Where[Q, int64](cols.DefaultMaxPlayers.Expression),
		RequireDedicatedIP:                sqlite.Where[Q, bool](cols.RequireDedicatedIP.Expression),
		UsesSourceQuery:                   sqlite.Where[Q, bool](cols.UsesSourceQuery.Expression),
		UsesSteamcmd:                      sqlite.Where[Q, bool](cols.UsesSteamcmd.Expression),
		SteamAppID:                        sqlite.Where[Q, string](cols.SteamAppID.Expression),
		RequiresSteamGameServerLoginToken: sqlite.Where[Q, bool](cols.RequiresSteamGameServerLoginToken.Expression),
		LinuxSupport:                      sqlite.Where[Q, bool](cols.LinuxSupport.Expression),
		LinuxStopCommand:                  sqlite.Where[Q, string](cols.LinuxStopCommand.Expression),
		LinuxInstallCommand:               sqlite.Where[Q, string](cols.LinuxInstallCommand.Expression),
		LinuxInstallCommandType:           sqlite.Where[Q, string](cols.LinuxInstallCommandType.Expression),
		LinuxUpdateCommand:                sqlite.Where[Q, string](cols.LinuxUpdateCommand.Expression),
		LinuxUpdateCommandType:            sqlite.Where[Q, string](cols.LinuxUpdateCommandType.Expression),
		LinuxWorkingDirectory:             sqlite.Where[Q, string](cols.LinuxWorkingDirectory.Expression),
		WindowsSupport:                    sqlite.Where[Q, bool](cols.WindowsSupport.Expression),
		WindowsStopCommand:                sqlite.Where[Q, string](cols.WindowsStopCommand.Expression),
		WindowsInstallCommand:             sqlite.Where[Q, string](cols.WindowsInstallCommand.Expression),
		WindowsInstallCommandType:         sqlite.Where[Q, string](cols.WindowsInstallCommandType.Expression),
		WindowsUpdateCommand:              sqlite.Where[Q, string](cols.WindowsUpdateCommand.Expression),
		WindowsUpdateCommandType:          sqlite.Where[Q, string](cols.WindowsUpdateCommandType.Expression),
		WindowsWorkingDirectory:           sqlite.Where[Q, string](cols.WindowsWorkingDirectory.Expression),
		BindsToAllIps:                     sqlite.Where[Q, bool](cols.BindsToAllIps.Expression),
		CreatedAt:                         sqlite.Where[Q, time.Time](cols.CreatedAt.Expression),
		UpdatedAt:                         sqlite.Where[Q, time.Time](cols.UpdatedAt.Expression),
		XylonaOfficial:                    sqlite.Where[Q, bool](cols.XylonaOfficial.Expression),
		ConfigSchemas:                     sqlite.WhereNull[Q, string](cols.ConfigSchemas.Expression),
		ServerSoftware:                    sqlite.WhereNull[Q, string](cols.ServerSoftware.Expression),
		LinuxStartArgsTemplate:            sqlite.WhereNull[Q, string](cols.LinuxStartArgsTemplate.Expression),
		WindowsStartArgsTemplate:          sqlite.WhereNull[Q, string](cols.WindowsStartArgsTemplate.Expression),
		LinuxBaseCommand:                  sqlite.Where[Q, string](cols.LinuxBaseCommand.Expression),
		WindowsBaseCommand:                sqlite.Where[Q, string](cols.WindowsBaseCommand.Expression),
		StartArgBlocklist:                 sqlite.Where[Q, string](cols.StartArgBlocklist.Expression),
		AllowStartArgEditing:              sqlite.Where[Q, bool](cols.AllowStartArgEditing.Expression),
		OfficialDefinitionHash:            sqlite.Where[Q, string](cols.OfficialDefinitionHash.Expression),
		OfficialDefinitionSource:          sqlite.Where[Q, string](cols.OfficialDefinitionSource.Expression),
		OfficialDefinitionSchemaVersion:   sqlite.Where[Q, int64](cols.OfficialDefinitionSchemaVersion.Expression),
		OfficialDefinitionDiverged:        sqlite.Where[Q, bool](cols.OfficialDefinitionDiverged.Expression),
		DefaultEnvVars:                    sqlite.Where[Q, string](cols.DefaultEnvVars.Expression),
		LinuxAllowBackups:                 sqlite.Where[Q, bool](cols.LinuxAllowBackups.Expression),
		WindowsAllowBackups:               sqlite.Where[Q, bool](cols.WindowsAllowBackups.Expression),
		ConsoleCommands:                   sqlite.Where[Q, string](cols.ConsoleCommands.Expression),
		R:                                 gameWhereR[Q]{cols: cols},
	}
}

// gameWhereR holds the relationship-based filters of
// gameWhere under the R namespace — mirroring the model's
// R struct — so they cannot collide with column-based filter fields.
type gameWhereR[Q sqlite.Filterable] struct {
	cols gameColumns
}

// HasGameServers filters parents that have a matching GameServers using a
// correlated EXISTS subquery (semi-join). Unlike an INNER JOIN it does not
// multiply parent rows, so no DISTINCT is needed. The optional filters are
// applied to the subquery (i.e. to GameServers).
func (w gameWhereR[Q]) HasGameServers(filters ...bob.Mod[*dialect.SelectQuery]) mods.Where[Q] {
	q := sqlite.Select(
		sm.Columns(sqlite.Raw("1")),
		sm.From(GameServers.NameExpr()),
		sm.Where(GameServers.Columns.GameID.EQ(w.cols.ID)),
	)
	q.Apply(filters...)
	return mods.Where[Q]{E: sqlite.Exists(q)}
}

// NULL-tolerant scan buffer for gameScanMapperNullable:
// on a LEFT JOIN miss every column comes back NULL, so each field uses the
// nullable version of the column type even when the column itself is NOT NULL.
type gamePreloadBuf struct {
	ID                                null.Val[string]
	Name                              null.Val[string]
	DefaultPort                       null.Val[int64]
	DefaultQueryPort                  null.Val[int64]
	DefaultMaxPlayers                 null.Val[int64]
	RequireDedicatedIP                null.Val[bool]
	UsesSourceQuery                   null.Val[bool]
	UsesSteamcmd                      null.Val[bool]
	SteamAppID                        null.Val[string]
	RequiresSteamGameServerLoginToken null.Val[bool]
	LinuxSupport                      null.Val[bool]
	LinuxStopCommand                  null.Val[string]
	LinuxInstallCommand               null.Val[string]
	LinuxInstallCommandType           null.Val[string]
	LinuxUpdateCommand                null.Val[string]
	LinuxUpdateCommandType            null.Val[string]
	LinuxWorkingDirectory             null.Val[string]
	WindowsSupport                    null.Val[bool]
	WindowsStopCommand                null.Val[string]
	WindowsInstallCommand             null.Val[string]
	WindowsInstallCommandType         null.Val[string]
	WindowsUpdateCommand              null.Val[string]
	WindowsUpdateCommandType          null.Val[string]
	WindowsWorkingDirectory           null.Val[string]
	BindsToAllIps                     null.Val[bool]
	CreatedAt                         null.Val[time.Time]
	UpdatedAt                         null.Val[time.Time]
	XylonaOfficial                    null.Val[bool]
	ConfigSchemas                     null.Val[string]
	ServerSoftware                    null.Val[string]
	LinuxStartArgsTemplate            null.Val[string]
	WindowsStartArgsTemplate          null.Val[string]
	LinuxBaseCommand                  null.Val[string]
	WindowsBaseCommand                null.Val[string]
	StartArgBlocklist                 null.Val[string]
	AllowStartArgEditing              null.Val[bool]
	OfficialDefinitionHash            null.Val[string]
	OfficialDefinitionSource          null.Val[string]
	OfficialDefinitionSchemaVersion   null.Val[int64]
	OfficialDefinitionDiverged        null.Val[bool]
	DefaultEnvVars                    null.Val[string]
	LinuxAllowBackups                 null.Val[bool]
	WindowsAllowBackups               null.Val[bool]
	ConsoleCommands                   null.Val[string]
}

// gameScanMapperNullable maps the preloaded game
// columns (prefixed with the runtime join alias) without reflection, while
// keeping the LEFT JOIN semantics of the reflection-based mapper: a row whose
// prefixed columns are all NULL yields nil (no child), and NULL values never
// error, they just leave the zero value in the field.
func gameScanMapperNullable(prefix string) scan.Mapper[*Game] {
	return func(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*Game, error)) {
		// resolve the column names once per query, not per row
		type target struct {
			idx int
			dst func(b *gamePreloadBuf) any
		}
		targets := make([]target, 0, 44)
		for i, col := range cols {
			name, ok := strings.CutPrefix(col, prefix)
			if !ok {
				continue
			}
			switch name {
			case "id":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.ID }})
			case "name":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.Name }})
			case "default_port":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.DefaultPort }})
			case "default_query_port":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.DefaultQueryPort }})
			case "default_max_players":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.DefaultMaxPlayers }})
			case "require_dedicated_ip":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.RequireDedicatedIP }})
			case "uses_source_query":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.UsesSourceQuery }})
			case "uses_steamcmd":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.UsesSteamcmd }})
			case "steam_app_id":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.SteamAppID }})
			case "requires_steam_game_server_login_token":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.RequiresSteamGameServerLoginToken }})
			case "linux_support":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.LinuxSupport }})
			case "linux_stop_command":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.LinuxStopCommand }})
			case "linux_install_command":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.LinuxInstallCommand }})
			case "linux_install_command_type":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.LinuxInstallCommandType }})
			case "linux_update_command":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.LinuxUpdateCommand }})
			case "linux_update_command_type":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.LinuxUpdateCommandType }})
			case "linux_working_directory":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.LinuxWorkingDirectory }})
			case "windows_support":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.WindowsSupport }})
			case "windows_stop_command":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.WindowsStopCommand }})
			case "windows_install_command":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.WindowsInstallCommand }})
			case "windows_install_command_type":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.WindowsInstallCommandType }})
			case "windows_update_command":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.WindowsUpdateCommand }})
			case "windows_update_command_type":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.WindowsUpdateCommandType }})
			case "windows_working_directory":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.WindowsWorkingDirectory }})
			case "binds_to_all_ips":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.BindsToAllIps }})
			case "created_at":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.CreatedAt }})
			case "updated_at":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.UpdatedAt }})
			case "xylona_official":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.XylonaOfficial }})
			case "config_schemas":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.ConfigSchemas }})
			case "server_software":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.ServerSoftware }})
			case "linux_start_args_template":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.LinuxStartArgsTemplate }})
			case "windows_start_args_template":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.WindowsStartArgsTemplate }})
			case "linux_base_command":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.LinuxBaseCommand }})
			case "windows_base_command":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.WindowsBaseCommand }})
			case "start_arg_blocklist":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.StartArgBlocklist }})
			case "allow_start_arg_editing":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.AllowStartArgEditing }})
			case "official_definition_hash":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.OfficialDefinitionHash }})
			case "official_definition_source":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.OfficialDefinitionSource }})
			case "official_definition_schema_version":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.OfficialDefinitionSchemaVersion }})
			case "official_definition_diverged":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.OfficialDefinitionDiverged }})
			case "default_env_vars":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.DefaultEnvVars }})
			case "linux_allow_backups":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.LinuxAllowBackups }})
			case "windows_allow_backups":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.WindowsAllowBackups }})
			case "console_commands":
				targets = append(targets, target{i, func(b *gamePreloadBuf) any { return &b.ConsoleCommands }})
			}
		}

		// One scratch buffer reused for every row: before -> scan -> after runs
		// synchronously per row, the scheduled columns are fully overwritten each
		// row, and unselected columns stay zero, so a single buffer preserves the
		// per-row NULL semantics without allocating a buffer per parent row. The
		// returned child (o below) is always freshly allocated, so buf never
		// escapes past the after func.
		buf := new(gamePreloadBuf)
		return func(row *scan.Row) (any, error) {
				for _, t := range targets {
					row.ScheduleScanByIndex(t.idx, t.dst(buf))
				}
				return buf, nil
			}, func(link any) (*Game, error) {
				buf := link.(*gamePreloadBuf)

				// Same rule as the reflection mapper's row validator: the child
				// exists only if at least one of its columns is not NULL. Columns
				// not selected by the query are never scanned and stay invalid,
				// so this check also matches when only a subset is selected.
				if !(buf.ID.IsValue()) &&
					!(buf.Name.IsValue()) &&
					!(buf.DefaultPort.IsValue()) &&
					!(buf.DefaultQueryPort.IsValue()) &&
					!(buf.DefaultMaxPlayers.IsValue()) &&
					!(buf.RequireDedicatedIP.IsValue()) &&
					!(buf.UsesSourceQuery.IsValue()) &&
					!(buf.UsesSteamcmd.IsValue()) &&
					!(buf.SteamAppID.IsValue()) &&
					!(buf.RequiresSteamGameServerLoginToken.IsValue()) &&
					!(buf.LinuxSupport.IsValue()) &&
					!(buf.LinuxStopCommand.IsValue()) &&
					!(buf.LinuxInstallCommand.IsValue()) &&
					!(buf.LinuxInstallCommandType.IsValue()) &&
					!(buf.LinuxUpdateCommand.IsValue()) &&
					!(buf.LinuxUpdateCommandType.IsValue()) &&
					!(buf.LinuxWorkingDirectory.IsValue()) &&
					!(buf.WindowsSupport.IsValue()) &&
					!(buf.WindowsStopCommand.IsValue()) &&
					!(buf.WindowsInstallCommand.IsValue()) &&
					!(buf.WindowsInstallCommandType.IsValue()) &&
					!(buf.WindowsUpdateCommand.IsValue()) &&
					!(buf.WindowsUpdateCommandType.IsValue()) &&
					!(buf.WindowsWorkingDirectory.IsValue()) &&
					!(buf.BindsToAllIps.IsValue()) &&
					!(buf.CreatedAt.IsValue()) &&
					!(buf.UpdatedAt.IsValue()) &&
					!(buf.XylonaOfficial.IsValue()) &&
					!(buf.ConfigSchemas.IsValue()) &&
					!(buf.ServerSoftware.IsValue()) &&
					!(buf.LinuxStartArgsTemplate.IsValue()) &&
					!(buf.WindowsStartArgsTemplate.IsValue()) &&
					!(buf.LinuxBaseCommand.IsValue()) &&
					!(buf.WindowsBaseCommand.IsValue()) &&
					!(buf.StartArgBlocklist.IsValue()) &&
					!(buf.AllowStartArgEditing.IsValue()) &&
					!(buf.OfficialDefinitionHash.IsValue()) &&
					!(buf.OfficialDefinitionSource.IsValue()) &&
					!(buf.OfficialDefinitionSchemaVersion.IsValue()) &&
					!(buf.OfficialDefinitionDiverged.IsValue()) &&
					!(buf.DefaultEnvVars.IsValue()) &&
					!(buf.LinuxAllowBackups.IsValue()) &&
					!(buf.WindowsAllowBackups.IsValue()) &&
					!(buf.ConsoleCommands.IsValue()) {
					return nil, nil
				}

				o := new(Game)
				if buf.ID.IsValue() {
					o.ID = buf.ID.MustGet()
				}
				if buf.Name.IsValue() {
					o.Name = buf.Name.MustGet()
				}
				if buf.DefaultPort.IsValue() {
					o.DefaultPort = buf.DefaultPort.MustGet()
				}
				if buf.DefaultQueryPort.IsValue() {
					o.DefaultQueryPort = buf.DefaultQueryPort.MustGet()
				}
				if buf.DefaultMaxPlayers.IsValue() {
					o.DefaultMaxPlayers = buf.DefaultMaxPlayers.MustGet()
				}
				if buf.RequireDedicatedIP.IsValue() {
					o.RequireDedicatedIP = buf.RequireDedicatedIP.MustGet()
				}
				if buf.UsesSourceQuery.IsValue() {
					o.UsesSourceQuery = buf.UsesSourceQuery.MustGet()
				}
				if buf.UsesSteamcmd.IsValue() {
					o.UsesSteamcmd = buf.UsesSteamcmd.MustGet()
				}
				if buf.SteamAppID.IsValue() {
					o.SteamAppID = buf.SteamAppID.MustGet()
				}
				if buf.RequiresSteamGameServerLoginToken.IsValue() {
					o.RequiresSteamGameServerLoginToken = buf.RequiresSteamGameServerLoginToken.MustGet()
				}
				if buf.LinuxSupport.IsValue() {
					o.LinuxSupport = buf.LinuxSupport.MustGet()
				}
				if buf.LinuxStopCommand.IsValue() {
					o.LinuxStopCommand = buf.LinuxStopCommand.MustGet()
				}
				if buf.LinuxInstallCommand.IsValue() {
					o.LinuxInstallCommand = buf.LinuxInstallCommand.MustGet()
				}
				if buf.LinuxInstallCommandType.IsValue() {
					o.LinuxInstallCommandType = buf.LinuxInstallCommandType.MustGet()
				}
				if buf.LinuxUpdateCommand.IsValue() {
					o.LinuxUpdateCommand = buf.LinuxUpdateCommand.MustGet()
				}
				if buf.LinuxUpdateCommandType.IsValue() {
					o.LinuxUpdateCommandType = buf.LinuxUpdateCommandType.MustGet()
				}
				if buf.LinuxWorkingDirectory.IsValue() {
					o.LinuxWorkingDirectory = buf.LinuxWorkingDirectory.MustGet()
				}
				if buf.WindowsSupport.IsValue() {
					o.WindowsSupport = buf.WindowsSupport.MustGet()
				}
				if buf.WindowsStopCommand.IsValue() {
					o.WindowsStopCommand = buf.WindowsStopCommand.MustGet()
				}
				if buf.WindowsInstallCommand.IsValue() {
					o.WindowsInstallCommand = buf.WindowsInstallCommand.MustGet()
				}
				if buf.WindowsInstallCommandType.IsValue() {
					o.WindowsInstallCommandType = buf.WindowsInstallCommandType.MustGet()
				}
				if buf.WindowsUpdateCommand.IsValue() {
					o.WindowsUpdateCommand = buf.WindowsUpdateCommand.MustGet()
				}
				if buf.WindowsUpdateCommandType.IsValue() {
					o.WindowsUpdateCommandType = buf.WindowsUpdateCommandType.MustGet()
				}
				if buf.WindowsWorkingDirectory.IsValue() {
					o.WindowsWorkingDirectory = buf.WindowsWorkingDirectory.MustGet()
				}
				if buf.BindsToAllIps.IsValue() {
					o.BindsToAllIps = buf.BindsToAllIps.MustGet()
				}
				if buf.CreatedAt.IsValue() {
					o.CreatedAt = buf.CreatedAt.MustGet()
				}
				if buf.UpdatedAt.IsValue() {
					o.UpdatedAt = buf.UpdatedAt.MustGet()
				}
				if buf.XylonaOfficial.IsValue() {
					o.XylonaOfficial = buf.XylonaOfficial.MustGet()
				}
				o.ConfigSchemas = buf.ConfigSchemas
				o.ServerSoftware = buf.ServerSoftware
				o.LinuxStartArgsTemplate = buf.LinuxStartArgsTemplate
				o.WindowsStartArgsTemplate = buf.WindowsStartArgsTemplate
				if buf.LinuxBaseCommand.IsValue() {
					o.LinuxBaseCommand = buf.LinuxBaseCommand.MustGet()
				}
				if buf.WindowsBaseCommand.IsValue() {
					o.WindowsBaseCommand = buf.WindowsBaseCommand.MustGet()
				}
				if buf.StartArgBlocklist.IsValue() {
					o.StartArgBlocklist = buf.StartArgBlocklist.MustGet()
				}
				if buf.AllowStartArgEditing.IsValue() {
					o.AllowStartArgEditing = buf.AllowStartArgEditing.MustGet()
				}
				if buf.OfficialDefinitionHash.IsValue() {
					o.OfficialDefinitionHash = buf.OfficialDefinitionHash.MustGet()
				}
				if buf.OfficialDefinitionSource.IsValue() {
					o.OfficialDefinitionSource = buf.OfficialDefinitionSource.MustGet()
				}
				if buf.OfficialDefinitionSchemaVersion.IsValue() {
					o.OfficialDefinitionSchemaVersion = buf.OfficialDefinitionSchemaVersion.MustGet()
				}
				if buf.OfficialDefinitionDiverged.IsValue() {
					o.OfficialDefinitionDiverged = buf.OfficialDefinitionDiverged.MustGet()
				}
				if buf.DefaultEnvVars.IsValue() {
					o.DefaultEnvVars = buf.DefaultEnvVars.MustGet()
				}
				if buf.LinuxAllowBackups.IsValue() {
					o.LinuxAllowBackups = buf.LinuxAllowBackups.MustGet()
				}
				if buf.WindowsAllowBackups.IsValue() {
					o.WindowsAllowBackups = buf.WindowsAllowBackups.MustGet()
				}
				if buf.ConsoleCommands.IsValue() {
					o.ConsoleCommands = buf.ConsoleCommands.MustGet()
				}
				return o, nil
			}
	}
}

func (o *Game) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "GameServers":
		rels, ok := retrieved.(GameServerSlice)
		if !ok {
			return fmt.Errorf("game cannot load %T as %q", retrieved, name)
		}

		o.R.GameServers = rels
		o.R.Loaded.GameServers = true

		for _, rel := range rels {
			if rel != nil {
				rel.R.Game = o
				rel.R.Loaded.Game = true
			}
		}
		return nil
	default:
		return fmt.Errorf("game has no relationship %q", name)
	}
}

type gamePreloader struct{}

func buildGamePreloader() gamePreloader {
	return gamePreloader{}
}

type gameThenLoader[Q orm.Loadable] struct {
	GameServers func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildGameThenLoader[Q orm.Loadable]() gameThenLoader[Q] {
	type GameServersLoadInterface interface {
		LoadGameServers(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return gameThenLoader[Q]{
		GameServers: thenLoadBuilder[Q](
			"GameServers",
			func(ctx context.Context, exec bob.Executor, retrieved GameServersLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadGameServers(ctx, exec, mods...)
			},
		),
	}
}

// LoadGameServers loads the game's GameServers into the .R struct
func (o *Game) LoadGameServers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.GameServers = nil
	o.R.Loaded.GameServers = false

	related, err := o.GameServers(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Game = o
		rel.R.Loaded.Game = true
	}

	o.R.GameServers = related
	o.R.Loaded.GameServers = true
	return nil
}

// LoadGameServers loads the game's GameServers into the .R struct
func (os GameSlice) LoadGameServers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	gameServers, err := os.GameServers(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.GameServers = nil
		o.R.Loaded.GameServers = true
	}
	// O(N+M) stitch via a map keyed by the join column (key -> []parent; was O(N*M)).
	gameByKey := make(map[string][]*Game, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}

		gameByKey[o.ID] = append(gameByKey[o.ID], o)
	}

	for _, rel := range gameServers {

		owners, ok := gameByKey[rel.GameID]
		if !ok {
			continue
		}

		for _, o := range owners {

			rel.R.Game = o
			rel.R.Loaded.Game = true

			o.R.GameServers = append(o.R.GameServers, rel)

		}
	}

	return nil
}

// gameC is where relationship counts are stored.
type gameC struct {
	GameServers *int64
}

// PreloadCount sets a count in the C struct by name
func (o *Game) PreloadCount(name string, count int64) error {
	if o == nil {
		return nil
	}

	switch name {
	case "GameServers":
		o.C.GameServers = &count
	}
	return nil
}

type gameCountPreloader struct {
	GameServers func(...bob.Mod[*dialect.SelectQuery]) sqlite.Preloader
}

func buildGameCountPreloader() gameCountPreloader {
	return gameCountPreloader{
		GameServers: func(mods ...bob.Mod[*dialect.SelectQuery]) sqlite.Preloader {
			return countPreloader[*Game]("GameServers", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Games.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(sqlite.Raw("count(*)")),

					sm.From(GameServers.NameAsExpr()),
					sm.Where(sqlite.Quote(GameServers.Alias(), "game_id").EQ(sqlite.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return sqlite.Group(sqlite.Select(subqueryMods...).Expression)
			})
		},
	}
}

type gameCountThenLoader[Q orm.Loadable] struct {
	GameServers func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildGameCountThenLoader[Q orm.Loadable]() gameCountThenLoader[Q] {
	type GameServersCountInterface interface {
		LoadCountGameServers(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return gameCountThenLoader[Q]{
		GameServers: countThenLoadBuilder[Q](
			"GameServers",
			func(ctx context.Context, exec bob.Executor, retrieved GameServersCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountGameServers(ctx, exec, mods...)
			},
		),
	}
}

// LoadCountGameServers loads the count of GameServers into the C struct
func (o *Game) LoadCountGameServers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.GameServers(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.GameServers = &count
	return nil
}

// LoadCountGameServers loads the count of GameServers for a slice in a single batch query
func (os GameSlice) LoadCountGameServers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs
	PKArgSlice := make([]bob.Expression, 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		PKArgSlice = append(PKArgSlice, sqlite.Arg(o.ID))
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			GameServers.Columns.GameID.As("id"),
			sqlite.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(GameServers.NameAsExpr()),

		// WHERE fk IN (parent PKs) — psql single-column FK uses `= ANY(array)` (see PKArgExpr above)
		sm.Where(GameServers.Columns.GameID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(GameServers.Columns.GameID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		sqlite.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.GameServers = &count
	}

	return nil
}

type gameJoins[Q dialect.Joinable] struct {
	typ         string
	GameServers modAs[Q, gameServerColumns]
}

func (j gameJoins[Q]) aliasedAs(alias string) gameJoins[Q] {
	return buildGameJoins[Q](buildGameColumns(alias), j.typ)
}

func buildGameJoins[Q dialect.Joinable](cols gameColumns, typ string) gameJoins[Q] {
	return gameJoins[Q]{
		typ: typ,
		GameServers: modAs[Q, gameServerColumns]{
			c: GameServers.Columns,
			f: func(to gameServerColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, GameServers.NameExpr().As(to.Alias())).On(
						to.GameID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
