// Code generated by BobGen sqlite v0.22.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/im"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// GameServer is an object representing the database table.
type GameServer struct {
	ID                        string    `db:"id,pk" `
	UserID                    string    `db:"user_id" `
	Name                      string    `db:"name" `
	GameID                    string    `db:"game_id" `
	StartCommand              string    `db:"start_command" `
	Status                    string    `db:"status" `
	SetPlayers                int64     `db:"set_players" `
	MaxPlayers                int64     `db:"max_players" `
	Map                       string    `db:"map" `
	IP                        string    `db:"ip" `
	Port                      int64     `db:"port" `
	QueryPort                 int64     `db:"query_port" `
	Directory                 string    `db:"directory" `
	MaxMemoryMB               int64     `db:"max_memory_mb" `
	BackupsEnabled            bool      `db:"backups_enabled" `
	SteamGameServerLoginToken string    `db:"steam_game_server_login_token" `
	BackupDirectory           string    `db:"backup_directory" `
	MaxBackups                int64     `db:"max_backups" `
	CreatedAt                 time.Time `db:"created_at" `
	UpdatedAt                 time.Time `db:"updated_at" `

	R gameServerR `db:"-" `
}

// GameServerSlice is an alias for a slice of pointers to GameServer.
// This should almost always be used instead of []*GameServer.
type GameServerSlice []*GameServer

// GameServers contains methods to work with the game_server table
var GameServers = sqlite.NewTablex[*GameServer, GameServerSlice, *GameServerSetter]("", "game_server")

// GameServersQuery is a query on the game_server table
type GameServersQuery = *sqlite.ViewQuery[*GameServer, GameServerSlice]

// GameServersStmt is a prepared statment on game_server
type GameServersStmt = bob.QueryStmt[*GameServer, GameServerSlice]

// gameServerR is where relationships are stored.
type gameServerR struct {
	IP   *IP      // fk_game_server_0
	Game *Game    // fk_game_server_1
	User *User    // fk_game_server_2
	Logs LogSlice // fk_log_0
}

// GameServerSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type GameServerSetter struct {
	ID                        omit.Val[string]    `db:"id,pk"`
	UserID                    omit.Val[string]    `db:"user_id"`
	Name                      omit.Val[string]    `db:"name"`
	GameID                    omit.Val[string]    `db:"game_id"`
	StartCommand              omit.Val[string]    `db:"start_command"`
	Status                    omit.Val[string]    `db:"status"`
	SetPlayers                omit.Val[int64]     `db:"set_players"`
	MaxPlayers                omit.Val[int64]     `db:"max_players"`
	Map                       omit.Val[string]    `db:"map"`
	IP                        omit.Val[string]    `db:"ip"`
	Port                      omit.Val[int64]     `db:"port"`
	QueryPort                 omit.Val[int64]     `db:"query_port"`
	Directory                 omit.Val[string]    `db:"directory"`
	MaxMemoryMB               omit.Val[int64]     `db:"max_memory_mb"`
	BackupsEnabled            omit.Val[bool]      `db:"backups_enabled"`
	SteamGameServerLoginToken omit.Val[string]    `db:"steam_game_server_login_token"`
	BackupDirectory           omit.Val[string]    `db:"backup_directory"`
	MaxBackups                omit.Val[int64]     `db:"max_backups"`
	CreatedAt                 omit.Val[time.Time] `db:"created_at"`
	UpdatedAt                 omit.Val[time.Time] `db:"updated_at"`
}

func (s GameServerSetter) SetColumns() []string {
	vals := make([]string, 0, 20)
	if !s.ID.IsUnset() {
		vals = append(vals, "id")
	}

	if !s.UserID.IsUnset() {
		vals = append(vals, "user_id")
	}

	if !s.Name.IsUnset() {
		vals = append(vals, "name")
	}

	if !s.GameID.IsUnset() {
		vals = append(vals, "game_id")
	}

	if !s.StartCommand.IsUnset() {
		vals = append(vals, "start_command")
	}

	if !s.Status.IsUnset() {
		vals = append(vals, "status")
	}

	if !s.SetPlayers.IsUnset() {
		vals = append(vals, "set_players")
	}

	if !s.MaxPlayers.IsUnset() {
		vals = append(vals, "max_players")
	}

	if !s.Map.IsUnset() {
		vals = append(vals, "map")
	}

	if !s.IP.IsUnset() {
		vals = append(vals, "ip")
	}

	if !s.Port.IsUnset() {
		vals = append(vals, "port")
	}

	if !s.QueryPort.IsUnset() {
		vals = append(vals, "query_port")
	}

	if !s.Directory.IsUnset() {
		vals = append(vals, "directory")
	}

	if !s.MaxMemoryMB.IsUnset() {
		vals = append(vals, "max_memory_mb")
	}

	if !s.BackupsEnabled.IsUnset() {
		vals = append(vals, "backups_enabled")
	}

	if !s.SteamGameServerLoginToken.IsUnset() {
		vals = append(vals, "steam_game_server_login_token")
	}

	if !s.BackupDirectory.IsUnset() {
		vals = append(vals, "backup_directory")
	}

	if !s.MaxBackups.IsUnset() {
		vals = append(vals, "max_backups")
	}

	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}

	if !s.UpdatedAt.IsUnset() {
		vals = append(vals, "updated_at")
	}

	return vals
}

func (s GameServerSetter) Overwrite(t *GameServer) {
	if !s.ID.IsUnset() {
		t.ID, _ = s.ID.Get()
	}
	if !s.UserID.IsUnset() {
		t.UserID, _ = s.UserID.Get()
	}
	if !s.Name.IsUnset() {
		t.Name, _ = s.Name.Get()
	}
	if !s.GameID.IsUnset() {
		t.GameID, _ = s.GameID.Get()
	}
	if !s.StartCommand.IsUnset() {
		t.StartCommand, _ = s.StartCommand.Get()
	}
	if !s.Status.IsUnset() {
		t.Status, _ = s.Status.Get()
	}
	if !s.SetPlayers.IsUnset() {
		t.SetPlayers, _ = s.SetPlayers.Get()
	}
	if !s.MaxPlayers.IsUnset() {
		t.MaxPlayers, _ = s.MaxPlayers.Get()
	}
	if !s.Map.IsUnset() {
		t.Map, _ = s.Map.Get()
	}
	if !s.IP.IsUnset() {
		t.IP, _ = s.IP.Get()
	}
	if !s.Port.IsUnset() {
		t.Port, _ = s.Port.Get()
	}
	if !s.QueryPort.IsUnset() {
		t.QueryPort, _ = s.QueryPort.Get()
	}
	if !s.Directory.IsUnset() {
		t.Directory, _ = s.Directory.Get()
	}
	if !s.MaxMemoryMB.IsUnset() {
		t.MaxMemoryMB, _ = s.MaxMemoryMB.Get()
	}
	if !s.BackupsEnabled.IsUnset() {
		t.BackupsEnabled, _ = s.BackupsEnabled.Get()
	}
	if !s.SteamGameServerLoginToken.IsUnset() {
		t.SteamGameServerLoginToken, _ = s.SteamGameServerLoginToken.Get()
	}
	if !s.BackupDirectory.IsUnset() {
		t.BackupDirectory, _ = s.BackupDirectory.Get()
	}
	if !s.MaxBackups.IsUnset() {
		t.MaxBackups, _ = s.MaxBackups.Get()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt, _ = s.CreatedAt.Get()
	}
	if !s.UpdatedAt.IsUnset() {
		t.UpdatedAt, _ = s.UpdatedAt.Get()
	}
}

func (s GameServerSetter) Apply(q *dialect.UpdateQuery) {
	if !s.ID.IsUnset() {
		um.Set("id").ToArg(s.ID).Apply(q)
	}
	if !s.UserID.IsUnset() {
		um.Set("user_id").ToArg(s.UserID).Apply(q)
	}
	if !s.Name.IsUnset() {
		um.Set("name").ToArg(s.Name).Apply(q)
	}
	if !s.GameID.IsUnset() {
		um.Set("game_id").ToArg(s.GameID).Apply(q)
	}
	if !s.StartCommand.IsUnset() {
		um.Set("start_command").ToArg(s.StartCommand).Apply(q)
	}
	if !s.Status.IsUnset() {
		um.Set("status").ToArg(s.Status).Apply(q)
	}
	if !s.SetPlayers.IsUnset() {
		um.Set("set_players").ToArg(s.SetPlayers).Apply(q)
	}
	if !s.MaxPlayers.IsUnset() {
		um.Set("max_players").ToArg(s.MaxPlayers).Apply(q)
	}
	if !s.Map.IsUnset() {
		um.Set("map").ToArg(s.Map).Apply(q)
	}
	if !s.IP.IsUnset() {
		um.Set("ip").ToArg(s.IP).Apply(q)
	}
	if !s.Port.IsUnset() {
		um.Set("port").ToArg(s.Port).Apply(q)
	}
	if !s.QueryPort.IsUnset() {
		um.Set("query_port").ToArg(s.QueryPort).Apply(q)
	}
	if !s.Directory.IsUnset() {
		um.Set("directory").ToArg(s.Directory).Apply(q)
	}
	if !s.MaxMemoryMB.IsUnset() {
		um.Set("max_memory_mb").ToArg(s.MaxMemoryMB).Apply(q)
	}
	if !s.BackupsEnabled.IsUnset() {
		um.Set("backups_enabled").ToArg(s.BackupsEnabled).Apply(q)
	}
	if !s.SteamGameServerLoginToken.IsUnset() {
		um.Set("steam_game_server_login_token").ToArg(s.SteamGameServerLoginToken).Apply(q)
	}
	if !s.BackupDirectory.IsUnset() {
		um.Set("backup_directory").ToArg(s.BackupDirectory).Apply(q)
	}
	if !s.MaxBackups.IsUnset() {
		um.Set("max_backups").ToArg(s.MaxBackups).Apply(q)
	}
	if !s.CreatedAt.IsUnset() {
		um.Set("created_at").ToArg(s.CreatedAt).Apply(q)
	}
	if !s.UpdatedAt.IsUnset() {
		um.Set("updated_at").ToArg(s.UpdatedAt).Apply(q)
	}
}

func (s GameServerSetter) Insert() bob.Mod[*dialect.InsertQuery] {
	vals := make([]bob.Expression, 0, 20)
	if !s.ID.IsUnset() {
		vals = append(vals, sqlite.Arg(s.ID))
	}

	if !s.UserID.IsUnset() {
		vals = append(vals, sqlite.Arg(s.UserID))
	}

	if !s.Name.IsUnset() {
		vals = append(vals, sqlite.Arg(s.Name))
	}

	if !s.GameID.IsUnset() {
		vals = append(vals, sqlite.Arg(s.GameID))
	}

	if !s.StartCommand.IsUnset() {
		vals = append(vals, sqlite.Arg(s.StartCommand))
	}

	if !s.Status.IsUnset() {
		vals = append(vals, sqlite.Arg(s.Status))
	}

	if !s.SetPlayers.IsUnset() {
		vals = append(vals, sqlite.Arg(s.SetPlayers))
	}

	if !s.MaxPlayers.IsUnset() {
		vals = append(vals, sqlite.Arg(s.MaxPlayers))
	}

	if !s.Map.IsUnset() {
		vals = append(vals, sqlite.Arg(s.Map))
	}

	if !s.IP.IsUnset() {
		vals = append(vals, sqlite.Arg(s.IP))
	}

	if !s.Port.IsUnset() {
		vals = append(vals, sqlite.Arg(s.Port))
	}

	if !s.QueryPort.IsUnset() {
		vals = append(vals, sqlite.Arg(s.QueryPort))
	}

	if !s.Directory.IsUnset() {
		vals = append(vals, sqlite.Arg(s.Directory))
	}

	if !s.MaxMemoryMB.IsUnset() {
		vals = append(vals, sqlite.Arg(s.MaxMemoryMB))
	}

	if !s.BackupsEnabled.IsUnset() {
		vals = append(vals, sqlite.Arg(s.BackupsEnabled))
	}

	if !s.SteamGameServerLoginToken.IsUnset() {
		vals = append(vals, sqlite.Arg(s.SteamGameServerLoginToken))
	}

	if !s.BackupDirectory.IsUnset() {
		vals = append(vals, sqlite.Arg(s.BackupDirectory))
	}

	if !s.MaxBackups.IsUnset() {
		vals = append(vals, sqlite.Arg(s.MaxBackups))
	}

	if !s.CreatedAt.IsUnset() {
		vals = append(vals, sqlite.Arg(s.CreatedAt))
	}

	if !s.UpdatedAt.IsUnset() {
		vals = append(vals, sqlite.Arg(s.UpdatedAt))
	}

	return im.Values(vals...)
}

type gameServerColumnNames struct {
	ID                        string
	UserID                    string
	Name                      string
	GameID                    string
	StartCommand              string
	Status                    string
	SetPlayers                string
	MaxPlayers                string
	Map                       string
	IP                        string
	Port                      string
	QueryPort                 string
	Directory                 string
	MaxMemoryMB               string
	BackupsEnabled            string
	SteamGameServerLoginToken string
	BackupDirectory           string
	MaxBackups                string
	CreatedAt                 string
	UpdatedAt                 string
}

type gameServerRelationshipJoins[Q dialect.Joinable] struct {
	IP   bob.Mod[Q]
	Game bob.Mod[Q]
	User bob.Mod[Q]
	Logs bob.Mod[Q]
}

func buildgameServerRelationshipJoins[Q dialect.Joinable](ctx context.Context, typ string) gameServerRelationshipJoins[Q] {
	return gameServerRelationshipJoins[Q]{
		IP:   gameServersJoinIP[Q](ctx, typ),
		Game: gameServersJoinGame[Q](ctx, typ),
		User: gameServersJoinUser[Q](ctx, typ),
		Logs: gameServersJoinLogs[Q](ctx, typ),
	}
}

func gameServersJoin[Q dialect.Joinable](ctx context.Context) joinSet[gameServerRelationshipJoins[Q]] {
	return joinSet[gameServerRelationshipJoins[Q]]{
		InnerJoin: buildgameServerRelationshipJoins[Q](ctx, clause.InnerJoin),
		LeftJoin:  buildgameServerRelationshipJoins[Q](ctx, clause.LeftJoin),
		RightJoin: buildgameServerRelationshipJoins[Q](ctx, clause.RightJoin),
	}
}

var GameServerColumns = struct {
	ID                        sqlite.Expression
	UserID                    sqlite.Expression
	Name                      sqlite.Expression
	GameID                    sqlite.Expression
	StartCommand              sqlite.Expression
	Status                    sqlite.Expression
	SetPlayers                sqlite.Expression
	MaxPlayers                sqlite.Expression
	Map                       sqlite.Expression
	IP                        sqlite.Expression
	Port                      sqlite.Expression
	QueryPort                 sqlite.Expression
	Directory                 sqlite.Expression
	MaxMemoryMB               sqlite.Expression
	BackupsEnabled            sqlite.Expression
	SteamGameServerLoginToken sqlite.Expression
	BackupDirectory           sqlite.Expression
	MaxBackups                sqlite.Expression
	CreatedAt                 sqlite.Expression
	UpdatedAt                 sqlite.Expression
}{
	ID:                        sqlite.Quote("game_server", "id"),
	UserID:                    sqlite.Quote("game_server", "user_id"),
	Name:                      sqlite.Quote("game_server", "name"),
	GameID:                    sqlite.Quote("game_server", "game_id"),
	StartCommand:              sqlite.Quote("game_server", "start_command"),
	Status:                    sqlite.Quote("game_server", "status"),
	SetPlayers:                sqlite.Quote("game_server", "set_players"),
	MaxPlayers:                sqlite.Quote("game_server", "max_players"),
	Map:                       sqlite.Quote("game_server", "map"),
	IP:                        sqlite.Quote("game_server", "ip"),
	Port:                      sqlite.Quote("game_server", "port"),
	QueryPort:                 sqlite.Quote("game_server", "query_port"),
	Directory:                 sqlite.Quote("game_server", "directory"),
	MaxMemoryMB:               sqlite.Quote("game_server", "max_memory_mb"),
	BackupsEnabled:            sqlite.Quote("game_server", "backups_enabled"),
	SteamGameServerLoginToken: sqlite.Quote("game_server", "steam_game_server_login_token"),
	BackupDirectory:           sqlite.Quote("game_server", "backup_directory"),
	MaxBackups:                sqlite.Quote("game_server", "max_backups"),
	CreatedAt:                 sqlite.Quote("game_server", "created_at"),
	UpdatedAt:                 sqlite.Quote("game_server", "updated_at"),
}

type gameServerWhere[Q sqlite.Filterable] struct {
	ID                        sqlite.WhereMod[Q, string]
	UserID                    sqlite.WhereMod[Q, string]
	Name                      sqlite.WhereMod[Q, string]
	GameID                    sqlite.WhereMod[Q, string]
	StartCommand              sqlite.WhereMod[Q, string]
	Status                    sqlite.WhereMod[Q, string]
	SetPlayers                sqlite.WhereMod[Q, int64]
	MaxPlayers                sqlite.WhereMod[Q, int64]
	Map                       sqlite.WhereMod[Q, string]
	IP                        sqlite.WhereMod[Q, string]
	Port                      sqlite.WhereMod[Q, int64]
	QueryPort                 sqlite.WhereMod[Q, int64]
	Directory                 sqlite.WhereMod[Q, string]
	MaxMemoryMB               sqlite.WhereMod[Q, int64]
	BackupsEnabled            sqlite.WhereMod[Q, bool]
	SteamGameServerLoginToken sqlite.WhereMod[Q, string]
	BackupDirectory           sqlite.WhereMod[Q, string]
	MaxBackups                sqlite.WhereMod[Q, int64]
	CreatedAt                 sqlite.WhereMod[Q, time.Time]
	UpdatedAt                 sqlite.WhereMod[Q, time.Time]
}

func GameServerWhere[Q sqlite.Filterable]() gameServerWhere[Q] {
	return gameServerWhere[Q]{
		ID:                        sqlite.Where[Q, string](GameServerColumns.ID),
		UserID:                    sqlite.Where[Q, string](GameServerColumns.UserID),
		Name:                      sqlite.Where[Q, string](GameServerColumns.Name),
		GameID:                    sqlite.Where[Q, string](GameServerColumns.GameID),
		StartCommand:              sqlite.Where[Q, string](GameServerColumns.StartCommand),
		Status:                    sqlite.Where[Q, string](GameServerColumns.Status),
		SetPlayers:                sqlite.Where[Q, int64](GameServerColumns.SetPlayers),
		MaxPlayers:                sqlite.Where[Q, int64](GameServerColumns.MaxPlayers),
		Map:                       sqlite.Where[Q, string](GameServerColumns.Map),
		IP:                        sqlite.Where[Q, string](GameServerColumns.IP),
		Port:                      sqlite.Where[Q, int64](GameServerColumns.Port),
		QueryPort:                 sqlite.Where[Q, int64](GameServerColumns.QueryPort),
		Directory:                 sqlite.Where[Q, string](GameServerColumns.Directory),
		MaxMemoryMB:               sqlite.Where[Q, int64](GameServerColumns.MaxMemoryMB),
		BackupsEnabled:            sqlite.Where[Q, bool](GameServerColumns.BackupsEnabled),
		SteamGameServerLoginToken: sqlite.Where[Q, string](GameServerColumns.SteamGameServerLoginToken),
		BackupDirectory:           sqlite.Where[Q, string](GameServerColumns.BackupDirectory),
		MaxBackups:                sqlite.Where[Q, int64](GameServerColumns.MaxBackups),
		CreatedAt:                 sqlite.Where[Q, time.Time](GameServerColumns.CreatedAt),
		UpdatedAt:                 sqlite.Where[Q, time.Time](GameServerColumns.UpdatedAt),
	}
}

// FindGameServer retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindGameServer(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*GameServer, error) {
	if len(cols) == 0 {
		return GameServers.Query(
			ctx, exec,
			SelectWhere.GameServers.ID.EQ(IDPK),
		).One()
	}

	return GameServers.Query(
		ctx, exec,
		SelectWhere.GameServers.ID.EQ(IDPK),
		sm.Columns(GameServers.Columns().Only(cols...)),
	).One()
}

// GameServerExists checks the presence of a single record by primary key
func GameServerExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return GameServers.Query(
		ctx, exec,
		SelectWhere.GameServers.ID.EQ(IDPK),
	).Exists()
}

// PrimaryKeyVals returns the primary key values of the GameServer
func (o *GameServer) PrimaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

// Update uses an executor to update the GameServer
func (o *GameServer) Update(ctx context.Context, exec bob.Executor, s *GameServerSetter) error {
	return GameServers.Update(ctx, exec, s, o)
}

// Delete deletes a single GameServer record with an executor
func (o *GameServer) Delete(ctx context.Context, exec bob.Executor) error {
	return GameServers.Delete(ctx, exec, o)
}

// Reload refreshes the GameServer using the executor
func (o *GameServer) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := GameServers.Query(
		ctx, exec,
		SelectWhere.GameServers.ID.EQ(o.ID),
	).One()
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

func (o GameServerSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals GameServerSetter) error {
	return GameServers.Update(ctx, exec, &vals, o...)
}

func (o GameServerSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	return GameServers.Delete(ctx, exec, o...)
}

func (o GameServerSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	var mods []bob.Mod[*dialect.SelectQuery]

	IDPK := make([]string, len(o))

	for i, o := range o {
		IDPK[i] = o.ID
	}

	mods = append(mods,
		SelectWhere.GameServers.ID.In(IDPK...),
	)

	o2, err := GameServers.Query(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, old := range o {
		for _, new := range o2 {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			*old = *new
			break
		}
	}

	return nil
}

func gameServersJoinIP[Q dialect.Joinable](ctx context.Context, typ string) bob.Mod[Q] {
	return mods.QueryMods[Q]{
		dialect.Join[Q](typ, Ips.Name(ctx)).On(
			IPColumns.Address.EQ(GameServerColumns.IP),
		),
	}
}
func gameServersJoinGame[Q dialect.Joinable](ctx context.Context, typ string) bob.Mod[Q] {
	return mods.QueryMods[Q]{
		dialect.Join[Q](typ, Games.Name(ctx)).On(
			GameColumns.ID.EQ(GameServerColumns.GameID),
		),
	}
}
func gameServersJoinUser[Q dialect.Joinable](ctx context.Context, typ string) bob.Mod[Q] {
	return mods.QueryMods[Q]{
		dialect.Join[Q](typ, Users.Name(ctx)).On(
			UserColumns.ID.EQ(GameServerColumns.UserID),
		),
	}
}
func gameServersJoinLogs[Q dialect.Joinable](ctx context.Context, typ string) bob.Mod[Q] {
	return mods.QueryMods[Q]{
		dialect.Join[Q](typ, Logs.Name(ctx)).On(
			LogColumns.GameServerID.EQ(GameServerColumns.ID),
		),
	}
}

// IP starts a query for related objects on ip
func (o *GameServer) RelatedIP(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) IpsQuery {
	return Ips.Query(ctx, exec, append(mods,
		sm.Where(IPColumns.Address.EQ(sqlite.Arg(o.IP))),
	)...)
}

func (os GameServerSlice) RelatedIP(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) IpsQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = sqlite.ArgGroup(o.IP)
	}

	return Ips.Query(ctx, exec, append(mods,
		sm.Where(sqlite.Group(IPColumns.Address).In(PKArgs...)),
	)...)
}

// Game starts a query for related objects on game
func (o *GameServer) Game(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) GamesQuery {
	return Games.Query(ctx, exec, append(mods,
		sm.Where(GameColumns.ID.EQ(sqlite.Arg(o.GameID))),
	)...)
}

func (os GameServerSlice) Game(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) GamesQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = sqlite.ArgGroup(o.GameID)
	}

	return Games.Query(ctx, exec, append(mods,
		sm.Where(sqlite.Group(GameColumns.ID).In(PKArgs...)),
	)...)
}

// User starts a query for related objects on user
func (o *GameServer) User(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(ctx, exec, append(mods,
		sm.Where(UserColumns.ID.EQ(sqlite.Arg(o.UserID))),
	)...)
}

func (os GameServerSlice) User(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = sqlite.ArgGroup(o.UserID)
	}

	return Users.Query(ctx, exec, append(mods,
		sm.Where(sqlite.Group(UserColumns.ID).In(PKArgs...)),
	)...)
}

// Logs starts a query for related objects on log
func (o *GameServer) Logs(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) LogsQuery {
	return Logs.Query(ctx, exec, append(mods,
		sm.Where(LogColumns.GameServerID.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os GameServerSlice) Logs(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) LogsQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = sqlite.ArgGroup(o.ID)
	}

	return Logs.Query(ctx, exec, append(mods,
		sm.Where(sqlite.Group(LogColumns.GameServerID).In(PKArgs...)),
	)...)
}

func (o *GameServer) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "IP":
		rel, ok := retrieved.(*IP)
		if !ok {
			return fmt.Errorf("gameServer cannot load %T as %q", retrieved, name)
		}

		o.R.IP = rel

		if rel != nil {
			rel.R.GameServers = GameServerSlice{o}
		}
		return nil
	case "Game":
		rel, ok := retrieved.(*Game)
		if !ok {
			return fmt.Errorf("gameServer cannot load %T as %q", retrieved, name)
		}

		o.R.Game = rel

		if rel != nil {
			rel.R.GameServers = GameServerSlice{o}
		}
		return nil
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("gameServer cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.GameServers = GameServerSlice{o}
		}
		return nil
	case "Logs":
		rels, ok := retrieved.(LogSlice)
		if !ok {
			return fmt.Errorf("gameServer cannot load %T as %q", retrieved, name)
		}

		o.R.Logs = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.GameServer = o
			}
		}
		return nil
	default:
		return fmt.Errorf("gameServer has no relationship %q", name)
	}
}

func PreloadGameServerIP(opts ...sqlite.PreloadOption) sqlite.Preloader {
	return sqlite.Preload[*IP, IPSlice](orm.Relationship{
		Name: "IP",
		Sides: []orm.RelSide{
			{
				From: "game_server",
				To:   TableNames.Ips,
				ToExpr: func(ctx context.Context) bob.Expression {
					return Ips.Name(ctx)
				},
				FromColumns: []string{
					ColumnNames.GameServers.IP,
				},
				ToColumns: []string{
					ColumnNames.Ips.Address,
				},
			},
		},
	}, Ips.Columns().Names(), opts...)
}

func ThenLoadGameServerIP(queryMods ...bob.Mod[*dialect.SelectQuery]) sqlite.Loader {
	return sqlite.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadGameServerIP(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load GameServerIP", retrieved)
		}

		err := loader.LoadGameServerIP(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadGameServerIP loads the gameServer's IP into the .R struct
func (o *GameServer) LoadGameServerIP(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.IP = nil

	related, err := o.RelatedIP(ctx, exec, mods...).One()
	if err != nil {
		return err
	}

	related.R.GameServers = GameServerSlice{o}

	o.R.IP = related
	return nil
}

// LoadGameServerIP loads the gameServer's IP into the .R struct
func (os GameServerSlice) LoadGameServerIP(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	ips, err := os.RelatedIP(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range ips {
			if o.IP != rel.Address {
				continue
			}

			rel.R.GameServers = append(rel.R.GameServers, o)

			o.R.IP = rel
			break
		}
	}

	return nil
}

func PreloadGameServerGame(opts ...sqlite.PreloadOption) sqlite.Preloader {
	return sqlite.Preload[*Game, GameSlice](orm.Relationship{
		Name: "Game",
		Sides: []orm.RelSide{
			{
				From: "game_server",
				To:   TableNames.Games,
				ToExpr: func(ctx context.Context) bob.Expression {
					return Games.Name(ctx)
				},
				FromColumns: []string{
					ColumnNames.GameServers.GameID,
				},
				ToColumns: []string{
					ColumnNames.Games.ID,
				},
			},
		},
	}, Games.Columns().Names(), opts...)
}

func ThenLoadGameServerGame(queryMods ...bob.Mod[*dialect.SelectQuery]) sqlite.Loader {
	return sqlite.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadGameServerGame(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load GameServerGame", retrieved)
		}

		err := loader.LoadGameServerGame(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadGameServerGame loads the gameServer's Game into the .R struct
func (o *GameServer) LoadGameServerGame(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Game = nil

	related, err := o.Game(ctx, exec, mods...).One()
	if err != nil {
		return err
	}

	related.R.GameServers = GameServerSlice{o}

	o.R.Game = related
	return nil
}

// LoadGameServerGame loads the gameServer's Game into the .R struct
func (os GameServerSlice) LoadGameServerGame(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	games, err := os.Game(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range games {
			if o.GameID != rel.ID {
				continue
			}

			rel.R.GameServers = append(rel.R.GameServers, o)

			o.R.Game = rel
			break
		}
	}

	return nil
}

func PreloadGameServerUser(opts ...sqlite.PreloadOption) sqlite.Preloader {
	return sqlite.Preload[*User, UserSlice](orm.Relationship{
		Name: "User",
		Sides: []orm.RelSide{
			{
				From: "game_server",
				To:   TableNames.Users,
				ToExpr: func(ctx context.Context) bob.Expression {
					return Users.Name(ctx)
				},
				FromColumns: []string{
					ColumnNames.GameServers.UserID,
				},
				ToColumns: []string{
					ColumnNames.Users.ID,
				},
			},
		},
	}, Users.Columns().Names(), opts...)
}

func ThenLoadGameServerUser(queryMods ...bob.Mod[*dialect.SelectQuery]) sqlite.Loader {
	return sqlite.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadGameServerUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load GameServerUser", retrieved)
		}

		err := loader.LoadGameServerUser(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadGameServerUser loads the gameServer's User into the .R struct
func (o *GameServer) LoadGameServerUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(ctx, exec, mods...).One()
	if err != nil {
		return err
	}

	related.R.GameServers = GameServerSlice{o}

	o.R.User = related
	return nil
}

// LoadGameServerUser loads the gameServer's User into the .R struct
func (os GameServerSlice) LoadGameServerUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range users {
			if o.UserID != rel.ID {
				continue
			}

			rel.R.GameServers = append(rel.R.GameServers, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

func ThenLoadGameServerLogs(queryMods ...bob.Mod[*dialect.SelectQuery]) sqlite.Loader {
	return sqlite.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadGameServerLogs(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load GameServerLogs", retrieved)
		}

		err := loader.LoadGameServerLogs(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadGameServerLogs loads the gameServer's Logs into the .R struct
func (o *GameServer) LoadGameServerLogs(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Logs = nil

	related, err := o.Logs(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.GameServer = o
	}

	o.R.Logs = related
	return nil
}

// LoadGameServerLogs loads the gameServer's Logs into the .R struct
func (os GameServerSlice) LoadGameServerLogs(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	logs, err := os.Logs(ctx, exec, mods...).All()
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.Logs = nil
	}

	for _, o := range os {
		for _, rel := range logs {
			if o.ID != rel.GameServerID.GetOrZero() {
				continue
			}

			rel.R.GameServer = o

			o.R.Logs = append(o.R.Logs, rel)
		}
	}

	return nil
}

func attachGameServerIP0(ctx context.Context, exec bob.Executor, gameServer0 *GameServer, ip1 *IP) error {
	setter := &GameServerSetter{
		IP: omit.From(ip1.Address),
	}

	err := GameServers.Update(ctx, exec, setter, gameServer0)
	if err != nil {
		return fmt.Errorf("attachGameServerIP0: %w", err)
	}

	return nil
}

func (gameServer0 *GameServer) InsertIP(ctx context.Context, exec bob.Executor, related *IPSetter) error {
	ip1, err := Ips.Insert(ctx, exec, related)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	err = attachGameServerIP0(ctx, exec, gameServer0, ip1)
	if err != nil {
		return err
	}

	gameServer0.R.IP = ip1

	ip1.R.GameServers = append(ip1.R.GameServers, gameServer0)

	return nil
}

func (gameServer0 *GameServer) AttachIP(ctx context.Context, exec bob.Executor, ip1 *IP) error {
	var err error

	err = attachGameServerIP0(ctx, exec, gameServer0, ip1)
	if err != nil {
		return err
	}

	gameServer0.R.IP = ip1

	ip1.R.GameServers = append(ip1.R.GameServers, gameServer0)

	return nil
}

func attachGameServerGame0(ctx context.Context, exec bob.Executor, gameServer0 *GameServer, game1 *Game) error {
	setter := &GameServerSetter{
		GameID: omit.From(game1.ID),
	}

	err := GameServers.Update(ctx, exec, setter, gameServer0)
	if err != nil {
		return fmt.Errorf("attachGameServerGame0: %w", err)
	}

	return nil
}

func (gameServer0 *GameServer) InsertGame(ctx context.Context, exec bob.Executor, related *GameSetter) error {
	game1, err := Games.Insert(ctx, exec, related)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	err = attachGameServerGame0(ctx, exec, gameServer0, game1)
	if err != nil {
		return err
	}

	gameServer0.R.Game = game1

	game1.R.GameServers = append(game1.R.GameServers, gameServer0)

	return nil
}

func (gameServer0 *GameServer) AttachGame(ctx context.Context, exec bob.Executor, game1 *Game) error {
	var err error

	err = attachGameServerGame0(ctx, exec, gameServer0, game1)
	if err != nil {
		return err
	}

	gameServer0.R.Game = game1

	game1.R.GameServers = append(game1.R.GameServers, gameServer0)

	return nil
}

func attachGameServerUser0(ctx context.Context, exec bob.Executor, gameServer0 *GameServer, user1 *User) error {
	setter := &GameServerSetter{
		UserID: omit.From(user1.ID),
	}

	err := GameServers.Update(ctx, exec, setter, gameServer0)
	if err != nil {
		return fmt.Errorf("attachGameServerUser0: %w", err)
	}

	return nil
}

func (gameServer0 *GameServer) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	user1, err := Users.Insert(ctx, exec, related)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	err = attachGameServerUser0(ctx, exec, gameServer0, user1)
	if err != nil {
		return err
	}

	gameServer0.R.User = user1

	user1.R.GameServers = append(user1.R.GameServers, gameServer0)

	return nil
}

func (gameServer0 *GameServer) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	err = attachGameServerUser0(ctx, exec, gameServer0, user1)
	if err != nil {
		return err
	}

	gameServer0.R.User = user1

	user1.R.GameServers = append(user1.R.GameServers, gameServer0)

	return nil
}

func insertGameServerLogs0(ctx context.Context, exec bob.Executor, logs1 []*LogSetter, gameServer0 *GameServer) (LogSlice, error) {
	for _, log1 := range logs1 {
		log1.GameServerID = omitnull.From(gameServer0.ID)
	}

	ret, err := Logs.InsertMany(ctx, exec, logs1...)
	if err != nil {
		return ret, fmt.Errorf("insertGameServerLogs0: %w", err)
	}

	return ret, nil
}

func attachGameServerLogs0(ctx context.Context, exec bob.Executor, logs1 LogSlice, gameServer0 *GameServer) error {
	setter := &LogSetter{
		GameServerID: omitnull.From(gameServer0.ID),
	}

	err := Logs.Update(ctx, exec, setter, logs1...)
	if err != nil {
		return fmt.Errorf("attachGameServerLogs0: %w", err)
	}

	return nil
}

func (gameServer0 *GameServer) InsertLogs(ctx context.Context, exec bob.Executor, related ...*LogSetter) error {
	if len(related) == 0 {
		return nil
	}

	log1, err := insertGameServerLogs0(ctx, exec, related, gameServer0)
	if err != nil {
		return err
	}

	gameServer0.R.Logs = append(gameServer0.R.Logs, log1...)

	for _, rel := range log1 {
		rel.R.GameServer = gameServer0
	}

	return nil
}

func (gameServer0 *GameServer) AttachLogs(ctx context.Context, exec bob.Executor, related ...*Log) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	log1 := LogSlice(related)

	err = attachGameServerLogs0(ctx, exec, log1, gameServer0)
	if err != nil {
		return err
	}

	gameServer0.R.Logs = append(gameServer0.R.Logs, log1...)

	for _, rel := range related {
		rel.R.GameServer = gameServer0
	}

	return nil
}
