// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// GameServerMetricsHistory is an object representing the database table.
type GameServerMetricsHistory struct {
	ID              string    `db:"id,pk" `
	GameServerID    string    `db:"game_server_id" `
	CPUPercent      float64   `db:"cpu_percent" `
	MemoryBytes     int64     `db:"memory_bytes" `
	MemoryPercent   float64   `db:"memory_percent" `
	DiskUsageBytes  int64     `db:"disk_usage_bytes" `
	IoReadRate      float64   `db:"io_read_rate" `
	IoWriteRate     float64   `db:"io_write_rate" `
	ConnectionCount int64     `db:"connection_count" `
	PlayerCount     int64     `db:"player_count" `
	RecordedAt      time.Time `db:"recorded_at" `

	R gameServerMetricsHistoryR `db:"-" `
}

// GameServerMetricsHistorySlice is an alias for a slice of pointers to GameServerMetricsHistory.
// This should almost always be used instead of []*GameServerMetricsHistory.
type GameServerMetricsHistorySlice []*GameServerMetricsHistory

// GameServerMetricsHistories contains methods to work with the game_server_metrics_history table
var GameServerMetricsHistories = sqlite.NewTablex[*GameServerMetricsHistory, GameServerMetricsHistorySlice, *GameServerMetricsHistorySetter]("", "game_server_metrics_history", buildGameServerMetricsHistoryColumns("game_server_metrics_history"))

// GameServerMetricsHistoriesQuery is a query on the game_server_metrics_history table
type GameServerMetricsHistoriesQuery = *sqlite.ViewQuery[*GameServerMetricsHistory, GameServerMetricsHistorySlice]

// gameServerMetricsHistoryR is where relationships are stored.
type gameServerMetricsHistoryR struct {
	GameServer *GameServer // fk_game_server_metrics_history_0
}

func buildGameServerMetricsHistoryColumns(alias string) gameServerMetricsHistoryColumns {
	return gameServerMetricsHistoryColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "game_server_id", "cpu_percent", "memory_bytes", "memory_percent", "disk_usage_bytes", "io_read_rate", "io_write_rate", "connection_count", "player_count", "recorded_at",
		).WithParent("game_server_metrics_history"),
		tableAlias:      alias,
		ID:              sqlite.Quote(alias, "id"),
		GameServerID:    sqlite.Quote(alias, "game_server_id"),
		CPUPercent:      sqlite.Quote(alias, "cpu_percent"),
		MemoryBytes:     sqlite.Quote(alias, "memory_bytes"),
		MemoryPercent:   sqlite.Quote(alias, "memory_percent"),
		DiskUsageBytes:  sqlite.Quote(alias, "disk_usage_bytes"),
		IoReadRate:      sqlite.Quote(alias, "io_read_rate"),
		IoWriteRate:     sqlite.Quote(alias, "io_write_rate"),
		ConnectionCount: sqlite.Quote(alias, "connection_count"),
		PlayerCount:     sqlite.Quote(alias, "player_count"),
		RecordedAt:      sqlite.Quote(alias, "recorded_at"),
	}
}

type gameServerMetricsHistoryColumns struct {
	expr.ColumnsExpr
	tableAlias      string
	ID              sqlite.Expression
	GameServerID    sqlite.Expression
	CPUPercent      sqlite.Expression
	MemoryBytes     sqlite.Expression
	MemoryPercent   sqlite.Expression
	DiskUsageBytes  sqlite.Expression
	IoReadRate      sqlite.Expression
	IoWriteRate     sqlite.Expression
	ConnectionCount sqlite.Expression
	PlayerCount     sqlite.Expression
	RecordedAt      sqlite.Expression
}

func (c gameServerMetricsHistoryColumns) Alias() string {
	return c.tableAlias
}

func (gameServerMetricsHistoryColumns) AliasedAs(alias string) gameServerMetricsHistoryColumns {
	return buildGameServerMetricsHistoryColumns(alias)
}

// GameServerMetricsHistorySetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type GameServerMetricsHistorySetter struct {
	ID              omit.Val[string]    `db:"id,pk" `
	GameServerID    omit.Val[string]    `db:"game_server_id" `
	CPUPercent      omit.Val[float64]   `db:"cpu_percent" `
	MemoryBytes     omit.Val[int64]     `db:"memory_bytes" `
	MemoryPercent   omit.Val[float64]   `db:"memory_percent" `
	DiskUsageBytes  omit.Val[int64]     `db:"disk_usage_bytes" `
	IoReadRate      omit.Val[float64]   `db:"io_read_rate" `
	IoWriteRate     omit.Val[float64]   `db:"io_write_rate" `
	ConnectionCount omit.Val[int64]     `db:"connection_count" `
	PlayerCount     omit.Val[int64]     `db:"player_count" `
	RecordedAt      omit.Val[time.Time] `db:"recorded_at" `
}

func (s GameServerMetricsHistorySetter) SetColumns() []string {
	vals := make([]string, 0, 11)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.GameServerID.IsValue() {
		vals = append(vals, "game_server_id")
	}
	if s.CPUPercent.IsValue() {
		vals = append(vals, "cpu_percent")
	}
	if s.MemoryBytes.IsValue() {
		vals = append(vals, "memory_bytes")
	}
	if s.MemoryPercent.IsValue() {
		vals = append(vals, "memory_percent")
	}
	if s.DiskUsageBytes.IsValue() {
		vals = append(vals, "disk_usage_bytes")
	}
	if s.IoReadRate.IsValue() {
		vals = append(vals, "io_read_rate")
	}
	if s.IoWriteRate.IsValue() {
		vals = append(vals, "io_write_rate")
	}
	if s.ConnectionCount.IsValue() {
		vals = append(vals, "connection_count")
	}
	if s.PlayerCount.IsValue() {
		vals = append(vals, "player_count")
	}
	if s.RecordedAt.IsValue() {
		vals = append(vals, "recorded_at")
	}
	return vals
}

func (s GameServerMetricsHistorySetter) Overwrite(t *GameServerMetricsHistory) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.GameServerID.IsValue() {
		t.GameServerID = s.GameServerID.MustGet()
	}
	if s.CPUPercent.IsValue() {
		t.CPUPercent = s.CPUPercent.MustGet()
	}
	if s.MemoryBytes.IsValue() {
		t.MemoryBytes = s.MemoryBytes.MustGet()
	}
	if s.MemoryPercent.IsValue() {
		t.MemoryPercent = s.MemoryPercent.MustGet()
	}
	if s.DiskUsageBytes.IsValue() {
		t.DiskUsageBytes = s.DiskUsageBytes.MustGet()
	}
	if s.IoReadRate.IsValue() {
		t.IoReadRate = s.IoReadRate.MustGet()
	}
	if s.IoWriteRate.IsValue() {
		t.IoWriteRate = s.IoWriteRate.MustGet()
	}
	if s.ConnectionCount.IsValue() {
		t.ConnectionCount = s.ConnectionCount.MustGet()
	}
	if s.PlayerCount.IsValue() {
		t.PlayerCount = s.PlayerCount.MustGet()
	}
	if s.RecordedAt.IsValue() {
		t.RecordedAt = s.RecordedAt.MustGet()
	}
}

func (s *GameServerMetricsHistorySetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return GameServerMetricsHistories.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 0, 11)
		if s.ID.IsValue() {
			vals = append(vals, sqlite.Arg(s.ID.MustGet()))
		}

		if s.GameServerID.IsValue() {
			vals = append(vals, sqlite.Arg(s.GameServerID.MustGet()))
		}

		if s.CPUPercent.IsValue() {
			vals = append(vals, sqlite.Arg(s.CPUPercent.MustGet()))
		}

		if s.MemoryBytes.IsValue() {
			vals = append(vals, sqlite.Arg(s.MemoryBytes.MustGet()))
		}

		if s.MemoryPercent.IsValue() {
			vals = append(vals, sqlite.Arg(s.MemoryPercent.MustGet()))
		}

		if s.DiskUsageBytes.IsValue() {
			vals = append(vals, sqlite.Arg(s.DiskUsageBytes.MustGet()))
		}

		if s.IoReadRate.IsValue() {
			vals = append(vals, sqlite.Arg(s.IoReadRate.MustGet()))
		}

		if s.IoWriteRate.IsValue() {
			vals = append(vals, sqlite.Arg(s.IoWriteRate.MustGet()))
		}

		if s.ConnectionCount.IsValue() {
			vals = append(vals, sqlite.Arg(s.ConnectionCount.MustGet()))
		}

		if s.PlayerCount.IsValue() {
			vals = append(vals, sqlite.Arg(s.PlayerCount.MustGet()))
		}

		if s.RecordedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.RecordedAt.MustGet()))
		}

		if len(vals) == 0 {
			vals = append(vals, sqlite.Arg(nil))
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s GameServerMetricsHistorySetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s GameServerMetricsHistorySetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 11)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.GameServerID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "game_server_id")...),
			sqlite.Arg(s.GameServerID),
		}})
	}

	if s.CPUPercent.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "cpu_percent")...),
			sqlite.Arg(s.CPUPercent),
		}})
	}

	if s.MemoryBytes.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "memory_bytes")...),
			sqlite.Arg(s.MemoryBytes),
		}})
	}

	if s.MemoryPercent.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "memory_percent")...),
			sqlite.Arg(s.MemoryPercent),
		}})
	}

	if s.DiskUsageBytes.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "disk_usage_bytes")...),
			sqlite.Arg(s.DiskUsageBytes),
		}})
	}

	if s.IoReadRate.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "io_read_rate")...),
			sqlite.Arg(s.IoReadRate),
		}})
	}

	if s.IoWriteRate.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "io_write_rate")...),
			sqlite.Arg(s.IoWriteRate),
		}})
	}

	if s.ConnectionCount.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "connection_count")...),
			sqlite.Arg(s.ConnectionCount),
		}})
	}

	if s.PlayerCount.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "player_count")...),
			sqlite.Arg(s.PlayerCount),
		}})
	}

	if s.RecordedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "recorded_at")...),
			sqlite.Arg(s.RecordedAt),
		}})
	}

	return exprs
}

// FindGameServerMetricsHistory retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindGameServerMetricsHistory(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*GameServerMetricsHistory, error) {
	if len(cols) == 0 {
		return GameServerMetricsHistories.Query(
			sm.Where(GameServerMetricsHistories.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return GameServerMetricsHistories.Query(
		sm.Where(GameServerMetricsHistories.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(GameServerMetricsHistories.Columns.Only(cols...)),
	).One(ctx, exec)
}

// GameServerMetricsHistoryExists checks the presence of a single record by primary key
func GameServerMetricsHistoryExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return GameServerMetricsHistories.Query(
		sm.Where(GameServerMetricsHistories.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after GameServerMetricsHistory is retrieved from the database
func (o *GameServerMetricsHistory) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = GameServerMetricsHistories.AfterSelectHooks.RunHooks(ctx, exec, GameServerMetricsHistorySlice{o})
	case bob.QueryTypeInsert:
		ctx, err = GameServerMetricsHistories.AfterInsertHooks.RunHooks(ctx, exec, GameServerMetricsHistorySlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = GameServerMetricsHistories.AfterUpdateHooks.RunHooks(ctx, exec, GameServerMetricsHistorySlice{o})
	case bob.QueryTypeDelete:
		ctx, err = GameServerMetricsHistories.AfterDeleteHooks.RunHooks(ctx, exec, GameServerMetricsHistorySlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the GameServerMetricsHistory
func (o *GameServerMetricsHistory) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *GameServerMetricsHistory) pkEQ() dialect.Expression {
	return sqlite.Quote("game_server_metrics_history", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the GameServerMetricsHistory
func (o *GameServerMetricsHistory) Update(ctx context.Context, exec bob.Executor, s *GameServerMetricsHistorySetter) error {
	v, err := GameServerMetricsHistories.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single GameServerMetricsHistory record with an executor
func (o *GameServerMetricsHistory) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := GameServerMetricsHistories.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the GameServerMetricsHistory using the executor
func (o *GameServerMetricsHistory) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := GameServerMetricsHistories.Query(
		sm.Where(GameServerMetricsHistories.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after GameServerMetricsHistorySlice is retrieved from the database
func (o GameServerMetricsHistorySlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = GameServerMetricsHistories.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = GameServerMetricsHistories.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = GameServerMetricsHistories.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = GameServerMetricsHistories.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o GameServerMetricsHistorySlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("game_server_metrics_history", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o GameServerMetricsHistorySlice) copyMatchingRows(from ...*GameServerMetricsHistory) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o GameServerMetricsHistorySlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return GameServerMetricsHistories.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *GameServerMetricsHistory:
				o.copyMatchingRows(retrieved)
			case []*GameServerMetricsHistory:
				o.copyMatchingRows(retrieved...)
			case GameServerMetricsHistorySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a GameServerMetricsHistory or a slice of GameServerMetricsHistory
				// then run the AfterUpdateHooks on the slice
				_, err = GameServerMetricsHistories.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o GameServerMetricsHistorySlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return GameServerMetricsHistories.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *GameServerMetricsHistory:
				o.copyMatchingRows(retrieved)
			case []*GameServerMetricsHistory:
				o.copyMatchingRows(retrieved...)
			case GameServerMetricsHistorySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a GameServerMetricsHistory or a slice of GameServerMetricsHistory
				// then run the AfterDeleteHooks on the slice
				_, err = GameServerMetricsHistories.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o GameServerMetricsHistorySlice) UpdateAll(ctx context.Context, exec bob.Executor, vals GameServerMetricsHistorySetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := GameServerMetricsHistories.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o GameServerMetricsHistorySlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := GameServerMetricsHistories.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o GameServerMetricsHistorySlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := GameServerMetricsHistories.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// GameServer starts a query for related objects on game_server
func (o *GameServerMetricsHistory) GameServer(mods ...bob.Mod[*dialect.SelectQuery]) GameServersQuery {
	return GameServers.Query(append(mods,
		sm.Where(GameServers.Columns.ID.EQ(sqlite.Arg(o.GameServerID))),
	)...)
}

func (os GameServerMetricsHistorySlice) GameServer(mods ...bob.Mod[*dialect.SelectQuery]) GameServersQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.GameServerID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return GameServers.Query(append(mods,
		sm.Where(sqlite.Group(GameServers.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachGameServerMetricsHistoryGameServer0(ctx context.Context, exec bob.Executor, count int, gameServerMetricsHistory0 *GameServerMetricsHistory, gameServer1 *GameServer) (*GameServerMetricsHistory, error) {
	setter := &GameServerMetricsHistorySetter{
		GameServerID: omit.From(gameServer1.ID),
	}

	err := gameServerMetricsHistory0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachGameServerMetricsHistoryGameServer0: %w", err)
	}

	return gameServerMetricsHistory0, nil
}

func (gameServerMetricsHistory0 *GameServerMetricsHistory) InsertGameServer(ctx context.Context, exec bob.Executor, related *GameServerSetter) error {
	var err error

	gameServer1, err := GameServers.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachGameServerMetricsHistoryGameServer0(ctx, exec, 1, gameServerMetricsHistory0, gameServer1)
	if err != nil {
		return err
	}

	gameServerMetricsHistory0.R.GameServer = gameServer1

	gameServer1.R.GameServerMetricsHistories = append(gameServer1.R.GameServerMetricsHistories, gameServerMetricsHistory0)

	return nil
}

func (gameServerMetricsHistory0 *GameServerMetricsHistory) AttachGameServer(ctx context.Context, exec bob.Executor, gameServer1 *GameServer) error {
	var err error

	_, err = attachGameServerMetricsHistoryGameServer0(ctx, exec, 1, gameServerMetricsHistory0, gameServer1)
	if err != nil {
		return err
	}

	gameServerMetricsHistory0.R.GameServer = gameServer1

	gameServer1.R.GameServerMetricsHistories = append(gameServer1.R.GameServerMetricsHistories, gameServerMetricsHistory0)

	return nil
}

type gameServerMetricsHistoryWhere[Q sqlite.Filterable] struct {
	ID              sqlite.WhereMod[Q, string]
	GameServerID    sqlite.WhereMod[Q, string]
	CPUPercent      sqlite.WhereMod[Q, float64]
	MemoryBytes     sqlite.WhereMod[Q, int64]
	MemoryPercent   sqlite.WhereMod[Q, float64]
	DiskUsageBytes  sqlite.WhereMod[Q, int64]
	IoReadRate      sqlite.WhereMod[Q, float64]
	IoWriteRate     sqlite.WhereMod[Q, float64]
	ConnectionCount sqlite.WhereMod[Q, int64]
	PlayerCount     sqlite.WhereMod[Q, int64]
	RecordedAt      sqlite.WhereMod[Q, time.Time]
}

func (gameServerMetricsHistoryWhere[Q]) AliasedAs(alias string) gameServerMetricsHistoryWhere[Q] {
	return buildGameServerMetricsHistoryWhere[Q](buildGameServerMetricsHistoryColumns(alias))
}

func buildGameServerMetricsHistoryWhere[Q sqlite.Filterable](cols gameServerMetricsHistoryColumns) gameServerMetricsHistoryWhere[Q] {
	return gameServerMetricsHistoryWhere[Q]{
		ID:              sqlite.Where[Q, string](cols.ID),
		GameServerID:    sqlite.Where[Q, string](cols.GameServerID),
		CPUPercent:      sqlite.Where[Q, float64](cols.CPUPercent),
		MemoryBytes:     sqlite.Where[Q, int64](cols.MemoryBytes),
		MemoryPercent:   sqlite.Where[Q, float64](cols.MemoryPercent),
		DiskUsageBytes:  sqlite.Where[Q, int64](cols.DiskUsageBytes),
		IoReadRate:      sqlite.Where[Q, float64](cols.IoReadRate),
		IoWriteRate:     sqlite.Where[Q, float64](cols.IoWriteRate),
		ConnectionCount: sqlite.Where[Q, int64](cols.ConnectionCount),
		PlayerCount:     sqlite.Where[Q, int64](cols.PlayerCount),
		RecordedAt:      sqlite.Where[Q, time.Time](cols.RecordedAt),
	}
}

func (o *GameServerMetricsHistory) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "GameServer":
		rel, ok := retrieved.(*GameServer)
		if !ok {
			return fmt.Errorf("gameServerMetricsHistory cannot load %T as %q", retrieved, name)
		}

		o.R.GameServer = rel

		if rel != nil {
			rel.R.GameServerMetricsHistories = GameServerMetricsHistorySlice{o}
		}
		return nil
	default:
		return fmt.Errorf("gameServerMetricsHistory has no relationship %q", name)
	}
}

type gameServerMetricsHistoryPreloader struct {
	GameServer func(...sqlite.PreloadOption) sqlite.Preloader
}

func buildGameServerMetricsHistoryPreloader() gameServerMetricsHistoryPreloader {
	return gameServerMetricsHistoryPreloader{
		GameServer: func(opts ...sqlite.PreloadOption) sqlite.Preloader {
			return sqlite.Preload[*GameServer, GameServerSlice](sqlite.PreloadRel{
				Name: "GameServer",
				Sides: []sqlite.PreloadSide{
					{
						From:        GameServerMetricsHistories,
						To:          GameServers,
						FromColumns: []string{"game_server_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, GameServers.Columns.Names(), opts...)
		},
	}
}

type gameServerMetricsHistoryThenLoader[Q orm.Loadable] struct {
	GameServer func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildGameServerMetricsHistoryThenLoader[Q orm.Loadable]() gameServerMetricsHistoryThenLoader[Q] {
	type GameServerLoadInterface interface {
		LoadGameServer(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return gameServerMetricsHistoryThenLoader[Q]{
		GameServer: thenLoadBuilder[Q](
			"GameServer",
			func(ctx context.Context, exec bob.Executor, retrieved GameServerLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadGameServer(ctx, exec, mods...)
			},
		),
	}
}

// LoadGameServer loads the gameServerMetricsHistory's GameServer into the .R struct
func (o *GameServerMetricsHistory) LoadGameServer(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.GameServer = nil

	related, err := o.GameServer(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.GameServerMetricsHistories = GameServerMetricsHistorySlice{o}

	o.R.GameServer = related
	return nil
}

// LoadGameServer loads the gameServerMetricsHistory's GameServer into the .R struct
func (os GameServerMetricsHistorySlice) LoadGameServer(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	gameServers, err := os.GameServer(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range gameServers {

			if !(o.GameServerID == rel.ID) {
				continue
			}

			rel.R.GameServerMetricsHistories = append(rel.R.GameServerMetricsHistories, o)

			o.R.GameServer = rel
			break
		}
	}

	return nil
}

type gameServerMetricsHistoryJoins[Q dialect.Joinable] struct {
	typ        string
	GameServer modAs[Q, gameServerColumns]
}

func (j gameServerMetricsHistoryJoins[Q]) aliasedAs(alias string) gameServerMetricsHistoryJoins[Q] {
	return buildGameServerMetricsHistoryJoins[Q](buildGameServerMetricsHistoryColumns(alias), j.typ)
}

func buildGameServerMetricsHistoryJoins[Q dialect.Joinable](cols gameServerMetricsHistoryColumns, typ string) gameServerMetricsHistoryJoins[Q] {
	return gameServerMetricsHistoryJoins[Q]{
		typ: typ,
		GameServer: modAs[Q, gameServerColumns]{
			c: GameServers.Columns,
			f: func(to gameServerColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, GameServers.Name().As(to.Alias())).On(
						to.ID.EQ(cols.GameServerID),
					))
				}

				return mods
			},
		},
	}
}
