// Code generated by BobGen sqlite v0.30.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// GameServer is an object representing the database table.
type GameServer struct {
	ID                        string    `db:"id,pk" `
	UserID                    string    `db:"user_id" `
	Name                      string    `db:"name" `
	GameID                    string    `db:"game_id" `
	StartCommand              string    `db:"start_command" `
	Status                    string    `db:"status" `
	SetPlayers                int64     `db:"set_players" `
	MaxPlayers                int64     `db:"max_players" `
	Map                       string    `db:"map" `
	IP                        string    `db:"ip" `
	Port                      int64     `db:"port" `
	QueryPort                 int64     `db:"query_port" `
	Directory                 string    `db:"directory" `
	MaxMemoryMB               int64     `db:"max_memory_mb" `
	BackupsEnabled            bool      `db:"backups_enabled" `
	SteamGameServerLoginToken string    `db:"steam_game_server_login_token" `
	BackupDirectory           string    `db:"backup_directory" `
	MaxBackups                int64     `db:"max_backups" `
	Version                   string    `db:"version" `
	Branch                    string    `db:"branch" `
	CreatedAt                 time.Time `db:"created_at" `
	UpdatedAt                 time.Time `db:"updated_at" `
	NodeID                    string    `db:"node_id" `

	R gameServerR `db:"-" `
}

// GameServerSlice is an alias for a slice of pointers to GameServer.
// This should almost always be used instead of []*GameServer.
type GameServerSlice []*GameServer

// GameServers contains methods to work with the game_server table
var GameServers = sqlite.NewTablex[*GameServer, GameServerSlice, *GameServerSetter]("", "game_server")

// GameServersQuery is a query on the game_server table
type GameServersQuery = *sqlite.ViewQuery[*GameServer, GameServerSlice]

// gameServerR is where relationships are stored.
type gameServerR struct {
	Node *Node    // fk_game_server_0
	IP   *IP      // fk_game_server_1
	Game *Game    // fk_game_server_2
	User *User    // fk_game_server_3
	Logs LogSlice // fk_log_0
}

type gameServerColumnNames struct {
	ID                        string
	UserID                    string
	Name                      string
	GameID                    string
	StartCommand              string
	Status                    string
	SetPlayers                string
	MaxPlayers                string
	Map                       string
	IP                        string
	Port                      string
	QueryPort                 string
	Directory                 string
	MaxMemoryMB               string
	BackupsEnabled            string
	SteamGameServerLoginToken string
	BackupDirectory           string
	MaxBackups                string
	Version                   string
	Branch                    string
	CreatedAt                 string
	UpdatedAt                 string
	NodeID                    string
}

var GameServerColumns = buildGameServerColumns("game_server")

type gameServerColumns struct {
	tableAlias                string
	ID                        sqlite.Expression
	UserID                    sqlite.Expression
	Name                      sqlite.Expression
	GameID                    sqlite.Expression
	StartCommand              sqlite.Expression
	Status                    sqlite.Expression
	SetPlayers                sqlite.Expression
	MaxPlayers                sqlite.Expression
	Map                       sqlite.Expression
	IP                        sqlite.Expression
	Port                      sqlite.Expression
	QueryPort                 sqlite.Expression
	Directory                 sqlite.Expression
	MaxMemoryMB               sqlite.Expression
	BackupsEnabled            sqlite.Expression
	SteamGameServerLoginToken sqlite.Expression
	BackupDirectory           sqlite.Expression
	MaxBackups                sqlite.Expression
	Version                   sqlite.Expression
	Branch                    sqlite.Expression
	CreatedAt                 sqlite.Expression
	UpdatedAt                 sqlite.Expression
	NodeID                    sqlite.Expression
}

func (c gameServerColumns) Alias() string {
	return c.tableAlias
}

func (gameServerColumns) AliasedAs(alias string) gameServerColumns {
	return buildGameServerColumns(alias)
}

func buildGameServerColumns(alias string) gameServerColumns {
	return gameServerColumns{
		tableAlias:                alias,
		ID:                        sqlite.Quote(alias, "id"),
		UserID:                    sqlite.Quote(alias, "user_id"),
		Name:                      sqlite.Quote(alias, "name"),
		GameID:                    sqlite.Quote(alias, "game_id"),
		StartCommand:              sqlite.Quote(alias, "start_command"),
		Status:                    sqlite.Quote(alias, "status"),
		SetPlayers:                sqlite.Quote(alias, "set_players"),
		MaxPlayers:                sqlite.Quote(alias, "max_players"),
		Map:                       sqlite.Quote(alias, "map"),
		IP:                        sqlite.Quote(alias, "ip"),
		Port:                      sqlite.Quote(alias, "port"),
		QueryPort:                 sqlite.Quote(alias, "query_port"),
		Directory:                 sqlite.Quote(alias, "directory"),
		MaxMemoryMB:               sqlite.Quote(alias, "max_memory_mb"),
		BackupsEnabled:            sqlite.Quote(alias, "backups_enabled"),
		SteamGameServerLoginToken: sqlite.Quote(alias, "steam_game_server_login_token"),
		BackupDirectory:           sqlite.Quote(alias, "backup_directory"),
		MaxBackups:                sqlite.Quote(alias, "max_backups"),
		Version:                   sqlite.Quote(alias, "version"),
		Branch:                    sqlite.Quote(alias, "branch"),
		CreatedAt:                 sqlite.Quote(alias, "created_at"),
		UpdatedAt:                 sqlite.Quote(alias, "updated_at"),
		NodeID:                    sqlite.Quote(alias, "node_id"),
	}
}

type gameServerWhere[Q sqlite.Filterable] struct {
	ID                        sqlite.WhereMod[Q, string]
	UserID                    sqlite.WhereMod[Q, string]
	Name                      sqlite.WhereMod[Q, string]
	GameID                    sqlite.WhereMod[Q, string]
	StartCommand              sqlite.WhereMod[Q, string]
	Status                    sqlite.WhereMod[Q, string]
	SetPlayers                sqlite.WhereMod[Q, int64]
	MaxPlayers                sqlite.WhereMod[Q, int64]
	Map                       sqlite.WhereMod[Q, string]
	IP                        sqlite.WhereMod[Q, string]
	Port                      sqlite.WhereMod[Q, int64]
	QueryPort                 sqlite.WhereMod[Q, int64]
	Directory                 sqlite.WhereMod[Q, string]
	MaxMemoryMB               sqlite.WhereMod[Q, int64]
	BackupsEnabled            sqlite.WhereMod[Q, bool]
	SteamGameServerLoginToken sqlite.WhereMod[Q, string]
	BackupDirectory           sqlite.WhereMod[Q, string]
	MaxBackups                sqlite.WhereMod[Q, int64]
	Version                   sqlite.WhereMod[Q, string]
	Branch                    sqlite.WhereMod[Q, string]
	CreatedAt                 sqlite.WhereMod[Q, time.Time]
	UpdatedAt                 sqlite.WhereMod[Q, time.Time]
	NodeID                    sqlite.WhereMod[Q, string]
}

func (gameServerWhere[Q]) AliasedAs(alias string) gameServerWhere[Q] {
	return buildGameServerWhere[Q](buildGameServerColumns(alias))
}

func buildGameServerWhere[Q sqlite.Filterable](cols gameServerColumns) gameServerWhere[Q] {
	return gameServerWhere[Q]{
		ID:                        sqlite.Where[Q, string](cols.ID),
		UserID:                    sqlite.Where[Q, string](cols.UserID),
		Name:                      sqlite.Where[Q, string](cols.Name),
		GameID:                    sqlite.Where[Q, string](cols.GameID),
		StartCommand:              sqlite.Where[Q, string](cols.StartCommand),
		Status:                    sqlite.Where[Q, string](cols.Status),
		SetPlayers:                sqlite.Where[Q, int64](cols.SetPlayers),
		MaxPlayers:                sqlite.Where[Q, int64](cols.MaxPlayers),
		Map:                       sqlite.Where[Q, string](cols.Map),
		IP:                        sqlite.Where[Q, string](cols.IP),
		Port:                      sqlite.Where[Q, int64](cols.Port),
		QueryPort:                 sqlite.Where[Q, int64](cols.QueryPort),
		Directory:                 sqlite.Where[Q, string](cols.Directory),
		MaxMemoryMB:               sqlite.Where[Q, int64](cols.MaxMemoryMB),
		BackupsEnabled:            sqlite.Where[Q, bool](cols.BackupsEnabled),
		SteamGameServerLoginToken: sqlite.Where[Q, string](cols.SteamGameServerLoginToken),
		BackupDirectory:           sqlite.Where[Q, string](cols.BackupDirectory),
		MaxBackups:                sqlite.Where[Q, int64](cols.MaxBackups),
		Version:                   sqlite.Where[Q, string](cols.Version),
		Branch:                    sqlite.Where[Q, string](cols.Branch),
		CreatedAt:                 sqlite.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:                 sqlite.Where[Q, time.Time](cols.UpdatedAt),
		NodeID:                    sqlite.Where[Q, string](cols.NodeID),
	}
}

// GameServerSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type GameServerSetter struct {
	ID                        omit.Val[string]    `db:"id,pk" `
	UserID                    omit.Val[string]    `db:"user_id" `
	Name                      omit.Val[string]    `db:"name" `
	GameID                    omit.Val[string]    `db:"game_id" `
	StartCommand              omit.Val[string]    `db:"start_command" `
	Status                    omit.Val[string]    `db:"status" `
	SetPlayers                omit.Val[int64]     `db:"set_players" `
	MaxPlayers                omit.Val[int64]     `db:"max_players" `
	Map                       omit.Val[string]    `db:"map" `
	IP                        omit.Val[string]    `db:"ip" `
	Port                      omit.Val[int64]     `db:"port" `
	QueryPort                 omit.Val[int64]     `db:"query_port" `
	Directory                 omit.Val[string]    `db:"directory" `
	MaxMemoryMB               omit.Val[int64]     `db:"max_memory_mb" `
	BackupsEnabled            omit.Val[bool]      `db:"backups_enabled" `
	SteamGameServerLoginToken omit.Val[string]    `db:"steam_game_server_login_token" `
	BackupDirectory           omit.Val[string]    `db:"backup_directory" `
	MaxBackups                omit.Val[int64]     `db:"max_backups" `
	Version                   omit.Val[string]    `db:"version" `
	Branch                    omit.Val[string]    `db:"branch" `
	CreatedAt                 omit.Val[time.Time] `db:"created_at" `
	UpdatedAt                 omit.Val[time.Time] `db:"updated_at" `
	NodeID                    omit.Val[string]    `db:"node_id" `
}

func (s GameServerSetter) SetColumns() []string {
	vals := make([]string, 0, 23)
	if !s.ID.IsUnset() {
		vals = append(vals, "id")
	}

	if !s.UserID.IsUnset() {
		vals = append(vals, "user_id")
	}

	if !s.Name.IsUnset() {
		vals = append(vals, "name")
	}

	if !s.GameID.IsUnset() {
		vals = append(vals, "game_id")
	}

	if !s.StartCommand.IsUnset() {
		vals = append(vals, "start_command")
	}

	if !s.Status.IsUnset() {
		vals = append(vals, "status")
	}

	if !s.SetPlayers.IsUnset() {
		vals = append(vals, "set_players")
	}

	if !s.MaxPlayers.IsUnset() {
		vals = append(vals, "max_players")
	}

	if !s.Map.IsUnset() {
		vals = append(vals, "map")
	}

	if !s.IP.IsUnset() {
		vals = append(vals, "ip")
	}

	if !s.Port.IsUnset() {
		vals = append(vals, "port")
	}

	if !s.QueryPort.IsUnset() {
		vals = append(vals, "query_port")
	}

	if !s.Directory.IsUnset() {
		vals = append(vals, "directory")
	}

	if !s.MaxMemoryMB.IsUnset() {
		vals = append(vals, "max_memory_mb")
	}

	if !s.BackupsEnabled.IsUnset() {
		vals = append(vals, "backups_enabled")
	}

	if !s.SteamGameServerLoginToken.IsUnset() {
		vals = append(vals, "steam_game_server_login_token")
	}

	if !s.BackupDirectory.IsUnset() {
		vals = append(vals, "backup_directory")
	}

	if !s.MaxBackups.IsUnset() {
		vals = append(vals, "max_backups")
	}

	if !s.Version.IsUnset() {
		vals = append(vals, "version")
	}

	if !s.Branch.IsUnset() {
		vals = append(vals, "branch")
	}

	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}

	if !s.UpdatedAt.IsUnset() {
		vals = append(vals, "updated_at")
	}

	if !s.NodeID.IsUnset() {
		vals = append(vals, "node_id")
	}

	return vals
}

func (s GameServerSetter) Overwrite(t *GameServer) {
	if !s.ID.IsUnset() {
		t.ID, _ = s.ID.Get()
	}
	if !s.UserID.IsUnset() {
		t.UserID, _ = s.UserID.Get()
	}
	if !s.Name.IsUnset() {
		t.Name, _ = s.Name.Get()
	}
	if !s.GameID.IsUnset() {
		t.GameID, _ = s.GameID.Get()
	}
	if !s.StartCommand.IsUnset() {
		t.StartCommand, _ = s.StartCommand.Get()
	}
	if !s.Status.IsUnset() {
		t.Status, _ = s.Status.Get()
	}
	if !s.SetPlayers.IsUnset() {
		t.SetPlayers, _ = s.SetPlayers.Get()
	}
	if !s.MaxPlayers.IsUnset() {
		t.MaxPlayers, _ = s.MaxPlayers.Get()
	}
	if !s.Map.IsUnset() {
		t.Map, _ = s.Map.Get()
	}
	if !s.IP.IsUnset() {
		t.IP, _ = s.IP.Get()
	}
	if !s.Port.IsUnset() {
		t.Port, _ = s.Port.Get()
	}
	if !s.QueryPort.IsUnset() {
		t.QueryPort, _ = s.QueryPort.Get()
	}
	if !s.Directory.IsUnset() {
		t.Directory, _ = s.Directory.Get()
	}
	if !s.MaxMemoryMB.IsUnset() {
		t.MaxMemoryMB, _ = s.MaxMemoryMB.Get()
	}
	if !s.BackupsEnabled.IsUnset() {
		t.BackupsEnabled, _ = s.BackupsEnabled.Get()
	}
	if !s.SteamGameServerLoginToken.IsUnset() {
		t.SteamGameServerLoginToken, _ = s.SteamGameServerLoginToken.Get()
	}
	if !s.BackupDirectory.IsUnset() {
		t.BackupDirectory, _ = s.BackupDirectory.Get()
	}
	if !s.MaxBackups.IsUnset() {
		t.MaxBackups, _ = s.MaxBackups.Get()
	}
	if !s.Version.IsUnset() {
		t.Version, _ = s.Version.Get()
	}
	if !s.Branch.IsUnset() {
		t.Branch, _ = s.Branch.Get()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt, _ = s.CreatedAt.Get()
	}
	if !s.UpdatedAt.IsUnset() {
		t.UpdatedAt, _ = s.UpdatedAt.Get()
	}
	if !s.NodeID.IsUnset() {
		t.NodeID, _ = s.NodeID.Get()
	}
}

func (s *GameServerSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return GameServers.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.Table.Columns) == 0 {
		q.Table.Columns = s.SetColumns()
	}

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 0, 23)
		if !s.ID.IsUnset() {
			vals = append(vals, sqlite.Arg(s.ID))
		}

		if !s.UserID.IsUnset() {
			vals = append(vals, sqlite.Arg(s.UserID))
		}

		if !s.Name.IsUnset() {
			vals = append(vals, sqlite.Arg(s.Name))
		}

		if !s.GameID.IsUnset() {
			vals = append(vals, sqlite.Arg(s.GameID))
		}

		if !s.StartCommand.IsUnset() {
			vals = append(vals, sqlite.Arg(s.StartCommand))
		}

		if !s.Status.IsUnset() {
			vals = append(vals, sqlite.Arg(s.Status))
		}

		if !s.SetPlayers.IsUnset() {
			vals = append(vals, sqlite.Arg(s.SetPlayers))
		}

		if !s.MaxPlayers.IsUnset() {
			vals = append(vals, sqlite.Arg(s.MaxPlayers))
		}

		if !s.Map.IsUnset() {
			vals = append(vals, sqlite.Arg(s.Map))
		}

		if !s.IP.IsUnset() {
			vals = append(vals, sqlite.Arg(s.IP))
		}

		if !s.Port.IsUnset() {
			vals = append(vals, sqlite.Arg(s.Port))
		}

		if !s.QueryPort.IsUnset() {
			vals = append(vals, sqlite.Arg(s.QueryPort))
		}

		if !s.Directory.IsUnset() {
			vals = append(vals, sqlite.Arg(s.Directory))
		}

		if !s.MaxMemoryMB.IsUnset() {
			vals = append(vals, sqlite.Arg(s.MaxMemoryMB))
		}

		if !s.BackupsEnabled.IsUnset() {
			vals = append(vals, sqlite.Arg(s.BackupsEnabled))
		}

		if !s.SteamGameServerLoginToken.IsUnset() {
			vals = append(vals, sqlite.Arg(s.SteamGameServerLoginToken))
		}

		if !s.BackupDirectory.IsUnset() {
			vals = append(vals, sqlite.Arg(s.BackupDirectory))
		}

		if !s.MaxBackups.IsUnset() {
			vals = append(vals, sqlite.Arg(s.MaxBackups))
		}

		if !s.Version.IsUnset() {
			vals = append(vals, sqlite.Arg(s.Version))
		}

		if !s.Branch.IsUnset() {
			vals = append(vals, sqlite.Arg(s.Branch))
		}

		if !s.CreatedAt.IsUnset() {
			vals = append(vals, sqlite.Arg(s.CreatedAt))
		}

		if !s.UpdatedAt.IsUnset() {
			vals = append(vals, sqlite.Arg(s.UpdatedAt))
		}

		if !s.NodeID.IsUnset() {
			vals = append(vals, sqlite.Arg(s.NodeID))
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s GameServerSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s GameServerSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 23)

	if !s.ID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if !s.UserID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "user_id")...),
			sqlite.Arg(s.UserID),
		}})
	}

	if !s.Name.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "name")...),
			sqlite.Arg(s.Name),
		}})
	}

	if !s.GameID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "game_id")...),
			sqlite.Arg(s.GameID),
		}})
	}

	if !s.StartCommand.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "start_command")...),
			sqlite.Arg(s.StartCommand),
		}})
	}

	if !s.Status.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "status")...),
			sqlite.Arg(s.Status),
		}})
	}

	if !s.SetPlayers.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "set_players")...),
			sqlite.Arg(s.SetPlayers),
		}})
	}

	if !s.MaxPlayers.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "max_players")...),
			sqlite.Arg(s.MaxPlayers),
		}})
	}

	if !s.Map.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "map")...),
			sqlite.Arg(s.Map),
		}})
	}

	if !s.IP.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "ip")...),
			sqlite.Arg(s.IP),
		}})
	}

	if !s.Port.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "port")...),
			sqlite.Arg(s.Port),
		}})
	}

	if !s.QueryPort.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "query_port")...),
			sqlite.Arg(s.QueryPort),
		}})
	}

	if !s.Directory.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "directory")...),
			sqlite.Arg(s.Directory),
		}})
	}

	if !s.MaxMemoryMB.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "max_memory_mb")...),
			sqlite.Arg(s.MaxMemoryMB),
		}})
	}

	if !s.BackupsEnabled.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "backups_enabled")...),
			sqlite.Arg(s.BackupsEnabled),
		}})
	}

	if !s.SteamGameServerLoginToken.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "steam_game_server_login_token")...),
			sqlite.Arg(s.SteamGameServerLoginToken),
		}})
	}

	if !s.BackupDirectory.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "backup_directory")...),
			sqlite.Arg(s.BackupDirectory),
		}})
	}

	if !s.MaxBackups.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "max_backups")...),
			sqlite.Arg(s.MaxBackups),
		}})
	}

	if !s.Version.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "version")...),
			sqlite.Arg(s.Version),
		}})
	}

	if !s.Branch.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "branch")...),
			sqlite.Arg(s.Branch),
		}})
	}

	if !s.CreatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "created_at")...),
			sqlite.Arg(s.CreatedAt),
		}})
	}

	if !s.UpdatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "updated_at")...),
			sqlite.Arg(s.UpdatedAt),
		}})
	}

	if !s.NodeID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "node_id")...),
			sqlite.Arg(s.NodeID),
		}})
	}

	return exprs
}

// FindGameServer retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindGameServer(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*GameServer, error) {
	if len(cols) == 0 {
		return GameServers.Query(
			SelectWhere.GameServers.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return GameServers.Query(
		SelectWhere.GameServers.ID.EQ(IDPK),
		sm.Columns(GameServers.Columns().Only(cols...)),
	).One(ctx, exec)
}

// GameServerExists checks the presence of a single record by primary key
func GameServerExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return GameServers.Query(
		SelectWhere.GameServers.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after GameServer is retrieved from the database
func (o *GameServer) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = GameServers.AfterSelectHooks.RunHooks(ctx, exec, GameServerSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = GameServers.AfterInsertHooks.RunHooks(ctx, exec, GameServerSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = GameServers.AfterUpdateHooks.RunHooks(ctx, exec, GameServerSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = GameServers.AfterDeleteHooks.RunHooks(ctx, exec, GameServerSlice{o})
	}

	return err
}

// PrimaryKeyVals returns the primary key values of the GameServer
func (o *GameServer) PrimaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *GameServer) pkEQ() dialect.Expression {
	return sqlite.Quote("game_server", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.PrimaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the GameServer
func (o *GameServer) Update(ctx context.Context, exec bob.Executor, s *GameServerSetter) error {
	v, err := GameServers.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single GameServer record with an executor
func (o *GameServer) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := GameServers.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the GameServer using the executor
func (o *GameServer) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := GameServers.Query(
		SelectWhere.GameServers.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after GameServerSlice is retrieved from the database
func (o GameServerSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = GameServers.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = GameServers.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = GameServers.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = GameServers.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o GameServerSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("game_server", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.PrimaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o GameServerSlice) copyMatchingRows(from ...*GameServer) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o GameServerSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return GameServers.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *GameServer:
				o.copyMatchingRows(retrieved)
			case []*GameServer:
				o.copyMatchingRows(retrieved...)
			case GameServerSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a GameServer or a slice of GameServer
				// then run the AfterUpdateHooks on the slice
				_, err = GameServers.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o GameServerSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return GameServers.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *GameServer:
				o.copyMatchingRows(retrieved)
			case []*GameServer:
				o.copyMatchingRows(retrieved...)
			case GameServerSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a GameServer or a slice of GameServer
				// then run the AfterDeleteHooks on the slice
				_, err = GameServers.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o GameServerSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals GameServerSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := GameServers.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o GameServerSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := GameServers.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o GameServerSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := GameServers.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type gameServerJoins[Q dialect.Joinable] struct {
	typ  string
	Node func(context.Context) modAs[Q, nodeColumns]
	IP   func(context.Context) modAs[Q, ipColumns]
	Game func(context.Context) modAs[Q, gameColumns]
	User func(context.Context) modAs[Q, userColumns]
	Logs func(context.Context) modAs[Q, logColumns]
}

func (j gameServerJoins[Q]) aliasedAs(alias string) gameServerJoins[Q] {
	return buildGameServerJoins[Q](buildGameServerColumns(alias), j.typ)
}

func buildGameServerJoins[Q dialect.Joinable](cols gameServerColumns, typ string) gameServerJoins[Q] {
	return gameServerJoins[Q]{
		typ:  typ,
		Node: gameServersJoinNode[Q](cols, typ),
		IP:   gameServersJoinIP[Q](cols, typ),
		Game: gameServersJoinGame[Q](cols, typ),
		User: gameServersJoinUser[Q](cols, typ),
		Logs: gameServersJoinLogs[Q](cols, typ),
	}
}

func gameServersJoinNode[Q dialect.Joinable](from gameServerColumns, typ string) func(context.Context) modAs[Q, nodeColumns] {
	return func(ctx context.Context) modAs[Q, nodeColumns] {
		return modAs[Q, nodeColumns]{
			c: NodeColumns,
			f: func(to nodeColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Nodes.Name().As(to.Alias())).On(
						to.ID.EQ(from.NodeID),
					))
				}

				return mods
			},
		}
	}
}

func gameServersJoinIP[Q dialect.Joinable](from gameServerColumns, typ string) func(context.Context) modAs[Q, ipColumns] {
	return func(ctx context.Context) modAs[Q, ipColumns] {
		return modAs[Q, ipColumns]{
			c: IPColumns,
			f: func(to ipColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Ips.Name().As(to.Alias())).On(
						to.Address.EQ(from.IP),
					))
				}

				return mods
			},
		}
	}
}

func gameServersJoinGame[Q dialect.Joinable](from gameServerColumns, typ string) func(context.Context) modAs[Q, gameColumns] {
	return func(ctx context.Context) modAs[Q, gameColumns] {
		return modAs[Q, gameColumns]{
			c: GameColumns,
			f: func(to gameColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Games.Name().As(to.Alias())).On(
						to.ID.EQ(from.GameID),
					))
				}

				return mods
			},
		}
	}
}

func gameServersJoinUser[Q dialect.Joinable](from gameServerColumns, typ string) func(context.Context) modAs[Q, userColumns] {
	return func(ctx context.Context) modAs[Q, userColumns] {
		return modAs[Q, userColumns]{
			c: UserColumns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(from.UserID),
					))
				}

				return mods
			},
		}
	}
}

func gameServersJoinLogs[Q dialect.Joinable](from gameServerColumns, typ string) func(context.Context) modAs[Q, logColumns] {
	return func(ctx context.Context) modAs[Q, logColumns] {
		return modAs[Q, logColumns]{
			c: LogColumns,
			f: func(to logColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Logs.Name().As(to.Alias())).On(
						to.GameServerID.EQ(from.ID),
					))
				}

				return mods
			},
		}
	}
}

// Node starts a query for related objects on node
func (o *GameServer) Node(mods ...bob.Mod[*dialect.SelectQuery]) NodesQuery {
	return Nodes.Query(append(mods,
		sm.Where(NodeColumns.ID.EQ(sqlite.Arg(o.NodeID))),
	)...)
}

func (os GameServerSlice) Node(mods ...bob.Mod[*dialect.SelectQuery]) NodesQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = sqlite.ArgGroup(o.NodeID)
	}

	return Nodes.Query(append(mods,
		sm.Where(sqlite.Group(NodeColumns.ID).In(PKArgs...)),
	)...)
}

// IP starts a query for related objects on ip
func (o *GameServer) RelatedIP(mods ...bob.Mod[*dialect.SelectQuery]) IpsQuery {
	return Ips.Query(append(mods,
		sm.Where(IPColumns.Address.EQ(sqlite.Arg(o.IP))),
	)...)
}

func (os GameServerSlice) RelatedIP(mods ...bob.Mod[*dialect.SelectQuery]) IpsQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = sqlite.ArgGroup(o.IP)
	}

	return Ips.Query(append(mods,
		sm.Where(sqlite.Group(IPColumns.Address).In(PKArgs...)),
	)...)
}

// Game starts a query for related objects on game
func (o *GameServer) Game(mods ...bob.Mod[*dialect.SelectQuery]) GamesQuery {
	return Games.Query(append(mods,
		sm.Where(GameColumns.ID.EQ(sqlite.Arg(o.GameID))),
	)...)
}

func (os GameServerSlice) Game(mods ...bob.Mod[*dialect.SelectQuery]) GamesQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = sqlite.ArgGroup(o.GameID)
	}

	return Games.Query(append(mods,
		sm.Where(sqlite.Group(GameColumns.ID).In(PKArgs...)),
	)...)
}

// User starts a query for related objects on user
func (o *GameServer) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(UserColumns.ID.EQ(sqlite.Arg(o.UserID))),
	)...)
}

func (os GameServerSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = sqlite.ArgGroup(o.UserID)
	}

	return Users.Query(append(mods,
		sm.Where(sqlite.Group(UserColumns.ID).In(PKArgs...)),
	)...)
}

// Logs starts a query for related objects on log
func (o *GameServer) Logs(mods ...bob.Mod[*dialect.SelectQuery]) LogsQuery {
	return Logs.Query(append(mods,
		sm.Where(LogColumns.GameServerID.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os GameServerSlice) Logs(mods ...bob.Mod[*dialect.SelectQuery]) LogsQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = sqlite.ArgGroup(o.ID)
	}

	return Logs.Query(append(mods,
		sm.Where(sqlite.Group(LogColumns.GameServerID).In(PKArgs...)),
	)...)
}

func (o *GameServer) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Node":
		rel, ok := retrieved.(*Node)
		if !ok {
			return fmt.Errorf("gameServer cannot load %T as %q", retrieved, name)
		}

		o.R.Node = rel

		if rel != nil {
			rel.R.GameServers = GameServerSlice{o}
		}
		return nil
	case "IP":
		rel, ok := retrieved.(*IP)
		if !ok {
			return fmt.Errorf("gameServer cannot load %T as %q", retrieved, name)
		}

		o.R.IP = rel

		if rel != nil {
			rel.R.GameServers = GameServerSlice{o}
		}
		return nil
	case "Game":
		rel, ok := retrieved.(*Game)
		if !ok {
			return fmt.Errorf("gameServer cannot load %T as %q", retrieved, name)
		}

		o.R.Game = rel

		if rel != nil {
			rel.R.GameServers = GameServerSlice{o}
		}
		return nil
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("gameServer cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.GameServers = GameServerSlice{o}
		}
		return nil
	case "Logs":
		rels, ok := retrieved.(LogSlice)
		if !ok {
			return fmt.Errorf("gameServer cannot load %T as %q", retrieved, name)
		}

		o.R.Logs = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.GameServer = o
			}
		}
		return nil
	default:
		return fmt.Errorf("gameServer has no relationship %q", name)
	}
}

func PreloadGameServerNode(opts ...sqlite.PreloadOption) sqlite.Preloader {
	return sqlite.Preload[*Node, NodeSlice](orm.Relationship{
		Name: "Node",
		Sides: []orm.RelSide{
			{
				From: TableNames.GameServers,
				To:   TableNames.Nodes,
				FromColumns: []string{
					ColumnNames.GameServers.NodeID,
				},
				ToColumns: []string{
					ColumnNames.Nodes.ID,
				},
			},
		},
	}, Nodes.Columns().Names(), opts...)
}

func ThenLoadGameServerNode(queryMods ...bob.Mod[*dialect.SelectQuery]) sqlite.Loader {
	return sqlite.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadGameServerNode(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load GameServerNode", retrieved)
		}

		err := loader.LoadGameServerNode(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadGameServerNode loads the gameServer's Node into the .R struct
func (o *GameServer) LoadGameServerNode(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Node = nil

	related, err := o.Node(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.GameServers = GameServerSlice{o}

	o.R.Node = related
	return nil
}

// LoadGameServerNode loads the gameServer's Node into the .R struct
func (os GameServerSlice) LoadGameServerNode(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	nodes, err := os.Node(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range nodes {
			if o.NodeID != rel.ID {
				continue
			}

			rel.R.GameServers = append(rel.R.GameServers, o)

			o.R.Node = rel
			break
		}
	}

	return nil
}

func PreloadGameServerIP(opts ...sqlite.PreloadOption) sqlite.Preloader {
	return sqlite.Preload[*IP, IPSlice](orm.Relationship{
		Name: "IP",
		Sides: []orm.RelSide{
			{
				From: TableNames.GameServers,
				To:   TableNames.Ips,
				FromColumns: []string{
					ColumnNames.GameServers.IP,
				},
				ToColumns: []string{
					ColumnNames.Ips.Address,
				},
			},
		},
	}, Ips.Columns().Names(), opts...)
}

func ThenLoadGameServerIP(queryMods ...bob.Mod[*dialect.SelectQuery]) sqlite.Loader {
	return sqlite.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadGameServerIP(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load GameServerIP", retrieved)
		}

		err := loader.LoadGameServerIP(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadGameServerIP loads the gameServer's IP into the .R struct
func (o *GameServer) LoadGameServerIP(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.IP = nil

	related, err := o.RelatedIP(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.GameServers = GameServerSlice{o}

	o.R.IP = related
	return nil
}

// LoadGameServerIP loads the gameServer's IP into the .R struct
func (os GameServerSlice) LoadGameServerIP(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	ips, err := os.RelatedIP(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range ips {
			if o.IP != rel.Address {
				continue
			}

			rel.R.GameServers = append(rel.R.GameServers, o)

			o.R.IP = rel
			break
		}
	}

	return nil
}

func PreloadGameServerGame(opts ...sqlite.PreloadOption) sqlite.Preloader {
	return sqlite.Preload[*Game, GameSlice](orm.Relationship{
		Name: "Game",
		Sides: []orm.RelSide{
			{
				From: TableNames.GameServers,
				To:   TableNames.Games,
				FromColumns: []string{
					ColumnNames.GameServers.GameID,
				},
				ToColumns: []string{
					ColumnNames.Games.ID,
				},
			},
		},
	}, Games.Columns().Names(), opts...)
}

func ThenLoadGameServerGame(queryMods ...bob.Mod[*dialect.SelectQuery]) sqlite.Loader {
	return sqlite.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadGameServerGame(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load GameServerGame", retrieved)
		}

		err := loader.LoadGameServerGame(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadGameServerGame loads the gameServer's Game into the .R struct
func (o *GameServer) LoadGameServerGame(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Game = nil

	related, err := o.Game(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.GameServers = GameServerSlice{o}

	o.R.Game = related
	return nil
}

// LoadGameServerGame loads the gameServer's Game into the .R struct
func (os GameServerSlice) LoadGameServerGame(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	games, err := os.Game(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range games {
			if o.GameID != rel.ID {
				continue
			}

			rel.R.GameServers = append(rel.R.GameServers, o)

			o.R.Game = rel
			break
		}
	}

	return nil
}

func PreloadGameServerUser(opts ...sqlite.PreloadOption) sqlite.Preloader {
	return sqlite.Preload[*User, UserSlice](orm.Relationship{
		Name: "User",
		Sides: []orm.RelSide{
			{
				From: TableNames.GameServers,
				To:   TableNames.Users,
				FromColumns: []string{
					ColumnNames.GameServers.UserID,
				},
				ToColumns: []string{
					ColumnNames.Users.ID,
				},
			},
		},
	}, Users.Columns().Names(), opts...)
}

func ThenLoadGameServerUser(queryMods ...bob.Mod[*dialect.SelectQuery]) sqlite.Loader {
	return sqlite.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadGameServerUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load GameServerUser", retrieved)
		}

		err := loader.LoadGameServerUser(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadGameServerUser loads the gameServer's User into the .R struct
func (o *GameServer) LoadGameServerUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.GameServers = GameServerSlice{o}

	o.R.User = related
	return nil
}

// LoadGameServerUser loads the gameServer's User into the .R struct
func (os GameServerSlice) LoadGameServerUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range users {
			if o.UserID != rel.ID {
				continue
			}

			rel.R.GameServers = append(rel.R.GameServers, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

func ThenLoadGameServerLogs(queryMods ...bob.Mod[*dialect.SelectQuery]) sqlite.Loader {
	return sqlite.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadGameServerLogs(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load GameServerLogs", retrieved)
		}

		err := loader.LoadGameServerLogs(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadGameServerLogs loads the gameServer's Logs into the .R struct
func (o *GameServer) LoadGameServerLogs(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Logs = nil

	related, err := o.Logs(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.GameServer = o
	}

	o.R.Logs = related
	return nil
}

// LoadGameServerLogs loads the gameServer's Logs into the .R struct
func (os GameServerSlice) LoadGameServerLogs(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	logs, err := os.Logs(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.Logs = nil
	}

	for _, o := range os {
		for _, rel := range logs {
			if o.ID != rel.GameServerID.GetOrZero() {
				continue
			}

			rel.R.GameServer = o

			o.R.Logs = append(o.R.Logs, rel)
		}
	}

	return nil
}

func attachGameServerNode0(ctx context.Context, exec bob.Executor, count int, gameServer0 *GameServer, node1 *Node) (*GameServer, error) {
	setter := &GameServerSetter{
		NodeID: omit.From(node1.ID),
	}

	err := gameServer0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachGameServerNode0: %w", err)
	}

	return gameServer0, nil
}

func (gameServer0 *GameServer) InsertNode(ctx context.Context, exec bob.Executor, related *NodeSetter) error {
	node1, err := Nodes.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachGameServerNode0(ctx, exec, 1, gameServer0, node1)
	if err != nil {
		return err
	}

	gameServer0.R.Node = node1

	node1.R.GameServers = append(node1.R.GameServers, gameServer0)

	return nil
}

func (gameServer0 *GameServer) AttachNode(ctx context.Context, exec bob.Executor, node1 *Node) error {
	var err error

	_, err = attachGameServerNode0(ctx, exec, 1, gameServer0, node1)
	if err != nil {
		return err
	}

	gameServer0.R.Node = node1

	node1.R.GameServers = append(node1.R.GameServers, gameServer0)

	return nil
}

func attachGameServerIP0(ctx context.Context, exec bob.Executor, count int, gameServer0 *GameServer, ip1 *IP) (*GameServer, error) {
	setter := &GameServerSetter{
		IP: omit.From(ip1.Address),
	}

	err := gameServer0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachGameServerIP0: %w", err)
	}

	return gameServer0, nil
}

func (gameServer0 *GameServer) InsertIP(ctx context.Context, exec bob.Executor, related *IPSetter) error {
	ip1, err := Ips.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachGameServerIP0(ctx, exec, 1, gameServer0, ip1)
	if err != nil {
		return err
	}

	gameServer0.R.IP = ip1

	ip1.R.GameServers = append(ip1.R.GameServers, gameServer0)

	return nil
}

func (gameServer0 *GameServer) AttachIP(ctx context.Context, exec bob.Executor, ip1 *IP) error {
	var err error

	_, err = attachGameServerIP0(ctx, exec, 1, gameServer0, ip1)
	if err != nil {
		return err
	}

	gameServer0.R.IP = ip1

	ip1.R.GameServers = append(ip1.R.GameServers, gameServer0)

	return nil
}

func attachGameServerGame0(ctx context.Context, exec bob.Executor, count int, gameServer0 *GameServer, game1 *Game) (*GameServer, error) {
	setter := &GameServerSetter{
		GameID: omit.From(game1.ID),
	}

	err := gameServer0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachGameServerGame0: %w", err)
	}

	return gameServer0, nil
}

func (gameServer0 *GameServer) InsertGame(ctx context.Context, exec bob.Executor, related *GameSetter) error {
	game1, err := Games.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachGameServerGame0(ctx, exec, 1, gameServer0, game1)
	if err != nil {
		return err
	}

	gameServer0.R.Game = game1

	game1.R.GameServers = append(game1.R.GameServers, gameServer0)

	return nil
}

func (gameServer0 *GameServer) AttachGame(ctx context.Context, exec bob.Executor, game1 *Game) error {
	var err error

	_, err = attachGameServerGame0(ctx, exec, 1, gameServer0, game1)
	if err != nil {
		return err
	}

	gameServer0.R.Game = game1

	game1.R.GameServers = append(game1.R.GameServers, gameServer0)

	return nil
}

func attachGameServerUser0(ctx context.Context, exec bob.Executor, count int, gameServer0 *GameServer, user1 *User) (*GameServer, error) {
	setter := &GameServerSetter{
		UserID: omit.From(user1.ID),
	}

	err := gameServer0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachGameServerUser0: %w", err)
	}

	return gameServer0, nil
}

func (gameServer0 *GameServer) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachGameServerUser0(ctx, exec, 1, gameServer0, user1)
	if err != nil {
		return err
	}

	gameServer0.R.User = user1

	user1.R.GameServers = append(user1.R.GameServers, gameServer0)

	return nil
}

func (gameServer0 *GameServer) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachGameServerUser0(ctx, exec, 1, gameServer0, user1)
	if err != nil {
		return err
	}

	gameServer0.R.User = user1

	user1.R.GameServers = append(user1.R.GameServers, gameServer0)

	return nil
}

func insertGameServerLogs0(ctx context.Context, exec bob.Executor, logs1 []*LogSetter, gameServer0 *GameServer) (LogSlice, error) {
	for i := range logs1 {
		logs1[i].GameServerID = omitnull.From(gameServer0.ID)
	}

	ret, err := Logs.Insert(bob.ToMods(logs1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertGameServerLogs0: %w", err)
	}

	return ret, nil
}

func attachGameServerLogs0(ctx context.Context, exec bob.Executor, count int, logs1 LogSlice, gameServer0 *GameServer) (LogSlice, error) {
	setter := &LogSetter{
		GameServerID: omitnull.From(gameServer0.ID),
	}

	err := logs1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachGameServerLogs0: %w", err)
	}

	return logs1, nil
}

func (gameServer0 *GameServer) InsertLogs(ctx context.Context, exec bob.Executor, related ...*LogSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	logs1, err := insertGameServerLogs0(ctx, exec, related, gameServer0)
	if err != nil {
		return err
	}

	gameServer0.R.Logs = append(gameServer0.R.Logs, logs1...)

	for _, rel := range logs1 {
		rel.R.GameServer = gameServer0
	}
	return nil
}

func (gameServer0 *GameServer) AttachLogs(ctx context.Context, exec bob.Executor, related ...*Log) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	logs1 := LogSlice(related)

	_, err = attachGameServerLogs0(ctx, exec, len(related), logs1, gameServer0)
	if err != nil {
		return err
	}

	gameServer0.R.Logs = append(gameServer0.R.Logs, logs1...)

	for _, rel := range related {
		rel.R.GameServer = gameServer0
	}

	return nil
}
