// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
)

// NodeAPIKey is an object representing the database table.
type NodeAPIKey struct {
	ID          string    `db:"id,pk" `
	ServiceName string    `db:"service_name" `
	APIKey      string    `db:"api_key" `
	CreatedAt   time.Time `db:"created_at" `
	UpdatedAt   time.Time `db:"updated_at" `
}

// NodeAPIKeySlice is an alias for a slice of pointers to NodeAPIKey.
// This should almost always be used instead of []*NodeAPIKey.
type NodeAPIKeySlice []*NodeAPIKey

// NodeAPIKeys contains methods to work with the node_api_key table
var NodeAPIKeys = sqlite.NewTablex[*NodeAPIKey, NodeAPIKeySlice, *NodeAPIKeySetter]("", "node_api_key", buildNodeAPIKeyColumns("node_api_key"))

// NodeAPIKeysQuery is a query on the node_api_key table
type NodeAPIKeysQuery = *sqlite.ViewQuery[*NodeAPIKey, NodeAPIKeySlice]

func buildNodeAPIKeyColumns(alias string) nodeAPIKeyColumns {
	return nodeAPIKeyColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "service_name", "api_key", "created_at", "updated_at",
		).WithParent("node_api_key"),
		tableAlias:  alias,
		ID:          sqlite.Quote(alias, "id"),
		ServiceName: sqlite.Quote(alias, "service_name"),
		APIKey:      sqlite.Quote(alias, "api_key"),
		CreatedAt:   sqlite.Quote(alias, "created_at"),
		UpdatedAt:   sqlite.Quote(alias, "updated_at"),
	}
}

type nodeAPIKeyColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          sqlite.Expression
	ServiceName sqlite.Expression
	APIKey      sqlite.Expression
	CreatedAt   sqlite.Expression
	UpdatedAt   sqlite.Expression
}

func (c nodeAPIKeyColumns) Alias() string {
	return c.tableAlias
}

func (nodeAPIKeyColumns) AliasedAs(alias string) nodeAPIKeyColumns {
	return buildNodeAPIKeyColumns(alias)
}

// NodeAPIKeySetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type NodeAPIKeySetter struct {
	ID          omit.Val[string]    `db:"id,pk" `
	ServiceName omit.Val[string]    `db:"service_name" `
	APIKey      omit.Val[string]    `db:"api_key" `
	CreatedAt   omit.Val[time.Time] `db:"created_at" `
	UpdatedAt   omit.Val[time.Time] `db:"updated_at" `
}

func (s NodeAPIKeySetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.ServiceName.IsValue() {
		vals = append(vals, "service_name")
	}
	if s.APIKey.IsValue() {
		vals = append(vals, "api_key")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s NodeAPIKeySetter) Overwrite(t *NodeAPIKey) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.ServiceName.IsValue() {
		t.ServiceName = s.ServiceName.MustGet()
	}
	if s.APIKey.IsValue() {
		t.APIKey = s.APIKey.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *NodeAPIKeySetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return NodeAPIKeys.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 0, 5)
		if s.ID.IsValue() {
			vals = append(vals, sqlite.Arg(s.ID.MustGet()))
		}

		if s.ServiceName.IsValue() {
			vals = append(vals, sqlite.Arg(s.ServiceName.MustGet()))
		}

		if s.APIKey.IsValue() {
			vals = append(vals, sqlite.Arg(s.APIKey.MustGet()))
		}

		if s.CreatedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.CreatedAt.MustGet()))
		}

		if s.UpdatedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.UpdatedAt.MustGet()))
		}

		if len(vals) == 0 {
			vals = append(vals, sqlite.Arg(nil))
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s NodeAPIKeySetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s NodeAPIKeySetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.ServiceName.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "service_name")...),
			sqlite.Arg(s.ServiceName),
		}})
	}

	if s.APIKey.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "api_key")...),
			sqlite.Arg(s.APIKey),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "created_at")...),
			sqlite.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "updated_at")...),
			sqlite.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindNodeAPIKey retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindNodeAPIKey(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*NodeAPIKey, error) {
	if len(cols) == 0 {
		return NodeAPIKeys.Query(
			sm.Where(NodeAPIKeys.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return NodeAPIKeys.Query(
		sm.Where(NodeAPIKeys.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(NodeAPIKeys.Columns.Only(cols...)),
	).One(ctx, exec)
}

// NodeAPIKeyExists checks the presence of a single record by primary key
func NodeAPIKeyExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return NodeAPIKeys.Query(
		sm.Where(NodeAPIKeys.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after NodeAPIKey is retrieved from the database
func (o *NodeAPIKey) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = NodeAPIKeys.AfterSelectHooks.RunHooks(ctx, exec, NodeAPIKeySlice{o})
	case bob.QueryTypeInsert:
		ctx, err = NodeAPIKeys.AfterInsertHooks.RunHooks(ctx, exec, NodeAPIKeySlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = NodeAPIKeys.AfterUpdateHooks.RunHooks(ctx, exec, NodeAPIKeySlice{o})
	case bob.QueryTypeDelete:
		ctx, err = NodeAPIKeys.AfterDeleteHooks.RunHooks(ctx, exec, NodeAPIKeySlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the NodeAPIKey
func (o *NodeAPIKey) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *NodeAPIKey) pkEQ() dialect.Expression {
	return sqlite.Quote("node_api_key", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the NodeAPIKey
func (o *NodeAPIKey) Update(ctx context.Context, exec bob.Executor, s *NodeAPIKeySetter) error {
	v, err := NodeAPIKeys.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single NodeAPIKey record with an executor
func (o *NodeAPIKey) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := NodeAPIKeys.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the NodeAPIKey using the executor
func (o *NodeAPIKey) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := NodeAPIKeys.Query(
		sm.Where(NodeAPIKeys.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after NodeAPIKeySlice is retrieved from the database
func (o NodeAPIKeySlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = NodeAPIKeys.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = NodeAPIKeys.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = NodeAPIKeys.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = NodeAPIKeys.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o NodeAPIKeySlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("node_api_key", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o NodeAPIKeySlice) copyMatchingRows(from ...*NodeAPIKey) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o NodeAPIKeySlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return NodeAPIKeys.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *NodeAPIKey:
				o.copyMatchingRows(retrieved)
			case []*NodeAPIKey:
				o.copyMatchingRows(retrieved...)
			case NodeAPIKeySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a NodeAPIKey or a slice of NodeAPIKey
				// then run the AfterUpdateHooks on the slice
				_, err = NodeAPIKeys.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o NodeAPIKeySlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return NodeAPIKeys.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *NodeAPIKey:
				o.copyMatchingRows(retrieved)
			case []*NodeAPIKey:
				o.copyMatchingRows(retrieved...)
			case NodeAPIKeySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a NodeAPIKey or a slice of NodeAPIKey
				// then run the AfterDeleteHooks on the slice
				_, err = NodeAPIKeys.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o NodeAPIKeySlice) UpdateAll(ctx context.Context, exec bob.Executor, vals NodeAPIKeySetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := NodeAPIKeys.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o NodeAPIKeySlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := NodeAPIKeys.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o NodeAPIKeySlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := NodeAPIKeys.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type nodeAPIKeyWhere[Q sqlite.Filterable] struct {
	ID          sqlite.WhereMod[Q, string]
	ServiceName sqlite.WhereMod[Q, string]
	APIKey      sqlite.WhereMod[Q, string]
	CreatedAt   sqlite.WhereMod[Q, time.Time]
	UpdatedAt   sqlite.WhereMod[Q, time.Time]
}

func (nodeAPIKeyWhere[Q]) AliasedAs(alias string) nodeAPIKeyWhere[Q] {
	return buildNodeAPIKeyWhere[Q](buildNodeAPIKeyColumns(alias))
}

func buildNodeAPIKeyWhere[Q sqlite.Filterable](cols nodeAPIKeyColumns) nodeAPIKeyWhere[Q] {
	return nodeAPIKeyWhere[Q]{
		ID:          sqlite.Where[Q, string](cols.ID),
		ServiceName: sqlite.Where[Q, string](cols.ServiceName),
		APIKey:      sqlite.Where[Q, string](cols.APIKey),
		CreatedAt:   sqlite.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:   sqlite.Where[Q, time.Time](cols.UpdatedAt),
	}
}
