// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// NodeSyncQueue is an object representing the database table.
type NodeSyncQueue struct {
	ID          int64               `db:"id,pk" `
	NodeID      string              `db:"node_id" `
	ActionJSON  string              `db:"action_json" `
	CreatedAt   time.Time           `db:"created_at" `
	SucceededAt null.Val[time.Time] `db:"succeeded_at" `

	R nodeSyncQueueR `db:"-" `
}

// NodeSyncQueueSlice is an alias for a slice of pointers to NodeSyncQueue.
// This should almost always be used instead of []*NodeSyncQueue.
type NodeSyncQueueSlice []*NodeSyncQueue

// NodeSyncQueues contains methods to work with the node_sync_queue table
var NodeSyncQueues = sqlite.NewTablex[*NodeSyncQueue, NodeSyncQueueSlice, *NodeSyncQueueSetter]("", "node_sync_queue", buildNodeSyncQueueColumns("node_sync_queue"))

// NodeSyncQueuesQuery is a query on the node_sync_queue table
type NodeSyncQueuesQuery = *sqlite.ViewQuery[*NodeSyncQueue, NodeSyncQueueSlice]

// nodeSyncQueueR is where relationships are stored.
type nodeSyncQueueR struct {
	Node *Node // fk_node_sync_queue_0
}

func buildNodeSyncQueueColumns(alias string) nodeSyncQueueColumns {
	return nodeSyncQueueColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "node_id", "action_json", "created_at", "succeeded_at",
		).WithParent("node_sync_queue"),
		tableAlias:  alias,
		ID:          sqlite.Quote(alias, "id"),
		NodeID:      sqlite.Quote(alias, "node_id"),
		ActionJSON:  sqlite.Quote(alias, "action_json"),
		CreatedAt:   sqlite.Quote(alias, "created_at"),
		SucceededAt: sqlite.Quote(alias, "succeeded_at"),
	}
}

type nodeSyncQueueColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          sqlite.Expression
	NodeID      sqlite.Expression
	ActionJSON  sqlite.Expression
	CreatedAt   sqlite.Expression
	SucceededAt sqlite.Expression
}

func (c nodeSyncQueueColumns) Alias() string {
	return c.tableAlias
}

func (nodeSyncQueueColumns) AliasedAs(alias string) nodeSyncQueueColumns {
	return buildNodeSyncQueueColumns(alias)
}

// NodeSyncQueueSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type NodeSyncQueueSetter struct {
	ID          omit.Val[int64]         `db:"id,pk" `
	NodeID      omit.Val[string]        `db:"node_id" `
	ActionJSON  omit.Val[string]        `db:"action_json" `
	CreatedAt   omit.Val[time.Time]     `db:"created_at" `
	SucceededAt omitnull.Val[time.Time] `db:"succeeded_at" `
}

func (s NodeSyncQueueSetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.NodeID.IsValue() {
		vals = append(vals, "node_id")
	}
	if s.ActionJSON.IsValue() {
		vals = append(vals, "action_json")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if !s.SucceededAt.IsUnset() {
		vals = append(vals, "succeeded_at")
	}
	return vals
}

func (s NodeSyncQueueSetter) Overwrite(t *NodeSyncQueue) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.NodeID.IsValue() {
		t.NodeID = s.NodeID.MustGet()
	}
	if s.ActionJSON.IsValue() {
		t.ActionJSON = s.ActionJSON.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if !s.SucceededAt.IsUnset() {
		t.SucceededAt = s.SucceededAt.MustGetNull()
	}
}

func (s *NodeSyncQueueSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return NodeSyncQueues.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 0, 5)
		if s.ID.IsValue() {
			vals = append(vals, sqlite.Arg(s.ID.MustGet()))
		}

		if s.NodeID.IsValue() {
			vals = append(vals, sqlite.Arg(s.NodeID.MustGet()))
		}

		if s.ActionJSON.IsValue() {
			vals = append(vals, sqlite.Arg(s.ActionJSON.MustGet()))
		}

		if s.CreatedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.CreatedAt.MustGet()))
		}

		if !s.SucceededAt.IsUnset() {
			vals = append(vals, sqlite.Arg(s.SucceededAt.MustGetNull()))
		}

		if len(vals) == 0 {
			vals = append(vals, sqlite.Arg(nil))
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s NodeSyncQueueSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s NodeSyncQueueSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.NodeID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "node_id")...),
			sqlite.Arg(s.NodeID),
		}})
	}

	if s.ActionJSON.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "action_json")...),
			sqlite.Arg(s.ActionJSON),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "created_at")...),
			sqlite.Arg(s.CreatedAt),
		}})
	}

	if !s.SucceededAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "succeeded_at")...),
			sqlite.Arg(s.SucceededAt),
		}})
	}

	return exprs
}

// FindNodeSyncQueue retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindNodeSyncQueue(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*NodeSyncQueue, error) {
	if len(cols) == 0 {
		return NodeSyncQueues.Query(
			sm.Where(NodeSyncQueues.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return NodeSyncQueues.Query(
		sm.Where(NodeSyncQueues.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(NodeSyncQueues.Columns.Only(cols...)),
	).One(ctx, exec)
}

// NodeSyncQueueExists checks the presence of a single record by primary key
func NodeSyncQueueExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return NodeSyncQueues.Query(
		sm.Where(NodeSyncQueues.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after NodeSyncQueue is retrieved from the database
func (o *NodeSyncQueue) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = NodeSyncQueues.AfterSelectHooks.RunHooks(ctx, exec, NodeSyncQueueSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = NodeSyncQueues.AfterInsertHooks.RunHooks(ctx, exec, NodeSyncQueueSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = NodeSyncQueues.AfterUpdateHooks.RunHooks(ctx, exec, NodeSyncQueueSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = NodeSyncQueues.AfterDeleteHooks.RunHooks(ctx, exec, NodeSyncQueueSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the NodeSyncQueue
func (o *NodeSyncQueue) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *NodeSyncQueue) pkEQ() dialect.Expression {
	return sqlite.Quote("node_sync_queue", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the NodeSyncQueue
func (o *NodeSyncQueue) Update(ctx context.Context, exec bob.Executor, s *NodeSyncQueueSetter) error {
	v, err := NodeSyncQueues.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single NodeSyncQueue record with an executor
func (o *NodeSyncQueue) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := NodeSyncQueues.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the NodeSyncQueue using the executor
func (o *NodeSyncQueue) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := NodeSyncQueues.Query(
		sm.Where(NodeSyncQueues.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after NodeSyncQueueSlice is retrieved from the database
func (o NodeSyncQueueSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = NodeSyncQueues.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = NodeSyncQueues.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = NodeSyncQueues.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = NodeSyncQueues.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o NodeSyncQueueSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("node_sync_queue", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o NodeSyncQueueSlice) copyMatchingRows(from ...*NodeSyncQueue) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o NodeSyncQueueSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return NodeSyncQueues.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *NodeSyncQueue:
				o.copyMatchingRows(retrieved)
			case []*NodeSyncQueue:
				o.copyMatchingRows(retrieved...)
			case NodeSyncQueueSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a NodeSyncQueue or a slice of NodeSyncQueue
				// then run the AfterUpdateHooks on the slice
				_, err = NodeSyncQueues.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o NodeSyncQueueSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return NodeSyncQueues.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *NodeSyncQueue:
				o.copyMatchingRows(retrieved)
			case []*NodeSyncQueue:
				o.copyMatchingRows(retrieved...)
			case NodeSyncQueueSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a NodeSyncQueue or a slice of NodeSyncQueue
				// then run the AfterDeleteHooks on the slice
				_, err = NodeSyncQueues.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o NodeSyncQueueSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals NodeSyncQueueSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := NodeSyncQueues.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o NodeSyncQueueSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := NodeSyncQueues.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o NodeSyncQueueSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := NodeSyncQueues.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Node starts a query for related objects on node
func (o *NodeSyncQueue) Node(mods ...bob.Mod[*dialect.SelectQuery]) NodesQuery {
	return Nodes.Query(append(mods,
		sm.Where(Nodes.Columns.ID.EQ(sqlite.Arg(o.NodeID))),
	)...)
}

func (os NodeSyncQueueSlice) Node(mods ...bob.Mod[*dialect.SelectQuery]) NodesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.NodeID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return Nodes.Query(append(mods,
		sm.Where(sqlite.Group(Nodes.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachNodeSyncQueueNode0(ctx context.Context, exec bob.Executor, count int, nodeSyncQueue0 *NodeSyncQueue, node1 *Node) (*NodeSyncQueue, error) {
	setter := &NodeSyncQueueSetter{
		NodeID: omit.From(node1.ID),
	}

	err := nodeSyncQueue0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachNodeSyncQueueNode0: %w", err)
	}

	return nodeSyncQueue0, nil
}

func (nodeSyncQueue0 *NodeSyncQueue) InsertNode(ctx context.Context, exec bob.Executor, related *NodeSetter) error {
	var err error

	node1, err := Nodes.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachNodeSyncQueueNode0(ctx, exec, 1, nodeSyncQueue0, node1)
	if err != nil {
		return err
	}

	nodeSyncQueue0.R.Node = node1

	node1.R.NodeSyncQueues = append(node1.R.NodeSyncQueues, nodeSyncQueue0)

	return nil
}

func (nodeSyncQueue0 *NodeSyncQueue) AttachNode(ctx context.Context, exec bob.Executor, node1 *Node) error {
	var err error

	_, err = attachNodeSyncQueueNode0(ctx, exec, 1, nodeSyncQueue0, node1)
	if err != nil {
		return err
	}

	nodeSyncQueue0.R.Node = node1

	node1.R.NodeSyncQueues = append(node1.R.NodeSyncQueues, nodeSyncQueue0)

	return nil
}

type nodeSyncQueueWhere[Q sqlite.Filterable] struct {
	ID          sqlite.WhereMod[Q, int64]
	NodeID      sqlite.WhereMod[Q, string]
	ActionJSON  sqlite.WhereMod[Q, string]
	CreatedAt   sqlite.WhereMod[Q, time.Time]
	SucceededAt sqlite.WhereNullMod[Q, time.Time]
}

func (nodeSyncQueueWhere[Q]) AliasedAs(alias string) nodeSyncQueueWhere[Q] {
	return buildNodeSyncQueueWhere[Q](buildNodeSyncQueueColumns(alias))
}

func buildNodeSyncQueueWhere[Q sqlite.Filterable](cols nodeSyncQueueColumns) nodeSyncQueueWhere[Q] {
	return nodeSyncQueueWhere[Q]{
		ID:          sqlite.Where[Q, int64](cols.ID),
		NodeID:      sqlite.Where[Q, string](cols.NodeID),
		ActionJSON:  sqlite.Where[Q, string](cols.ActionJSON),
		CreatedAt:   sqlite.Where[Q, time.Time](cols.CreatedAt),
		SucceededAt: sqlite.WhereNull[Q, time.Time](cols.SucceededAt),
	}
}

func (o *NodeSyncQueue) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Node":
		rel, ok := retrieved.(*Node)
		if !ok {
			return fmt.Errorf("nodeSyncQueue cannot load %T as %q", retrieved, name)
		}

		o.R.Node = rel

		if rel != nil {
			rel.R.NodeSyncQueues = NodeSyncQueueSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("nodeSyncQueue has no relationship %q", name)
	}
}

type nodeSyncQueuePreloader struct {
	Node func(...sqlite.PreloadOption) sqlite.Preloader
}

func buildNodeSyncQueuePreloader() nodeSyncQueuePreloader {
	return nodeSyncQueuePreloader{
		Node: func(opts ...sqlite.PreloadOption) sqlite.Preloader {
			return sqlite.Preload[*Node, NodeSlice](sqlite.PreloadRel{
				Name: "Node",
				Sides: []sqlite.PreloadSide{
					{
						From:        NodeSyncQueues,
						To:          Nodes,
						FromColumns: []string{"node_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Nodes.Columns.Names(), opts...)
		},
	}
}

type nodeSyncQueueThenLoader[Q orm.Loadable] struct {
	Node func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildNodeSyncQueueThenLoader[Q orm.Loadable]() nodeSyncQueueThenLoader[Q] {
	type NodeLoadInterface interface {
		LoadNode(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return nodeSyncQueueThenLoader[Q]{
		Node: thenLoadBuilder[Q](
			"Node",
			func(ctx context.Context, exec bob.Executor, retrieved NodeLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadNode(ctx, exec, mods...)
			},
		),
	}
}

// LoadNode loads the nodeSyncQueue's Node into the .R struct
func (o *NodeSyncQueue) LoadNode(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Node = nil

	related, err := o.Node(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.NodeSyncQueues = NodeSyncQueueSlice{o}

	o.R.Node = related
	return nil
}

// LoadNode loads the nodeSyncQueue's Node into the .R struct
func (os NodeSyncQueueSlice) LoadNode(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	nodes, err := os.Node(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range nodes {

			if !(o.NodeID == rel.ID) {
				continue
			}

			rel.R.NodeSyncQueues = append(rel.R.NodeSyncQueues, o)

			o.R.Node = rel
			break
		}
	}

	return nil
}

type nodeSyncQueueJoins[Q dialect.Joinable] struct {
	typ  string
	Node modAs[Q, nodeColumns]
}

func (j nodeSyncQueueJoins[Q]) aliasedAs(alias string) nodeSyncQueueJoins[Q] {
	return buildNodeSyncQueueJoins[Q](buildNodeSyncQueueColumns(alias), j.typ)
}

func buildNodeSyncQueueJoins[Q dialect.Joinable](cols nodeSyncQueueColumns, typ string) nodeSyncQueueJoins[Q] {
	return nodeSyncQueueJoins[Q]{
		typ: typ,
		Node: modAs[Q, nodeColumns]{
			c: Nodes.Columns,
			f: func(to nodeColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Nodes.Name().As(to.Alias())).On(
						to.ID.EQ(cols.NodeID),
					))
				}

				return mods
			},
		},
	}
}
