// Code generated by BobGen sqlite v0.48.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/scan"
)

// NotificationChannel is an object representing the database table.
type NotificationChannel struct {
	ID          string    `db:"id,pk" `
	UserID      string    `db:"user_id" `
	Name        string    `db:"name" `
	ChannelType string    `db:"channel_type" `
	Config      string    `db:"config" `
	Enabled     int64     `db:"enabled" `
	CreatedAt   time.Time `db:"created_at" `
	UpdatedAt   time.Time `db:"updated_at" `

	R notificationChannelR `db:"-" `

	C notificationChannelC `db:"-" `
}

// NotificationChannelSlice is an alias for a slice of pointers to NotificationChannel.
// This should almost always be used instead of []*NotificationChannel.
type NotificationChannelSlice []*NotificationChannel

// NotificationChannels contains methods to work with the notification_channel table
var NotificationChannels = sqlite.NewTablex[*NotificationChannel, NotificationChannelSlice, *NotificationChannelSetter]("", "notification_channel", buildNotificationChannelColumns("notification_channel"))

// NotificationChannelsQuery is a query on the notification_channel table
type NotificationChannelsQuery = *sqlite.ViewQuery[*NotificationChannel, NotificationChannelSlice]

// notificationChannelR is where relationships are stored.
type notificationChannelR struct {
	AlertRules AlertRuleSlice // fk_alert_rule_0
	User       *User          // fk_notification_channel_0
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded notificationChannelRLoaded `db:"-" `
}

// notificationChannelRLoaded tracks which relationships on NotificationChannel have been loaded.
type notificationChannelRLoaded struct {
	AlertRules bool // fk_alert_rule_0
	User       bool // fk_notification_channel_0
}

func buildNotificationChannelColumns(tableName string) notificationChannelColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "user_id", "name", "channel_type", "config", "enabled", "created_at", "updated_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return notificationChannelColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          buildNotificationChannelColumn(tableName, "id"),
		UserID:      buildNotificationChannelColumn(tableName, "user_id"),
		Name:        buildNotificationChannelColumn(tableName, "name"),
		ChannelType: buildNotificationChannelColumn(tableName, "channel_type"),
		Config:      buildNotificationChannelColumn(tableName, "config"),
		Enabled:     buildNotificationChannelColumn(tableName, "enabled"),
		CreatedAt:   buildNotificationChannelColumn(tableName, "created_at"),
		UpdatedAt:   buildNotificationChannelColumn(tableName, "updated_at"),
	}
}

type notificationChannelColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          notificationChannelColumn
	UserID      notificationChannelColumn
	Name        notificationChannelColumn
	ChannelType notificationChannelColumn
	Config      notificationChannelColumn
	Enabled     notificationChannelColumn
	CreatedAt   notificationChannelColumn
	UpdatedAt   notificationChannelColumn
}

// Alias returns the current table alias for the columns set.
func (c notificationChannelColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (notificationChannelColumns) AliasedAs(tableName string) notificationChannelColumns {
	return buildNotificationChannelColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c notificationChannelColumns) Unqualified() notificationChannelColumns {
	return buildNotificationChannelColumns("")
}

func buildNotificationChannelColumn(alias, name string) notificationChannelColumn {
	return notificationChannelColumn{
		Expression: sqlite.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type notificationChannelColumn struct {
	sqlite.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c notificationChannelColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c notificationChannelColumn) ShouldOmitParens() bool {
	return true
}

// NotificationChannelSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type NotificationChannelSetter struct {
	ID          omit.Val[string]    `db:"id,pk" `
	UserID      omit.Val[string]    `db:"user_id" `
	Name        omit.Val[string]    `db:"name" `
	ChannelType omit.Val[string]    `db:"channel_type" `
	Config      omit.Val[string]    `db:"config" `
	Enabled     omit.Val[int64]     `db:"enabled" `
	CreatedAt   omit.Val[time.Time] `db:"created_at" `
	UpdatedAt   omit.Val[time.Time] `db:"updated_at" `
}

func (s NotificationChannelSetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.ChannelType.IsValue() {
		vals = append(vals, "channel_type")
	}
	if s.Config.IsValue() {
		vals = append(vals, "config")
	}
	if s.Enabled.IsValue() {
		vals = append(vals, "enabled")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s NotificationChannelSetter) Overwrite(t *NotificationChannel) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.ChannelType.IsValue() {
		t.ChannelType = s.ChannelType.MustGet()
	}
	if s.Config.IsValue() {
		t.Config = s.Config.MustGet()
	}
	if s.Enabled.IsValue() {
		t.Enabled = s.Enabled.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *NotificationChannelSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return NotificationChannels.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	vals := make([]bob.Expression, 0, len(q.TableRef.Columns))
	for _, col := range q.TableRef.Columns {
		switch col {
		case "id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ID.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "user_id":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.UserID.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.UserID.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "name":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Name.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.Name.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "channel_type":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.ChannelType.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.ChannelType.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "config":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Config.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.Config.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "enabled":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.Enabled.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.Enabled.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "created_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.CreatedAt.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		case "updated_at":
			vals = append(vals, bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
				if s.UpdatedAt.IsUnset() {
					return sqlite.Arg(nil).WriteSQL(ctx, w, d, start)
				}
				return sqlite.Arg(s.UpdatedAt.MustGet()).WriteSQL(ctx, w, d, start)
			}))
		}
	}

	q.AppendValues(vals...)
}

func (s NotificationChannelSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s NotificationChannelSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "user_id")...),
			sqlite.Arg(s.UserID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "name")...),
			sqlite.Arg(s.Name),
		}})
	}

	if s.ChannelType.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "channel_type")...),
			sqlite.Arg(s.ChannelType),
		}})
	}

	if s.Config.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "config")...),
			sqlite.Arg(s.Config),
		}})
	}

	if s.Enabled.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "enabled")...),
			sqlite.Arg(s.Enabled),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "created_at")...),
			sqlite.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "updated_at")...),
			sqlite.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindNotificationChannel retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindNotificationChannel(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*NotificationChannel, error) {
	if len(cols) == 0 {
		return NotificationChannels.Query(
			sm.Where(NotificationChannels.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return NotificationChannels.Query(
		sm.Where(NotificationChannels.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(NotificationChannels.Columns.Only(cols...)),
	).One(ctx, exec)
}

// NotificationChannelExists checks the presence of a single record by primary key
func NotificationChannelExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return NotificationChannels.Query(
		sm.Where(NotificationChannels.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after NotificationChannel is retrieved from the database
func (o *NotificationChannel) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = NotificationChannels.AfterSelectHooks.RunHooks(ctx, exec, NotificationChannelSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = NotificationChannels.AfterInsertHooks.RunHooks(ctx, exec, NotificationChannelSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = NotificationChannels.AfterUpdateHooks.RunHooks(ctx, exec, NotificationChannelSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = NotificationChannels.AfterDeleteHooks.RunHooks(ctx, exec, NotificationChannelSlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the NotificationChannel
func (o *NotificationChannel) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *NotificationChannel) pkEQ() dialect.Expression {
	return sqlite.Quote("notification_channel", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the NotificationChannel
func (o *NotificationChannel) Update(ctx context.Context, exec bob.Executor, s *NotificationChannelSetter) error {
	v, err := NotificationChannels.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single NotificationChannel record with an executor
func (o *NotificationChannel) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := NotificationChannels.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the NotificationChannel using the executor
func (o *NotificationChannel) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := NotificationChannels.Query(
		sm.Where(NotificationChannels.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after NotificationChannelSlice is retrieved from the database
func (o NotificationChannelSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = NotificationChannels.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = NotificationChannels.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = NotificationChannels.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = NotificationChannels.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o NotificationChannelSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("notification_channel", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o NotificationChannelSlice) copyMatchingRows(from ...*NotificationChannel) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o NotificationChannelSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return NotificationChannels.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *NotificationChannel:
				o.copyMatchingRows(retrieved)
			case []*NotificationChannel:
				o.copyMatchingRows(retrieved...)
			case NotificationChannelSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a NotificationChannel or a slice of NotificationChannel
				// then run the AfterUpdateHooks on the slice
				_, err = NotificationChannels.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o NotificationChannelSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return NotificationChannels.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *NotificationChannel:
				o.copyMatchingRows(retrieved)
			case []*NotificationChannel:
				o.copyMatchingRows(retrieved...)
			case NotificationChannelSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a NotificationChannel or a slice of NotificationChannel
				// then run the AfterDeleteHooks on the slice
				_, err = NotificationChannels.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o NotificationChannelSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals NotificationChannelSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := NotificationChannels.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o NotificationChannelSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := NotificationChannels.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o NotificationChannelSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := NotificationChannels.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// AlertRules starts a query for related objects on alert_rule
func (o *NotificationChannel) AlertRules(mods ...bob.Mod[*dialect.SelectQuery]) AlertRulesQuery {
	return AlertRules.Query(append(mods,
		sm.Where(AlertRules.Columns.NotificationChannelID.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os NotificationChannelSlice) AlertRules(mods ...bob.Mod[*dialect.SelectQuery]) AlertRulesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return AlertRules.Query(append(mods,
		sm.Where(sqlite.Group(AlertRules.Columns.NotificationChannelID).OP("IN", PKArgExpr)),
	)...)
}

// User starts a query for related objects on user
func (o *NotificationChannel) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(sqlite.Arg(o.UserID))),
	)...)
}

func (os NotificationChannelSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.UserID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return Users.Query(append(mods,
		sm.Where(sqlite.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func insertNotificationChannelAlertRules0(ctx context.Context, exec bob.Executor, alertRules1 []*AlertRuleSetter, notificationChannel0 *NotificationChannel) (AlertRuleSlice, error) {
	for i := range alertRules1 {
		alertRules1[i].NotificationChannelID = omit.From(notificationChannel0.ID)
	}

	ret, err := AlertRules.Insert(bob.ToMods(alertRules1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertNotificationChannelAlertRules0: %w", err)
	}

	return ret, nil
}

func attachNotificationChannelAlertRules0(ctx context.Context, exec bob.Executor, count int, alertRules1 AlertRuleSlice, notificationChannel0 *NotificationChannel) (AlertRuleSlice, error) {
	setter := &AlertRuleSetter{
		NotificationChannelID: omit.From(notificationChannel0.ID),
	}

	err := alertRules1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachNotificationChannelAlertRules0: %w", err)
	}

	return alertRules1, nil
}

func (notificationChannel0 *NotificationChannel) InsertAlertRules(ctx context.Context, exec bob.Executor, related ...*AlertRuleSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	alertRules1, err := insertNotificationChannelAlertRules0(ctx, exec, related, notificationChannel0)
	if err != nil {
		return err
	}

	notificationChannel0.R.AlertRules = append(notificationChannel0.R.AlertRules, alertRules1...)

	for _, rel := range alertRules1 {
		rel.R.NotificationChannel = notificationChannel0
		rel.R.Loaded.NotificationChannel = true
	}
	return nil
}

func (notificationChannel0 *NotificationChannel) AttachAlertRules(ctx context.Context, exec bob.Executor, related ...*AlertRule) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	alertRules1 := AlertRuleSlice(related)

	_, err = attachNotificationChannelAlertRules0(ctx, exec, len(related), alertRules1, notificationChannel0)
	if err != nil {
		return err
	}

	notificationChannel0.R.AlertRules = append(notificationChannel0.R.AlertRules, alertRules1...)

	for _, rel := range related {
		rel.R.NotificationChannel = notificationChannel0
		rel.R.Loaded.NotificationChannel = true
	}

	return nil
}

func attachNotificationChannelUser0(ctx context.Context, exec bob.Executor, count int, notificationChannel0 *NotificationChannel, user1 *User) (*NotificationChannel, error) {
	setter := &NotificationChannelSetter{
		UserID: omit.From(user1.ID),
	}

	err := notificationChannel0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachNotificationChannelUser0: %w", err)
	}

	return notificationChannel0, nil
}

func (notificationChannel0 *NotificationChannel) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachNotificationChannelUser0(ctx, exec, 1, notificationChannel0, user1)
	if err != nil {
		return err
	}

	notificationChannel0.R.User = user1
	notificationChannel0.R.Loaded.User = true

	user1.R.NotificationChannels = append(user1.R.NotificationChannels, notificationChannel0)

	return nil
}

func (notificationChannel0 *NotificationChannel) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachNotificationChannelUser0(ctx, exec, 1, notificationChannel0, user1)
	if err != nil {
		return err
	}

	notificationChannel0.R.User = user1
	notificationChannel0.R.Loaded.User = true

	user1.R.NotificationChannels = append(user1.R.NotificationChannels, notificationChannel0)

	return nil
}

type notificationChannelWhere[Q sqlite.Filterable] struct {
	ID          sqlite.WhereMod[Q, string]
	UserID      sqlite.WhereMod[Q, string]
	Name        sqlite.WhereMod[Q, string]
	ChannelType sqlite.WhereMod[Q, string]
	Config      sqlite.WhereMod[Q, string]
	Enabled     sqlite.WhereMod[Q, int64]
	CreatedAt   sqlite.WhereMod[Q, time.Time]
	UpdatedAt   sqlite.WhereMod[Q, time.Time]
}

func (notificationChannelWhere[Q]) AliasedAs(alias string) notificationChannelWhere[Q] {
	return buildNotificationChannelWhere[Q](buildNotificationChannelColumns(alias))
}

func buildNotificationChannelWhere[Q sqlite.Filterable](cols notificationChannelColumns) notificationChannelWhere[Q] {
	return notificationChannelWhere[Q]{
		ID:          sqlite.Where[Q, string](cols.ID.Expression),
		UserID:      sqlite.Where[Q, string](cols.UserID.Expression),
		Name:        sqlite.Where[Q, string](cols.Name.Expression),
		ChannelType: sqlite.Where[Q, string](cols.ChannelType.Expression),
		Config:      sqlite.Where[Q, string](cols.Config.Expression),
		Enabled:     sqlite.Where[Q, int64](cols.Enabled.Expression),
		CreatedAt:   sqlite.Where[Q, time.Time](cols.CreatedAt.Expression),
		UpdatedAt:   sqlite.Where[Q, time.Time](cols.UpdatedAt.Expression),
	}
}

func (o *NotificationChannel) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "AlertRules":
		rels, ok := retrieved.(AlertRuleSlice)
		if !ok {
			return fmt.Errorf("notificationChannel cannot load %T as %q", retrieved, name)
		}

		o.R.AlertRules = rels
		o.R.Loaded.AlertRules = true

		for _, rel := range rels {
			if rel != nil {
				rel.R.NotificationChannel = o
				rel.R.Loaded.NotificationChannel = true
			}
		}
		return nil
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("notificationChannel cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel
		o.R.Loaded.User = true

		if rel != nil {
			rel.R.NotificationChannels = NotificationChannelSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("notificationChannel has no relationship %q", name)
	}
}

type notificationChannelPreloader struct {
	User func(...sqlite.PreloadOption) sqlite.Preloader
}

func buildNotificationChannelPreloader() notificationChannelPreloader {
	return notificationChannelPreloader{
		User: func(opts ...sqlite.PreloadOption) sqlite.Preloader {
			return sqlite.Preload[*User, UserSlice](sqlite.PreloadRel{
				Name: "User",
				Sides: []sqlite.PreloadSide{
					{
						From:        NotificationChannels,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type notificationChannelThenLoader[Q orm.Loadable] struct {
	AlertRules func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	User       func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildNotificationChannelThenLoader[Q orm.Loadable]() notificationChannelThenLoader[Q] {
	type AlertRulesLoadInterface interface {
		LoadAlertRules(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return notificationChannelThenLoader[Q]{
		AlertRules: thenLoadBuilder[Q](
			"AlertRules",
			func(ctx context.Context, exec bob.Executor, retrieved AlertRulesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadAlertRules(ctx, exec, mods...)
			},
		),
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadAlertRules loads the notificationChannel's AlertRules into the .R struct
func (o *NotificationChannel) LoadAlertRules(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.AlertRules = nil
	o.R.Loaded.AlertRules = false

	related, err := o.AlertRules(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.NotificationChannel = o
		rel.R.Loaded.NotificationChannel = true
	}

	o.R.AlertRules = related
	o.R.Loaded.AlertRules = true
	return nil
}

// LoadAlertRules loads the notificationChannel's AlertRules into the .R struct
func (os NotificationChannelSlice) LoadAlertRules(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	alertRules, err := os.AlertRules(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.AlertRules = nil
		o.R.Loaded.AlertRules = true
	}
	// O(N+M) stitch via a map keyed by the join column (key -> []parent; was O(N*M)).
	notificationChannelByKey := make(map[string][]*NotificationChannel, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}

		notificationChannelByKey[o.ID] = append(notificationChannelByKey[o.ID], o)
	}

	for _, rel := range alertRules {

		owners, ok := notificationChannelByKey[rel.NotificationChannelID]
		if !ok {
			continue
		}

		for _, o := range owners {

			rel.R.NotificationChannel = o
			rel.R.Loaded.NotificationChannel = true

			o.R.AlertRules = append(o.R.AlertRules, rel)

		}
	}

	return nil
}

// LoadUser loads the notificationChannel's User into the .R struct
func (o *NotificationChannel) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil
	o.R.Loaded.User = false

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.NotificationChannels = NotificationChannelSlice{o}

	o.R.User = related
	o.R.Loaded.User = true
	return nil
}

// LoadUser loads the notificationChannel's User into the .R struct
func (os NotificationChannelSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.User = nil
		o.R.Loaded.User = true
	}
	// O(N+M) stitch via a map keyed by the join column (key -> []parent; was O(N*M)).
	notificationChannelByKey := make(map[string][]*NotificationChannel, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}

		notificationChannelByKey[o.UserID] = append(notificationChannelByKey[o.UserID], o)
	}

	for _, rel := range users {

		owners, ok := notificationChannelByKey[rel.ID]
		if !ok {
			continue
		}

		for _, o := range owners {

			// to-one: keep only the first matching child (matches the previous break)
			if o.R.User != nil {
				continue
			}

			rel.R.NotificationChannels = append(rel.R.NotificationChannels, o)

			o.R.User = rel

		}
	}

	return nil
}

// notificationChannelC is where relationship counts are stored.
type notificationChannelC struct {
	AlertRules *int64
}

// PreloadCount sets a count in the C struct by name
func (o *NotificationChannel) PreloadCount(name string, count int64) error {
	if o == nil {
		return nil
	}

	switch name {
	case "AlertRules":
		o.C.AlertRules = &count
	}
	return nil
}

type notificationChannelCountPreloader struct {
	AlertRules func(...bob.Mod[*dialect.SelectQuery]) sqlite.Preloader
}

func buildNotificationChannelCountPreloader() notificationChannelCountPreloader {
	return notificationChannelCountPreloader{
		AlertRules: func(mods ...bob.Mod[*dialect.SelectQuery]) sqlite.Preloader {
			return countPreloader[*NotificationChannel]("AlertRules", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = NotificationChannels.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(sqlite.Raw("count(*)")),

					sm.From(AlertRules.NameAsExpr()),
					sm.Where(sqlite.Quote(AlertRules.Alias(), "notification_channel_id").EQ(sqlite.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return sqlite.Group(sqlite.Select(subqueryMods...).Expression)
			})
		},
	}
}

type notificationChannelCountThenLoader[Q orm.Loadable] struct {
	AlertRules func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildNotificationChannelCountThenLoader[Q orm.Loadable]() notificationChannelCountThenLoader[Q] {
	type AlertRulesCountInterface interface {
		LoadCountAlertRules(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return notificationChannelCountThenLoader[Q]{
		AlertRules: countThenLoadBuilder[Q](
			"AlertRules",
			func(ctx context.Context, exec bob.Executor, retrieved AlertRulesCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountAlertRules(ctx, exec, mods...)
			},
		),
	}
}

// LoadCountAlertRules loads the count of AlertRules into the C struct
func (o *NotificationChannel) LoadCountAlertRules(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.AlertRules(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.AlertRules = &count
	return nil
}

// LoadCountAlertRules loads the count of AlertRules for a slice in a single batch query
func (os NotificationChannelSlice) LoadCountAlertRules(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs
	PKArgSlice := make([]bob.Expression, 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		PKArgSlice = append(PKArgSlice, sqlite.Arg(o.ID))
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			AlertRules.Columns.NotificationChannelID.As("id"),
			sqlite.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(AlertRules.NameAsExpr()),

		// WHERE fk IN (parent PKs) — psql single-column FK uses `= ANY(array)` (see PKArgExpr above)
		sm.Where(AlertRules.Columns.NotificationChannelID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(AlertRules.Columns.NotificationChannelID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		sqlite.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.AlertRules = &count
	}

	return nil
}

type notificationChannelJoins[Q dialect.Joinable] struct {
	typ        string
	AlertRules modAs[Q, alertRuleColumns]
	User       modAs[Q, userColumns]
}

func (j notificationChannelJoins[Q]) aliasedAs(alias string) notificationChannelJoins[Q] {
	return buildNotificationChannelJoins[Q](buildNotificationChannelColumns(alias), j.typ)
}

func buildNotificationChannelJoins[Q dialect.Joinable](cols notificationChannelColumns, typ string) notificationChannelJoins[Q] {
	return notificationChannelJoins[Q]{
		typ: typ,
		AlertRules: modAs[Q, alertRuleColumns]{
			c: AlertRules.Columns,
			f: func(to alertRuleColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, AlertRules.NameExpr().As(to.Alias())).On(
						to.NotificationChannelID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.NameExpr().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
