// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// SystemUpdateJob is an object representing the database table.
type SystemUpdateJob struct {
	ID                string              `db:"id,pk" `
	Component         string              `db:"component" `
	NodeID            null.Val[string]    `db:"node_id" `
	CurrentVersion    string              `db:"current_version" `
	TargetVersion     string              `db:"target_version" `
	Status            string              `db:"status" `
	Phase             string              `db:"phase" `
	ProgressPercent   int64               `db:"progress_percent" `
	Error             null.Val[string]    `db:"error" `
	ArtifactName      null.Val[string]    `db:"artifact_name" `
	ArtifactSha256    null.Val[string]    `db:"artifact_sha256" `
	RequestedByUserID null.Val[string]    `db:"requested_by_user_id" `
	CreatedAt         time.Time           `db:"created_at" `
	UpdatedAt         time.Time           `db:"updated_at" `
	StartedAt         null.Val[time.Time] `db:"started_at" `
	CompletedAt       null.Val[time.Time] `db:"completed_at" `

	R systemUpdateJobR `db:"-" `
}

// SystemUpdateJobSlice is an alias for a slice of pointers to SystemUpdateJob.
// This should almost always be used instead of []*SystemUpdateJob.
type SystemUpdateJobSlice []*SystemUpdateJob

// SystemUpdateJobs contains methods to work with the system_update_job table
var SystemUpdateJobs = sqlite.NewTablex[*SystemUpdateJob, SystemUpdateJobSlice, *SystemUpdateJobSetter]("", "system_update_job", buildSystemUpdateJobColumns("system_update_job"))

// SystemUpdateJobsQuery is a query on the system_update_job table
type SystemUpdateJobsQuery = *sqlite.ViewQuery[*SystemUpdateJob, SystemUpdateJobSlice]

// systemUpdateJobR is where relationships are stored.
type systemUpdateJobR struct {
	RequestedByUserUser      *User                     // fk_system_update_job_0
	Node                     *Node                     // fk_system_update_job_1
	JobSystemUpdateJobEvents SystemUpdateJobEventSlice // fk_system_update_job_event_0
}

func buildSystemUpdateJobColumns(alias string) systemUpdateJobColumns {
	return systemUpdateJobColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "component", "node_id", "current_version", "target_version", "status", "phase", "progress_percent", "error", "artifact_name", "artifact_sha256", "requested_by_user_id", "created_at", "updated_at", "started_at", "completed_at",
		).WithParent("system_update_job"),
		tableAlias:        alias,
		ID:                sqlite.Quote(alias, "id"),
		Component:         sqlite.Quote(alias, "component"),
		NodeID:            sqlite.Quote(alias, "node_id"),
		CurrentVersion:    sqlite.Quote(alias, "current_version"),
		TargetVersion:     sqlite.Quote(alias, "target_version"),
		Status:            sqlite.Quote(alias, "status"),
		Phase:             sqlite.Quote(alias, "phase"),
		ProgressPercent:   sqlite.Quote(alias, "progress_percent"),
		Error:             sqlite.Quote(alias, "error"),
		ArtifactName:      sqlite.Quote(alias, "artifact_name"),
		ArtifactSha256:    sqlite.Quote(alias, "artifact_sha256"),
		RequestedByUserID: sqlite.Quote(alias, "requested_by_user_id"),
		CreatedAt:         sqlite.Quote(alias, "created_at"),
		UpdatedAt:         sqlite.Quote(alias, "updated_at"),
		StartedAt:         sqlite.Quote(alias, "started_at"),
		CompletedAt:       sqlite.Quote(alias, "completed_at"),
	}
}

type systemUpdateJobColumns struct {
	expr.ColumnsExpr
	tableAlias        string
	ID                sqlite.Expression
	Component         sqlite.Expression
	NodeID            sqlite.Expression
	CurrentVersion    sqlite.Expression
	TargetVersion     sqlite.Expression
	Status            sqlite.Expression
	Phase             sqlite.Expression
	ProgressPercent   sqlite.Expression
	Error             sqlite.Expression
	ArtifactName      sqlite.Expression
	ArtifactSha256    sqlite.Expression
	RequestedByUserID sqlite.Expression
	CreatedAt         sqlite.Expression
	UpdatedAt         sqlite.Expression
	StartedAt         sqlite.Expression
	CompletedAt       sqlite.Expression
}

func (c systemUpdateJobColumns) Alias() string {
	return c.tableAlias
}

func (systemUpdateJobColumns) AliasedAs(alias string) systemUpdateJobColumns {
	return buildSystemUpdateJobColumns(alias)
}

// SystemUpdateJobSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type SystemUpdateJobSetter struct {
	ID                omit.Val[string]        `db:"id,pk" `
	Component         omit.Val[string]        `db:"component" `
	NodeID            omitnull.Val[string]    `db:"node_id" `
	CurrentVersion    omit.Val[string]        `db:"current_version" `
	TargetVersion     omit.Val[string]        `db:"target_version" `
	Status            omit.Val[string]        `db:"status" `
	Phase             omit.Val[string]        `db:"phase" `
	ProgressPercent   omit.Val[int64]         `db:"progress_percent" `
	Error             omitnull.Val[string]    `db:"error" `
	ArtifactName      omitnull.Val[string]    `db:"artifact_name" `
	ArtifactSha256    omitnull.Val[string]    `db:"artifact_sha256" `
	RequestedByUserID omitnull.Val[string]    `db:"requested_by_user_id" `
	CreatedAt         omit.Val[time.Time]     `db:"created_at" `
	UpdatedAt         omit.Val[time.Time]     `db:"updated_at" `
	StartedAt         omitnull.Val[time.Time] `db:"started_at" `
	CompletedAt       omitnull.Val[time.Time] `db:"completed_at" `
}

func (s SystemUpdateJobSetter) SetColumns() []string {
	vals := make([]string, 0, 16)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Component.IsValue() {
		vals = append(vals, "component")
	}
	if !s.NodeID.IsUnset() {
		vals = append(vals, "node_id")
	}
	if s.CurrentVersion.IsValue() {
		vals = append(vals, "current_version")
	}
	if s.TargetVersion.IsValue() {
		vals = append(vals, "target_version")
	}
	if s.Status.IsValue() {
		vals = append(vals, "status")
	}
	if s.Phase.IsValue() {
		vals = append(vals, "phase")
	}
	if s.ProgressPercent.IsValue() {
		vals = append(vals, "progress_percent")
	}
	if !s.Error.IsUnset() {
		vals = append(vals, "error")
	}
	if !s.ArtifactName.IsUnset() {
		vals = append(vals, "artifact_name")
	}
	if !s.ArtifactSha256.IsUnset() {
		vals = append(vals, "artifact_sha256")
	}
	if !s.RequestedByUserID.IsUnset() {
		vals = append(vals, "requested_by_user_id")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	if !s.StartedAt.IsUnset() {
		vals = append(vals, "started_at")
	}
	if !s.CompletedAt.IsUnset() {
		vals = append(vals, "completed_at")
	}
	return vals
}

func (s SystemUpdateJobSetter) Overwrite(t *SystemUpdateJob) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Component.IsValue() {
		t.Component = s.Component.MustGet()
	}
	if !s.NodeID.IsUnset() {
		t.NodeID = s.NodeID.MustGetNull()
	}
	if s.CurrentVersion.IsValue() {
		t.CurrentVersion = s.CurrentVersion.MustGet()
	}
	if s.TargetVersion.IsValue() {
		t.TargetVersion = s.TargetVersion.MustGet()
	}
	if s.Status.IsValue() {
		t.Status = s.Status.MustGet()
	}
	if s.Phase.IsValue() {
		t.Phase = s.Phase.MustGet()
	}
	if s.ProgressPercent.IsValue() {
		t.ProgressPercent = s.ProgressPercent.MustGet()
	}
	if !s.Error.IsUnset() {
		t.Error = s.Error.MustGetNull()
	}
	if !s.ArtifactName.IsUnset() {
		t.ArtifactName = s.ArtifactName.MustGetNull()
	}
	if !s.ArtifactSha256.IsUnset() {
		t.ArtifactSha256 = s.ArtifactSha256.MustGetNull()
	}
	if !s.RequestedByUserID.IsUnset() {
		t.RequestedByUserID = s.RequestedByUserID.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
	if !s.StartedAt.IsUnset() {
		t.StartedAt = s.StartedAt.MustGetNull()
	}
	if !s.CompletedAt.IsUnset() {
		t.CompletedAt = s.CompletedAt.MustGetNull()
	}
}

func (s *SystemUpdateJobSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return SystemUpdateJobs.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 0, 16)
		if s.ID.IsValue() {
			vals = append(vals, sqlite.Arg(s.ID.MustGet()))
		}

		if s.Component.IsValue() {
			vals = append(vals, sqlite.Arg(s.Component.MustGet()))
		}

		if !s.NodeID.IsUnset() {
			vals = append(vals, sqlite.Arg(s.NodeID.MustGetNull()))
		}

		if s.CurrentVersion.IsValue() {
			vals = append(vals, sqlite.Arg(s.CurrentVersion.MustGet()))
		}

		if s.TargetVersion.IsValue() {
			vals = append(vals, sqlite.Arg(s.TargetVersion.MustGet()))
		}

		if s.Status.IsValue() {
			vals = append(vals, sqlite.Arg(s.Status.MustGet()))
		}

		if s.Phase.IsValue() {
			vals = append(vals, sqlite.Arg(s.Phase.MustGet()))
		}

		if s.ProgressPercent.IsValue() {
			vals = append(vals, sqlite.Arg(s.ProgressPercent.MustGet()))
		}

		if !s.Error.IsUnset() {
			vals = append(vals, sqlite.Arg(s.Error.MustGetNull()))
		}

		if !s.ArtifactName.IsUnset() {
			vals = append(vals, sqlite.Arg(s.ArtifactName.MustGetNull()))
		}

		if !s.ArtifactSha256.IsUnset() {
			vals = append(vals, sqlite.Arg(s.ArtifactSha256.MustGetNull()))
		}

		if !s.RequestedByUserID.IsUnset() {
			vals = append(vals, sqlite.Arg(s.RequestedByUserID.MustGetNull()))
		}

		if s.CreatedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.CreatedAt.MustGet()))
		}

		if s.UpdatedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.UpdatedAt.MustGet()))
		}

		if !s.StartedAt.IsUnset() {
			vals = append(vals, sqlite.Arg(s.StartedAt.MustGetNull()))
		}

		if !s.CompletedAt.IsUnset() {
			vals = append(vals, sqlite.Arg(s.CompletedAt.MustGetNull()))
		}

		if len(vals) == 0 {
			vals = append(vals, sqlite.Arg(nil))
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s SystemUpdateJobSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s SystemUpdateJobSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 16)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if s.Component.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "component")...),
			sqlite.Arg(s.Component),
		}})
	}

	if !s.NodeID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "node_id")...),
			sqlite.Arg(s.NodeID),
		}})
	}

	if s.CurrentVersion.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "current_version")...),
			sqlite.Arg(s.CurrentVersion),
		}})
	}

	if s.TargetVersion.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "target_version")...),
			sqlite.Arg(s.TargetVersion),
		}})
	}

	if s.Status.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "status")...),
			sqlite.Arg(s.Status),
		}})
	}

	if s.Phase.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "phase")...),
			sqlite.Arg(s.Phase),
		}})
	}

	if s.ProgressPercent.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "progress_percent")...),
			sqlite.Arg(s.ProgressPercent),
		}})
	}

	if !s.Error.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "error")...),
			sqlite.Arg(s.Error),
		}})
	}

	if !s.ArtifactName.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "artifact_name")...),
			sqlite.Arg(s.ArtifactName),
		}})
	}

	if !s.ArtifactSha256.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "artifact_sha256")...),
			sqlite.Arg(s.ArtifactSha256),
		}})
	}

	if !s.RequestedByUserID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "requested_by_user_id")...),
			sqlite.Arg(s.RequestedByUserID),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "created_at")...),
			sqlite.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "updated_at")...),
			sqlite.Arg(s.UpdatedAt),
		}})
	}

	if !s.StartedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "started_at")...),
			sqlite.Arg(s.StartedAt),
		}})
	}

	if !s.CompletedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "completed_at")...),
			sqlite.Arg(s.CompletedAt),
		}})
	}

	return exprs
}

// FindSystemUpdateJob retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindSystemUpdateJob(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*SystemUpdateJob, error) {
	if len(cols) == 0 {
		return SystemUpdateJobs.Query(
			sm.Where(SystemUpdateJobs.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return SystemUpdateJobs.Query(
		sm.Where(SystemUpdateJobs.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(SystemUpdateJobs.Columns.Only(cols...)),
	).One(ctx, exec)
}

// SystemUpdateJobExists checks the presence of a single record by primary key
func SystemUpdateJobExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return SystemUpdateJobs.Query(
		sm.Where(SystemUpdateJobs.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after SystemUpdateJob is retrieved from the database
func (o *SystemUpdateJob) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = SystemUpdateJobs.AfterSelectHooks.RunHooks(ctx, exec, SystemUpdateJobSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = SystemUpdateJobs.AfterInsertHooks.RunHooks(ctx, exec, SystemUpdateJobSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = SystemUpdateJobs.AfterUpdateHooks.RunHooks(ctx, exec, SystemUpdateJobSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = SystemUpdateJobs.AfterDeleteHooks.RunHooks(ctx, exec, SystemUpdateJobSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the SystemUpdateJob
func (o *SystemUpdateJob) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *SystemUpdateJob) pkEQ() dialect.Expression {
	return sqlite.Quote("system_update_job", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the SystemUpdateJob
func (o *SystemUpdateJob) Update(ctx context.Context, exec bob.Executor, s *SystemUpdateJobSetter) error {
	v, err := SystemUpdateJobs.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single SystemUpdateJob record with an executor
func (o *SystemUpdateJob) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := SystemUpdateJobs.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the SystemUpdateJob using the executor
func (o *SystemUpdateJob) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := SystemUpdateJobs.Query(
		sm.Where(SystemUpdateJobs.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after SystemUpdateJobSlice is retrieved from the database
func (o SystemUpdateJobSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = SystemUpdateJobs.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = SystemUpdateJobs.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = SystemUpdateJobs.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = SystemUpdateJobs.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o SystemUpdateJobSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("system_update_job", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o SystemUpdateJobSlice) copyMatchingRows(from ...*SystemUpdateJob) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o SystemUpdateJobSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return SystemUpdateJobs.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *SystemUpdateJob:
				o.copyMatchingRows(retrieved)
			case []*SystemUpdateJob:
				o.copyMatchingRows(retrieved...)
			case SystemUpdateJobSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a SystemUpdateJob or a slice of SystemUpdateJob
				// then run the AfterUpdateHooks on the slice
				_, err = SystemUpdateJobs.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o SystemUpdateJobSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return SystemUpdateJobs.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *SystemUpdateJob:
				o.copyMatchingRows(retrieved)
			case []*SystemUpdateJob:
				o.copyMatchingRows(retrieved...)
			case SystemUpdateJobSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a SystemUpdateJob or a slice of SystemUpdateJob
				// then run the AfterDeleteHooks on the slice
				_, err = SystemUpdateJobs.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o SystemUpdateJobSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals SystemUpdateJobSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := SystemUpdateJobs.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o SystemUpdateJobSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := SystemUpdateJobs.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o SystemUpdateJobSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := SystemUpdateJobs.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// RequestedByUserUser starts a query for related objects on user
func (o *SystemUpdateJob) RequestedByUserUser(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(sqlite.Arg(o.RequestedByUserID))),
	)...)
}

func (os SystemUpdateJobSlice) RequestedByUserUser(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.RequestedByUserID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return Users.Query(append(mods,
		sm.Where(sqlite.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// Node starts a query for related objects on node
func (o *SystemUpdateJob) Node(mods ...bob.Mod[*dialect.SelectQuery]) NodesQuery {
	return Nodes.Query(append(mods,
		sm.Where(Nodes.Columns.ID.EQ(sqlite.Arg(o.NodeID))),
	)...)
}

func (os SystemUpdateJobSlice) Node(mods ...bob.Mod[*dialect.SelectQuery]) NodesQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.NodeID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return Nodes.Query(append(mods,
		sm.Where(sqlite.Group(Nodes.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// JobSystemUpdateJobEvents starts a query for related objects on system_update_job_event
func (o *SystemUpdateJob) JobSystemUpdateJobEvents(mods ...bob.Mod[*dialect.SelectQuery]) SystemUpdateJobEventsQuery {
	return SystemUpdateJobEvents.Query(append(mods,
		sm.Where(SystemUpdateJobEvents.Columns.JobID.EQ(sqlite.Arg(o.ID))),
	)...)
}

func (os SystemUpdateJobSlice) JobSystemUpdateJobEvents(mods ...bob.Mod[*dialect.SelectQuery]) SystemUpdateJobEventsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return SystemUpdateJobEvents.Query(append(mods,
		sm.Where(sqlite.Group(SystemUpdateJobEvents.Columns.JobID).OP("IN", PKArgExpr)),
	)...)
}

func attachSystemUpdateJobRequestedByUserUser0(ctx context.Context, exec bob.Executor, count int, systemUpdateJob0 *SystemUpdateJob, user1 *User) (*SystemUpdateJob, error) {
	setter := &SystemUpdateJobSetter{
		RequestedByUserID: omitnull.From(user1.ID),
	}

	err := systemUpdateJob0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachSystemUpdateJobRequestedByUserUser0: %w", err)
	}

	return systemUpdateJob0, nil
}

func (systemUpdateJob0 *SystemUpdateJob) InsertRequestedByUserUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachSystemUpdateJobRequestedByUserUser0(ctx, exec, 1, systemUpdateJob0, user1)
	if err != nil {
		return err
	}

	systemUpdateJob0.R.RequestedByUserUser = user1

	user1.R.RequestedByUserSystemUpdateJobs = append(user1.R.RequestedByUserSystemUpdateJobs, systemUpdateJob0)

	return nil
}

func (systemUpdateJob0 *SystemUpdateJob) AttachRequestedByUserUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachSystemUpdateJobRequestedByUserUser0(ctx, exec, 1, systemUpdateJob0, user1)
	if err != nil {
		return err
	}

	systemUpdateJob0.R.RequestedByUserUser = user1

	user1.R.RequestedByUserSystemUpdateJobs = append(user1.R.RequestedByUserSystemUpdateJobs, systemUpdateJob0)

	return nil
}

func attachSystemUpdateJobNode0(ctx context.Context, exec bob.Executor, count int, systemUpdateJob0 *SystemUpdateJob, node1 *Node) (*SystemUpdateJob, error) {
	setter := &SystemUpdateJobSetter{
		NodeID: omitnull.From(node1.ID),
	}

	err := systemUpdateJob0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachSystemUpdateJobNode0: %w", err)
	}

	return systemUpdateJob0, nil
}

func (systemUpdateJob0 *SystemUpdateJob) InsertNode(ctx context.Context, exec bob.Executor, related *NodeSetter) error {
	var err error

	node1, err := Nodes.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachSystemUpdateJobNode0(ctx, exec, 1, systemUpdateJob0, node1)
	if err != nil {
		return err
	}

	systemUpdateJob0.R.Node = node1

	node1.R.SystemUpdateJobs = append(node1.R.SystemUpdateJobs, systemUpdateJob0)

	return nil
}

func (systemUpdateJob0 *SystemUpdateJob) AttachNode(ctx context.Context, exec bob.Executor, node1 *Node) error {
	var err error

	_, err = attachSystemUpdateJobNode0(ctx, exec, 1, systemUpdateJob0, node1)
	if err != nil {
		return err
	}

	systemUpdateJob0.R.Node = node1

	node1.R.SystemUpdateJobs = append(node1.R.SystemUpdateJobs, systemUpdateJob0)

	return nil
}

func insertSystemUpdateJobJobSystemUpdateJobEvents0(ctx context.Context, exec bob.Executor, systemUpdateJobEvents1 []*SystemUpdateJobEventSetter, systemUpdateJob0 *SystemUpdateJob) (SystemUpdateJobEventSlice, error) {
	for i := range systemUpdateJobEvents1 {
		systemUpdateJobEvents1[i].JobID = omit.From(systemUpdateJob0.ID)
	}

	ret, err := SystemUpdateJobEvents.Insert(bob.ToMods(systemUpdateJobEvents1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertSystemUpdateJobJobSystemUpdateJobEvents0: %w", err)
	}

	return ret, nil
}

func attachSystemUpdateJobJobSystemUpdateJobEvents0(ctx context.Context, exec bob.Executor, count int, systemUpdateJobEvents1 SystemUpdateJobEventSlice, systemUpdateJob0 *SystemUpdateJob) (SystemUpdateJobEventSlice, error) {
	setter := &SystemUpdateJobEventSetter{
		JobID: omit.From(systemUpdateJob0.ID),
	}

	err := systemUpdateJobEvents1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachSystemUpdateJobJobSystemUpdateJobEvents0: %w", err)
	}

	return systemUpdateJobEvents1, nil
}

func (systemUpdateJob0 *SystemUpdateJob) InsertJobSystemUpdateJobEvents(ctx context.Context, exec bob.Executor, related ...*SystemUpdateJobEventSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	systemUpdateJobEvents1, err := insertSystemUpdateJobJobSystemUpdateJobEvents0(ctx, exec, related, systemUpdateJob0)
	if err != nil {
		return err
	}

	systemUpdateJob0.R.JobSystemUpdateJobEvents = append(systemUpdateJob0.R.JobSystemUpdateJobEvents, systemUpdateJobEvents1...)

	for _, rel := range systemUpdateJobEvents1 {
		rel.R.JobSystemUpdateJob = systemUpdateJob0
	}
	return nil
}

func (systemUpdateJob0 *SystemUpdateJob) AttachJobSystemUpdateJobEvents(ctx context.Context, exec bob.Executor, related ...*SystemUpdateJobEvent) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	systemUpdateJobEvents1 := SystemUpdateJobEventSlice(related)

	_, err = attachSystemUpdateJobJobSystemUpdateJobEvents0(ctx, exec, len(related), systemUpdateJobEvents1, systemUpdateJob0)
	if err != nil {
		return err
	}

	systemUpdateJob0.R.JobSystemUpdateJobEvents = append(systemUpdateJob0.R.JobSystemUpdateJobEvents, systemUpdateJobEvents1...)

	for _, rel := range related {
		rel.R.JobSystemUpdateJob = systemUpdateJob0
	}

	return nil
}

type systemUpdateJobWhere[Q sqlite.Filterable] struct {
	ID                sqlite.WhereMod[Q, string]
	Component         sqlite.WhereMod[Q, string]
	NodeID            sqlite.WhereNullMod[Q, string]
	CurrentVersion    sqlite.WhereMod[Q, string]
	TargetVersion     sqlite.WhereMod[Q, string]
	Status            sqlite.WhereMod[Q, string]
	Phase             sqlite.WhereMod[Q, string]
	ProgressPercent   sqlite.WhereMod[Q, int64]
	Error             sqlite.WhereNullMod[Q, string]
	ArtifactName      sqlite.WhereNullMod[Q, string]
	ArtifactSha256    sqlite.WhereNullMod[Q, string]
	RequestedByUserID sqlite.WhereNullMod[Q, string]
	CreatedAt         sqlite.WhereMod[Q, time.Time]
	UpdatedAt         sqlite.WhereMod[Q, time.Time]
	StartedAt         sqlite.WhereNullMod[Q, time.Time]
	CompletedAt       sqlite.WhereNullMod[Q, time.Time]
}

func (systemUpdateJobWhere[Q]) AliasedAs(alias string) systemUpdateJobWhere[Q] {
	return buildSystemUpdateJobWhere[Q](buildSystemUpdateJobColumns(alias))
}

func buildSystemUpdateJobWhere[Q sqlite.Filterable](cols systemUpdateJobColumns) systemUpdateJobWhere[Q] {
	return systemUpdateJobWhere[Q]{
		ID:                sqlite.Where[Q, string](cols.ID),
		Component:         sqlite.Where[Q, string](cols.Component),
		NodeID:            sqlite.WhereNull[Q, string](cols.NodeID),
		CurrentVersion:    sqlite.Where[Q, string](cols.CurrentVersion),
		TargetVersion:     sqlite.Where[Q, string](cols.TargetVersion),
		Status:            sqlite.Where[Q, string](cols.Status),
		Phase:             sqlite.Where[Q, string](cols.Phase),
		ProgressPercent:   sqlite.Where[Q, int64](cols.ProgressPercent),
		Error:             sqlite.WhereNull[Q, string](cols.Error),
		ArtifactName:      sqlite.WhereNull[Q, string](cols.ArtifactName),
		ArtifactSha256:    sqlite.WhereNull[Q, string](cols.ArtifactSha256),
		RequestedByUserID: sqlite.WhereNull[Q, string](cols.RequestedByUserID),
		CreatedAt:         sqlite.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:         sqlite.Where[Q, time.Time](cols.UpdatedAt),
		StartedAt:         sqlite.WhereNull[Q, time.Time](cols.StartedAt),
		CompletedAt:       sqlite.WhereNull[Q, time.Time](cols.CompletedAt),
	}
}

func (o *SystemUpdateJob) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "RequestedByUserUser":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("systemUpdateJob cannot load %T as %q", retrieved, name)
		}

		o.R.RequestedByUserUser = rel

		if rel != nil {
			rel.R.RequestedByUserSystemUpdateJobs = SystemUpdateJobSlice{o}
		}
		return nil
	case "Node":
		rel, ok := retrieved.(*Node)
		if !ok {
			return fmt.Errorf("systemUpdateJob cannot load %T as %q", retrieved, name)
		}

		o.R.Node = rel

		if rel != nil {
			rel.R.SystemUpdateJobs = SystemUpdateJobSlice{o}
		}
		return nil
	case "JobSystemUpdateJobEvents":
		rels, ok := retrieved.(SystemUpdateJobEventSlice)
		if !ok {
			return fmt.Errorf("systemUpdateJob cannot load %T as %q", retrieved, name)
		}

		o.R.JobSystemUpdateJobEvents = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.JobSystemUpdateJob = o
			}
		}
		return nil
	default:
		return fmt.Errorf("systemUpdateJob has no relationship %q", name)
	}
}

type systemUpdateJobPreloader struct {
	RequestedByUserUser func(...sqlite.PreloadOption) sqlite.Preloader
	Node                func(...sqlite.PreloadOption) sqlite.Preloader
}

func buildSystemUpdateJobPreloader() systemUpdateJobPreloader {
	return systemUpdateJobPreloader{
		RequestedByUserUser: func(opts ...sqlite.PreloadOption) sqlite.Preloader {
			return sqlite.Preload[*User, UserSlice](sqlite.PreloadRel{
				Name: "RequestedByUserUser",
				Sides: []sqlite.PreloadSide{
					{
						From:        SystemUpdateJobs,
						To:          Users,
						FromColumns: []string{"requested_by_user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
		Node: func(opts ...sqlite.PreloadOption) sqlite.Preloader {
			return sqlite.Preload[*Node, NodeSlice](sqlite.PreloadRel{
				Name: "Node",
				Sides: []sqlite.PreloadSide{
					{
						From:        SystemUpdateJobs,
						To:          Nodes,
						FromColumns: []string{"node_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Nodes.Columns.Names(), opts...)
		},
	}
}

type systemUpdateJobThenLoader[Q orm.Loadable] struct {
	RequestedByUserUser      func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Node                     func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	JobSystemUpdateJobEvents func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildSystemUpdateJobThenLoader[Q orm.Loadable]() systemUpdateJobThenLoader[Q] {
	type RequestedByUserUserLoadInterface interface {
		LoadRequestedByUserUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type NodeLoadInterface interface {
		LoadNode(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type JobSystemUpdateJobEventsLoadInterface interface {
		LoadJobSystemUpdateJobEvents(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return systemUpdateJobThenLoader[Q]{
		RequestedByUserUser: thenLoadBuilder[Q](
			"RequestedByUserUser",
			func(ctx context.Context, exec bob.Executor, retrieved RequestedByUserUserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadRequestedByUserUser(ctx, exec, mods...)
			},
		),
		Node: thenLoadBuilder[Q](
			"Node",
			func(ctx context.Context, exec bob.Executor, retrieved NodeLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadNode(ctx, exec, mods...)
			},
		),
		JobSystemUpdateJobEvents: thenLoadBuilder[Q](
			"JobSystemUpdateJobEvents",
			func(ctx context.Context, exec bob.Executor, retrieved JobSystemUpdateJobEventsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadJobSystemUpdateJobEvents(ctx, exec, mods...)
			},
		),
	}
}

// LoadRequestedByUserUser loads the systemUpdateJob's RequestedByUserUser into the .R struct
func (o *SystemUpdateJob) LoadRequestedByUserUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.RequestedByUserUser = nil

	related, err := o.RequestedByUserUser(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.RequestedByUserSystemUpdateJobs = SystemUpdateJobSlice{o}

	o.R.RequestedByUserUser = related
	return nil
}

// LoadRequestedByUserUser loads the systemUpdateJob's RequestedByUserUser into the .R struct
func (os SystemUpdateJobSlice) LoadRequestedByUserUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.RequestedByUserUser(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {
			if !o.RequestedByUserID.IsValue() {
				continue
			}

			if !(o.RequestedByUserID.IsValue() && o.RequestedByUserID.MustGet() == rel.ID) {
				continue
			}

			rel.R.RequestedByUserSystemUpdateJobs = append(rel.R.RequestedByUserSystemUpdateJobs, o)

			o.R.RequestedByUserUser = rel
			break
		}
	}

	return nil
}

// LoadNode loads the systemUpdateJob's Node into the .R struct
func (o *SystemUpdateJob) LoadNode(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Node = nil

	related, err := o.Node(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.SystemUpdateJobs = SystemUpdateJobSlice{o}

	o.R.Node = related
	return nil
}

// LoadNode loads the systemUpdateJob's Node into the .R struct
func (os SystemUpdateJobSlice) LoadNode(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	nodes, err := os.Node(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range nodes {
			if !o.NodeID.IsValue() {
				continue
			}

			if !(o.NodeID.IsValue() && o.NodeID.MustGet() == rel.ID) {
				continue
			}

			rel.R.SystemUpdateJobs = append(rel.R.SystemUpdateJobs, o)

			o.R.Node = rel
			break
		}
	}

	return nil
}

// LoadJobSystemUpdateJobEvents loads the systemUpdateJob's JobSystemUpdateJobEvents into the .R struct
func (o *SystemUpdateJob) LoadJobSystemUpdateJobEvents(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.JobSystemUpdateJobEvents = nil

	related, err := o.JobSystemUpdateJobEvents(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.JobSystemUpdateJob = o
	}

	o.R.JobSystemUpdateJobEvents = related
	return nil
}

// LoadJobSystemUpdateJobEvents loads the systemUpdateJob's JobSystemUpdateJobEvents into the .R struct
func (os SystemUpdateJobSlice) LoadJobSystemUpdateJobEvents(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	systemUpdateJobEvents, err := os.JobSystemUpdateJobEvents(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.JobSystemUpdateJobEvents = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range systemUpdateJobEvents {

			if !(o.ID == rel.JobID) {
				continue
			}

			rel.R.JobSystemUpdateJob = o

			o.R.JobSystemUpdateJobEvents = append(o.R.JobSystemUpdateJobEvents, rel)
		}
	}

	return nil
}

type systemUpdateJobJoins[Q dialect.Joinable] struct {
	typ                      string
	RequestedByUserUser      modAs[Q, userColumns]
	Node                     modAs[Q, nodeColumns]
	JobSystemUpdateJobEvents modAs[Q, systemUpdateJobEventColumns]
}

func (j systemUpdateJobJoins[Q]) aliasedAs(alias string) systemUpdateJobJoins[Q] {
	return buildSystemUpdateJobJoins[Q](buildSystemUpdateJobColumns(alias), j.typ)
}

func buildSystemUpdateJobJoins[Q dialect.Joinable](cols systemUpdateJobColumns, typ string) systemUpdateJobJoins[Q] {
	return systemUpdateJobJoins[Q]{
		typ: typ,
		RequestedByUserUser: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.RequestedByUserID),
					))
				}

				return mods
			},
		},
		Node: modAs[Q, nodeColumns]{
			c: Nodes.Columns,
			f: func(to nodeColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Nodes.Name().As(to.Alias())).On(
						to.ID.EQ(cols.NodeID),
					))
				}

				return mods
			},
		},
		JobSystemUpdateJobEvents: modAs[Q, systemUpdateJobEventColumns]{
			c: SystemUpdateJobEvents.Columns,
			f: func(to systemUpdateJobEventColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, SystemUpdateJobEvents.Name().As(to.Alias())).On(
						to.JobID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
