// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// UserAPIKey is an object representing the database table.
type UserAPIKey struct {
	ID     string           `db:"id,pk" `
	UserID null.Val[string] `db:"user_id" `

	R userAPIKeyR `db:"-" `
}

// UserAPIKeySlice is an alias for a slice of pointers to UserAPIKey.
// This should almost always be used instead of []*UserAPIKey.
type UserAPIKeySlice []*UserAPIKey

// UserAPIKeys contains methods to work with the user_api_key table
var UserAPIKeys = sqlite.NewTablex[*UserAPIKey, UserAPIKeySlice, *UserAPIKeySetter]("", "user_api_key", buildUserAPIKeyColumns("user_api_key"))

// UserAPIKeysQuery is a query on the user_api_key table
type UserAPIKeysQuery = *sqlite.ViewQuery[*UserAPIKey, UserAPIKeySlice]

// userAPIKeyR is where relationships are stored.
type userAPIKeyR struct {
	User *User // fk_user_api_key_0
}

func buildUserAPIKeyColumns(alias string) userAPIKeyColumns {
	return userAPIKeyColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "user_id",
		).WithParent("user_api_key"),
		tableAlias: alias,
		ID:         sqlite.Quote(alias, "id"),
		UserID:     sqlite.Quote(alias, "user_id"),
	}
}

type userAPIKeyColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         sqlite.Expression
	UserID     sqlite.Expression
}

func (c userAPIKeyColumns) Alias() string {
	return c.tableAlias
}

func (userAPIKeyColumns) AliasedAs(alias string) userAPIKeyColumns {
	return buildUserAPIKeyColumns(alias)
}

// UserAPIKeySetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UserAPIKeySetter struct {
	ID     omit.Val[string]     `db:"id,pk" `
	UserID omitnull.Val[string] `db:"user_id" `
}

func (s UserAPIKeySetter) SetColumns() []string {
	vals := make([]string, 0, 2)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if !s.UserID.IsUnset() {
		vals = append(vals, "user_id")
	}
	return vals
}

func (s UserAPIKeySetter) Overwrite(t *UserAPIKey) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if !s.UserID.IsUnset() {
		t.UserID = s.UserID.MustGetNull()
	}
}

func (s *UserAPIKeySetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return UserAPIKeys.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"id"}
		}

	}

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 0, 2)
		if s.ID.IsValue() {
			vals = append(vals, sqlite.Arg(s.ID.MustGet()))
		}

		if !s.UserID.IsUnset() {
			vals = append(vals, sqlite.Arg(s.UserID.MustGetNull()))
		}

		if len(vals) == 0 {
			vals = append(vals, sqlite.Arg(nil))
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s UserAPIKeySetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s UserAPIKeySetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 2)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "id")...),
			sqlite.Arg(s.ID),
		}})
	}

	if !s.UserID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "user_id")...),
			sqlite.Arg(s.UserID),
		}})
	}

	return exprs
}

// FindUserAPIKey retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUserAPIKey(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*UserAPIKey, error) {
	if len(cols) == 0 {
		return UserAPIKeys.Query(
			sm.Where(UserAPIKeys.Columns.ID.EQ(sqlite.Arg(IDPK))),
		).One(ctx, exec)
	}

	return UserAPIKeys.Query(
		sm.Where(UserAPIKeys.Columns.ID.EQ(sqlite.Arg(IDPK))),
		sm.Columns(UserAPIKeys.Columns.Only(cols...)),
	).One(ctx, exec)
}

// UserAPIKeyExists checks the presence of a single record by primary key
func UserAPIKeyExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return UserAPIKeys.Query(
		sm.Where(UserAPIKeys.Columns.ID.EQ(sqlite.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after UserAPIKey is retrieved from the database
func (o *UserAPIKey) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = UserAPIKeys.AfterSelectHooks.RunHooks(ctx, exec, UserAPIKeySlice{o})
	case bob.QueryTypeInsert:
		ctx, err = UserAPIKeys.AfterInsertHooks.RunHooks(ctx, exec, UserAPIKeySlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = UserAPIKeys.AfterUpdateHooks.RunHooks(ctx, exec, UserAPIKeySlice{o})
	case bob.QueryTypeDelete:
		ctx, err = UserAPIKeys.AfterDeleteHooks.RunHooks(ctx, exec, UserAPIKeySlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the UserAPIKey
func (o *UserAPIKey) primaryKeyVals() bob.Expression {
	return sqlite.Arg(o.ID)
}

func (o *UserAPIKey) pkEQ() dialect.Expression {
	return sqlite.Quote("user_api_key", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the UserAPIKey
func (o *UserAPIKey) Update(ctx context.Context, exec bob.Executor, s *UserAPIKeySetter) error {
	v, err := UserAPIKeys.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single UserAPIKey record with an executor
func (o *UserAPIKey) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := UserAPIKeys.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the UserAPIKey using the executor
func (o *UserAPIKey) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := UserAPIKeys.Query(
		sm.Where(UserAPIKeys.Columns.ID.EQ(sqlite.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after UserAPIKeySlice is retrieved from the database
func (o UserAPIKeySlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = UserAPIKeys.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = UserAPIKeys.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = UserAPIKeys.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = UserAPIKeys.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o UserAPIKeySlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Quote("user_api_key", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o UserAPIKeySlice) copyMatchingRows(from ...*UserAPIKey) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o UserAPIKeySlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return UserAPIKeys.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *UserAPIKey:
				o.copyMatchingRows(retrieved)
			case []*UserAPIKey:
				o.copyMatchingRows(retrieved...)
			case UserAPIKeySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a UserAPIKey or a slice of UserAPIKey
				// then run the AfterUpdateHooks on the slice
				_, err = UserAPIKeys.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o UserAPIKeySlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return UserAPIKeys.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *UserAPIKey:
				o.copyMatchingRows(retrieved)
			case []*UserAPIKey:
				o.copyMatchingRows(retrieved...)
			case UserAPIKeySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a UserAPIKey or a slice of UserAPIKey
				// then run the AfterDeleteHooks on the slice
				_, err = UserAPIKeys.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o UserAPIKeySlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UserAPIKeySetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := UserAPIKeys.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o UserAPIKeySlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := UserAPIKeys.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o UserAPIKeySlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := UserAPIKeys.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// User starts a query for related objects on user
func (o *UserAPIKey) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(sqlite.Arg(o.UserID))),
	)...)
}

func (os UserAPIKeySlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.UserID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return Users.Query(append(mods,
		sm.Where(sqlite.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachUserAPIKeyUser0(ctx context.Context, exec bob.Executor, count int, userAPIKey0 *UserAPIKey, user1 *User) (*UserAPIKey, error) {
	setter := &UserAPIKeySetter{
		UserID: omitnull.From(user1.ID),
	}

	err := userAPIKey0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserAPIKeyUser0: %w", err)
	}

	return userAPIKey0, nil
}

func (userAPIKey0 *UserAPIKey) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachUserAPIKeyUser0(ctx, exec, 1, userAPIKey0, user1)
	if err != nil {
		return err
	}

	userAPIKey0.R.User = user1

	user1.R.UserAPIKeys = append(user1.R.UserAPIKeys, userAPIKey0)

	return nil
}

func (userAPIKey0 *UserAPIKey) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachUserAPIKeyUser0(ctx, exec, 1, userAPIKey0, user1)
	if err != nil {
		return err
	}

	userAPIKey0.R.User = user1

	user1.R.UserAPIKeys = append(user1.R.UserAPIKeys, userAPIKey0)

	return nil
}

type userAPIKeyWhere[Q sqlite.Filterable] struct {
	ID     sqlite.WhereMod[Q, string]
	UserID sqlite.WhereNullMod[Q, string]
}

func (userAPIKeyWhere[Q]) AliasedAs(alias string) userAPIKeyWhere[Q] {
	return buildUserAPIKeyWhere[Q](buildUserAPIKeyColumns(alias))
}

func buildUserAPIKeyWhere[Q sqlite.Filterable](cols userAPIKeyColumns) userAPIKeyWhere[Q] {
	return userAPIKeyWhere[Q]{
		ID:     sqlite.Where[Q, string](cols.ID),
		UserID: sqlite.WhereNull[Q, string](cols.UserID),
	}
}

func (o *UserAPIKey) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("userAPIKey cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.UserAPIKeys = UserAPIKeySlice{o}
		}
		return nil
	default:
		return fmt.Errorf("userAPIKey has no relationship %q", name)
	}
}

type userAPIKeyPreloader struct {
	User func(...sqlite.PreloadOption) sqlite.Preloader
}

func buildUserAPIKeyPreloader() userAPIKeyPreloader {
	return userAPIKeyPreloader{
		User: func(opts ...sqlite.PreloadOption) sqlite.Preloader {
			return sqlite.Preload[*User, UserSlice](sqlite.PreloadRel{
				Name: "User",
				Sides: []sqlite.PreloadSide{
					{
						From:        UserAPIKeys,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type userAPIKeyThenLoader[Q orm.Loadable] struct {
	User func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildUserAPIKeyThenLoader[Q orm.Loadable]() userAPIKeyThenLoader[Q] {
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return userAPIKeyThenLoader[Q]{
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadUser loads the userAPIKey's User into the .R struct
func (o *UserAPIKey) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.UserAPIKeys = UserAPIKeySlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the userAPIKey's User into the .R struct
func (os UserAPIKeySlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {
			if !o.UserID.IsValue() {
				continue
			}

			if !(o.UserID.IsValue() && o.UserID.MustGet() == rel.ID) {
				continue
			}

			rel.R.UserAPIKeys = append(rel.R.UserAPIKeys, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

type userAPIKeyJoins[Q dialect.Joinable] struct {
	typ  string
	User modAs[Q, userColumns]
}

func (j userAPIKeyJoins[Q]) aliasedAs(alias string) userAPIKeyJoins[Q] {
	return buildUserAPIKeyJoins[Q](buildUserAPIKeyColumns(alias), j.typ)
}

func buildUserAPIKeyJoins[Q dialect.Joinable](cols userAPIKeyColumns, typ string) userAPIKeyJoins[Q] {
	return userAPIKeyJoins[Q]{
		typ: typ,
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
