-- +migrate Up
with seeded_games(id) as (values
    ('7_days_to_die'),
    ('abiotic_factor'),
    ('ark_survival_ascended'),
    ('ark_survival_evolved'),
    ('arma_3'),
    ('arma_reforger'),
    ('aska'),
    ('astroneer'),
    ('chivalry_medieval_warfare'),
    ('conan_exiles'),
    ('core_keeper'),
    ('counter_strike_2'),
    ('counter_strike_source'),
    ('dayz'),
    ('dont_starve_together'),
    ('eco'),
    ('empyrion_galactic_survival'),
    ('enshrouded'),
    ('factorio'),
    ('fivem'),
    ('garrys_mod'),
    ('hytale'),
    ('icarus_dedicated'),
    ('killing_floor_2'),
    ('left_4_dead_2'),
    ('minecraft'),
    ('mordhau'),
    ('multi_theft_auto'),
    ('no_more_room_in_hell'),
    ('palworld'),
    ('project_zomboid'),
    ('redm'),
    ('rust'),
    ('satisfactory'),
    ('scp_secret_laboratory'),
    ('sons_of_the_forest'),
    ('soulmask'),
    ('space_engineers'),
    ('squad'),
    ('starbound'),
    ('stationeers'),
    ('sunkenland'),
    ('survive_the_nights'),
    ('team_fortress_2'),
    ('terraria'),
    ('the_forest'),
    ('the_isle'),
    ('trackmania'),
    ('unturned'),
    ('v_rising'),
    ('valheim'),
    ('windrose')
)
update game
set xylona_official = 1
where id in (select id from seeded_games);

-- +migrate Down
-- Restore only seed rows that were non-official before this migration.
with seeded_games(id) as (values
    ('7_days_to_die'),
    ('abiotic_factor'),
    ('ark_survival_ascended'),
    ('ark_survival_evolved'),
    ('arma_3'),
    ('arma_reforger'),
    ('aska'),
    ('astroneer'),
    ('chivalry_medieval_warfare'),
    ('conan_exiles'),
    ('counter_strike_2'),
    ('counter_strike_source'),
    ('dayz'),
    ('dont_starve_together'),
    ('eco'),
    ('empyrion_galactic_survival'),
    ('factorio'),
    ('fivem'),
    ('garrys_mod'),
    ('icarus_dedicated'),
    ('killing_floor_2'),
    ('left_4_dead_2'),
    ('minecraft'),
    ('mordhau'),
    ('multi_theft_auto'),
    ('no_more_room_in_hell'),
    ('project_zomboid'),
    ('redm'),
    ('rust'),
    ('satisfactory'),
    ('scp_secret_laboratory'),
    ('sons_of_the_forest'),
    ('soulmask'),
    ('space_engineers'),
    ('squad'),
    ('starbound'),
    ('stationeers'),
    ('sunkenland'),
    ('survive_the_nights'),
    ('team_fortress_2'),
    ('terraria'),
    ('the_forest'),
    ('the_isle'),
    ('trackmania'),
    ('unturned')
)
update game
set xylona_official = 0
where id in (select id from seeded_games);
