syntax = "proto3";
import "google/protobuf/timestamp.proto";
import "google/protobuf/any.proto";

package xylona;
option go_package = 'github.com/ClintonCollins/Xylona/proto/go/xylona';


enum GameServerFilesCompressionType {
  ZIP = 0;
  BZIP2 = 1;
  GZIP = 2;
  ZST = 3;
  XZ = 4;
}

message GameServerFilesDeleteRequest {
  string game_server_id = 1;
  repeated string file_paths = 2;
}

message GameServerFilesDeleteResponse {
  repeated string file_paths = 1;
}

message GameServerFilesCompressionRequest {
  string game_server_id = 1;
  repeated string file_paths = 2;
  string file_name = 3;
  GameServerFilesCompressionType compression_type = 4;
  string source_path = 5;
}

message GameServerFilesCompressionResponse {
  string file_path = 1;
}

message GameServerFilesDecompressionRequest {
  string game_server_id = 1;
  string file_path = 2;
  string destination_path = 3;
}

message GameServerFilesDecompressionResponse {
  repeated string file_paths = 1;
}

message GameServersFileDownloadFromURLRequest {
  string game_server_id = 1;
  string url = 2;
  string destination_path = 3; // The path to save the file to (Not including the file name)
}

message GameServersFileDownloadFromURLResponse {
  string file_path = 1;
}

message GameServerFileRenameRequest {
  string game_server_id = 1;
  string old_path = 2;
  string new_path = 3;
}

message GameServerFileRenameResponse {
  string old_path = 1;
  string new_path = 2;
}

message GameServerFilesMoveRequest {
  string game_server_id = 1;
  repeated string file_paths = 2;
  string destination = 3;
}

message GameServerFilesMoveResponse {
  repeated string file_paths = 1;
}

message GameServersFileEditRequest {
  string game_server_id = 1;
  string file_path = 2;
  string content = 3;
}

message GameServersFileEditResponse {
}