syntax = "proto3";
import "google/protobuf/timestamp.proto";
import "google/protobuf/any.proto";

package xylona;
option go_package = 'github.com/ClintonCollins/Xylona/proto/go/xylona';


enum GameServerFilesCompressionType {
  ZIP = 0;
  BZIP2 = 1;
  GZIP = 2;
  ZST = 3;
  XZ = 4;
}

message GameServerFilesDeleteRequest {
  string game_server_id = 1;
  repeated string full_file_paths = 2;
}

message GameServerFilesDeleteResponse {
  repeated string full_file_paths = 1;
}

message GameServerFilesCompressionRequest {
  string game_server_id = 1;
  repeated string full_file_paths = 2;
  string full_destination_file_path = 3;
  GameServerFilesCompressionType compression_type = 4;
}

message GameServerFilesCompressionResponse {
  string full_file_path = 1;
}

message GameServerFilesDecompressionRequest {
  string game_server_id = 1;
  string full_file_path = 2;
  string destination_base_path = 3;
}

message GameServerFilesDecompressionResponse {
  repeated string full_file_paths = 1;
}

message GameServersFileDownloadFromURLRequest {
  string game_server_id = 1;
  string url = 2;
  string destination_base_path = 3; // The path to save the file to (Not including the file name)
}

message GameServersFileDownloadFromURLResponse {
  string file_path = 1;
}

message GameServerFileRenameRequest {
  string game_server_id = 1;
  string old_path = 2;
  string new_path = 3;
}

message GameServerFileRenameResponse {
  string old_path = 1;
  string new_path = 2;
}

message GameServerFilesMoveRequest {
  string game_server_id = 1;
  repeated string full_file_paths = 2;
  string destination_base_path = 3;
}

message GameServerFilesMoveResponse {
  repeated string full_file_paths = 1;
}

message GameServersFileEditRequest {
  string game_server_id = 1;
  string full_file_path = 2;
  string content = 3;
}

message GameServersFileEditResponse {
}

message GameServerFileOrDirectoryCreateRequest {
  string game_server_id = 1;
  string full_file_path = 2;
  string content = 3;
  bool is_directory = 4;
}

message GameServerFileOrDirectoryCreateResponse {
}

message DownloadFileRequest {
  string game_server_id = 1;
  string path = 2;
}

message File {
  string name = 1;
  int64 size = 2;
  google.protobuf.Timestamp last_modified = 3;
  bool is_directory = 4;
}

message ListDirectoryFilesRequest {
  string game_server_id = 1;
  string path = 2;
}

message ListDirectoryFilesResponse {
  repeated File files = 1;
}