syntax = "proto3";
import "google/protobuf/timestamp.proto";
import "gameserver_files_operations.proto";
import "shared.proto";
import "federation.proto";
// import "games/minecraft.proto";

package xylona;
option go_package = 'github.com/ClintonCollins/Xylona/proto/go/xylona';

service Xylona {
  // Game Operations
  rpc AddGame (AddGameRequest) returns (AddGameResponse) {}
  rpc EditGame (EditGameRequest) returns (EditGameResponse) {}
  rpc GetGame (GetGameRequest) returns (GetGameResponse) {}
  rpc RemoveGame (RemoveGameRequest) returns (RemoveGameResponse) {}
  rpc ImportGame (ImportGameRequest) returns (ImportGameResponse) {}
  rpc ExportGame (ExportGameRequest) returns (ExportGameResponse) {}
  rpc ListGames (ListGamesRequest) returns (ListGamesResponse) {}

  // General
  rpc Login (LoginRequest) returns (LoginResponse) {}
  rpc Logout (LogoutRequest) returns (LogoutResponse) {}
  rpc CheckUserAuthenticated (CheckUserAuthenticatedRequest) returns (CheckUserAuthenticatedResponse) {}
  rpc CreateUser (CreateUserRequest) returns (CreateUserResponse) {}
  rpc ListUsers (ListUsersRequest) returns (ListUsersResponse) {}
  rpc GetUser (GetUserDetailsRequest) returns (GetUserDetailsResponse) {}
  rpc ListIPs (ListIPsRequest) returns (ListIPsResponse) {}
  rpc AddIP (AddIPRequest) returns (AddIPResponse) {}
  rpc RemoveIP (RemoveIPRequest) returns (RemoveIPResponse) {}

  // Game Server Operations
  rpc CreateGameServer (CreateGameServerRequest) returns (CreateGameServerResponse) {}
  rpc EditGameServer (EditGameServerRequest) returns (EditGameServerResponse) {}
  rpc RemoveGameServer (RemoveGameServerRequest) returns (RemoveGameServerResponse) {}
  rpc StartGameServer (StartGameServerRequest) returns (StartGameServerResponse) {}
  rpc StopGameServer (StopGameServerRequest) returns (StopGameServerResponse) {}
  //  rpc RestartGameServer (RestartGameServerRequest) returns (RestartGameServerResponse) {}
  rpc ReadGameServerOutput (ReadGameServerOutputRequest) returns (ReadGameServerOutputResponse) {}
  rpc SendGameServerInput (SendGameServerInputRequest) returns (SendGameServerInputResponse) {}
  rpc GetGameServer (GetGameServerRequest) returns (GetGameServerResponse) {}
  rpc UpdateGameServer (UpdateGameServerRequest) returns (UpdateGameServerResponse) {}
  //  rpc ReinstallGameServer (ReinstallGameServerRequest) returns (ReinstallGameServerResponse) {}
  //  rpc BackupGameServer (BackupGameServerRequest) returns (BackupGameServerResponse) {}
  rpc ListGameServers (ListGameServersRequest) returns (ListGameServersResponse) {}
  rpc QueryGameServer (QueryGameServerRequest) returns (QueryGameServerResponse) {}

  rpc GetBranches (GetBranchesRequest) returns (GetBranchesResponse) {}
  // File Operations
  rpc ListDirectoryFiles (ListDirectoryFilesRequest) returns (ListDirectoryFilesResponse) {}
  rpc GameServerFilesDelete (GameServerFilesDeleteRequest) returns (GameServerFilesDeleteResponse) {}
  rpc GameServerFilesArchive (GameServerFilesCompressionRequest) returns (stream GameServerFilesArchiveProgress) {}
  rpc GameServerFilesExtract (GameServerFilesDecompressionRequest) returns (stream GameServerFilesExtractProgress) {}
  rpc GameServerFilesCompress (GameServerFilesCompressionRequest) returns (GameServerFilesCompressionResponse) {}
  rpc GameServerFilesDecompress (GameServerFilesDecompressionRequest) returns (GameServerFilesDecompressionResponse) {}
  rpc GameServerFilesDownloadFromURL (GameServersFileDownloadFromURLRequest) returns (GameServersFileDownloadFromURLResponse) {}
  rpc GameServerFileRename (GameServerFileRenameRequest) returns (GameServerFileRenameResponse) {}
  rpc GameServerFilesMove (GameServerFilesMoveRequest) returns (GameServerFilesMoveResponse) {}
  rpc GameServersFileEdit (GameServersFileEditRequest) returns (GameServersFileEditResponse) {}
  rpc GameServersFileOrDirectoryCreate (GameServerFileOrDirectoryCreateRequest) returns (GameServerFileOrDirectoryCreateResponse) {}

  // Nodes
  rpc GetNode (GetNodeRequest) returns (GetNodeResponse) {}
  rpc ListNodes (ListNodesRequest) returns (ListNodesResponse) {}
  rpc AddNode (AddNodeRequest) returns (AddNodeResponse) {}
  rpc RemoveNode (RemoveNodeRequest) returns (RemoveNodeResponse) {}
  rpc EditNode (EditNodeRequest) returns (EditNodeResponse) {}
  // Used to reach out to a new node and verify we're authorized when adding it.
  rpc VerifyNode (VerifyNodeRequest) returns (VerifyNodeResponse) {}
  rpc ListLocalSecretKeys (ListLocalSecretKeysRequest) returns (ListLocalSecretKeysResponse) {}
  rpc CreateLocalSecretKey (CreateLocalSecretKeyRequest) returns (CreateLocalSecretKeyResponse) {}
  rpc DeleteLocalSecretKey (DeleteLocalSecretKeyRequest) returns (DeleteLocalSecretKeyResponse) {}

  rpc SyncNode (SyncNodeRequest) returns (SyncNodeResponse) {}

  // Aggregated Views
  rpc ListAggregatedGameServers (ListAggregatedGameServersRequest) returns (ListAggregatedGameServersResponse) {}
}

message LoginRequest {
  string user_name = 1;
  string password = 2;
}

message LoginResponse {
  User user = 1;
}

message CreateUserRequest {
  string user_name = 1;
  string email = 2;
  string password = 3;
  string first_name = 4;
  string last_name = 5;
  bool super_user = 6;
}

message CreateUserResponse {
  User user = 1;
  optional Error error = 2;
}

message LogoutRequest {}

message LogoutResponse {}

message CheckUserAuthenticatedRequest {}

message CheckUserAuthenticatedResponse {
  bool authenticated = 1;
  User user = 2;
}

message ListGameServersRequest {}

message ListGameServersResponse {
  repeated GameServer game_servers = 1;
}

message ListGamesRequest {}

message ListGamesResponse {
  repeated Game games = 1;
}

message GetGameRequest {
  string id = 1;
}

message GetGameResponse {
  Game game = 1;
}

message GetGameServerRequest {
  string id = 1;
}

message GetGameServerResponse {
  GameServer game_server = 1;
}

message User {
  string id = 1;
  string user_name = 2;
  string email = 3;
  string first_name = 4;
  string last_name = 5;
  bool super_user = 6;
  google.protobuf.Timestamp last_login = 7;
  google.protobuf.Timestamp created_at = 8;
}

message ListUsersRequest {}

message ListUsersResponse {
  repeated User users = 1;
}

message GetUserDetailsRequest {
  string id = 1;
}

message GetUserDetailsResponse {
  User user = 1;
}

enum NotificationEvent {
  SERVER_STARTED = 0;
  SERVER_STOPPED = 1;
  SERVER_UPDATING = 2;
  SERVER_FINISHED_UPDATE = 3;
  SERVER_INSTALLING = 4;
  SERVER_FINISHED_INSTALL = 5;
  MISCELLANEOUS = 6;
}

message NotificationStreamRequest {}

message NotificationStreamResponse {
  NotificationEvent event = 1;
  GameServer game_server = 2;
  string message = 3;
  string error = 4;
}

message GetBranchesRequest {
  string game_id = 1;
}

message GetBranchesResponse {
  repeated SteamBranch branches = 1;
}

message ListIPsRequest {}

message ListIPsResponse {
  repeated IP ips = 1;
}

message AddIPRequest {
  IP ip = 1;
}

message AddIPResponse {}

message RemoveIPRequest {
  IP ip = 1;
}

message RemoveIPResponse {}

message AddGameRequest {
  Game game = 1;
}

message AddGameResponse {
  Game game = 1;
  optional Error error = 2;
}

message EditGameRequest {
  string game_id = 1;
  Game game = 2;
}

message EditGameResponse {
  Game game = 1;
}

message RemoveGameRequest {
  string game_id = 1;
}

message RemoveGameResponse {
}

message ImportGameRequest {
  string file_path = 1;
}

message ImportGameResponse {
  Game game = 1;
  optional Error error = 2;
}

message ExportGameRequest {
  string game_id = 1;
  string file_path = 2;
}

message ExportGameResponse {
  GameServer game_server = 1;
}

message UpdateGameServerRequest {
  string server_id = 1;
}
message UpdateGameServerResponse {}

message ReinstallGameServerRequest {
  string server_id = 1;
}
message ReinstallGameServerResponse {
  GameServer game_server = 1;
}

message BackupGameServerRequest {
  string server_id = 1;
}
message BackupGameServerResponse {}

message QueryGameServerRequest {
  string server_id = 1;
}

message QueryGameServerResponse {
  ServerQuery query_info = 1;
}

message GetNodeRequest {
  string node_id = 1;
}

message GetNodeResponse {
  Node node = 1;
}

message ListNodesRequest {}

message ListNodesResponse {
  repeated Node nodes = 1;
}

message AddNodeRequest {
  Node node = 1;
}

message AddNodeResponse {
  Node node = 1;
}

message RemoveNodeRequest {
  string node_id = 1;
}

message RemoveNodeResponse {
  Node node = 1;
}

message EditNodeRequest {
  Node node = 1;
}

message EditNodeResponse {
  Node node = 1;
}

message VerifyNodeRequest {
  string secret_key = 1;
}

message VerifyNodeResponse {
  Node node = 1;
}

message ListLocalSecretKeysRequest {
}

message ListLocalSecretKeysResponse {
  repeated SecretKey secret_keys = 1;
}

message CreateLocalSecretKeyRequest {
  string node_id = 1;
  string name = 2;
}

message CreateLocalSecretKeyResponse {
  int32 id = 1;
  string secret_key = 2;
}

message DeleteLocalSecretKeyRequest {
  int32 id = 1;
}

message DeleteLocalSecretKeyResponse {}