<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Release</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <OutputType>Library</OutputType>
    <RootNamespace>Xylona.SevenDaysToDie</RootNamespace>
    <AssemblyName>XylonaLandClaims</AssemblyName>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <LangVersion>8</LangVersion>
    <NoStdLib>true</NoStdLib>
    <Optimize>true</Optimize>
    <Deterministic>true</Deterministic>
    <DebugType>none</DebugType>
    <IntermediateOutputPath>obj\v2.6\$(Configuration)\</IntermediateOutputPath>
    <OutputPath>..\..\internal\controller\api\rpc\seven-days-to-die-land-claims\v2.6\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameReferences)\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="mscorlib">
      <HintPath>$(GameReferences)\mscorlib.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System">
      <HintPath>$(GameReferences)\System.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameReferences)\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Utf8Json">
      <HintPath>$(GameReferences)\Utf8Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="WebServer">
      <HintPath>$(WebServerReference)</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="src\AssemblyInfo.cs" />
    <Compile Include="src\LandClaims.cs" />
    <Compile Include="src\ModApi.cs" />
    <EmbeddedResource Include="src\GetLandClaims.openapi.yaml" />
  </ItemGroup>
  <Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />
</Project>
